import React,{useState,useEffect,useRef} from 'react';
import {ArrowLeft,Settings2,Volume2,VolumeX,Maximize,Minimize,Play,SkipForward,RotateCcw,X,Zap,Target,Timer,ChevronRight,HelpCircle} from 'lucide-react';
import {ANIMALS,STORAGE_KEY,SHOT_MS,createMatch,scores,availableTeams,currentTeam,currentRound,winners,shotOptions,adjustment,transition,recoverMatch,randomUnit} from './basketball-model.mjs';
import {BasketballAudio} from './BasketballAudio';
import './basketball.css';

const asset=name=>`/basketball/${name}`;
const defaultTeams=()=>ANIMALS.map((a,i)=>({name:`Team ${i+1}`,animal:a.id}));
const defaults={music:.28,sounds:.55,ambience:.16,muted:false,timer:0,powerups:true,reduced:false};
function readSettings(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY+'-settings'));return {...defaults,...Object.fromEntries(['music','sounds','ambience'].filter(k=>typeof p?.[k]==='number'&&p[k]>=0&&p[k]<=1).map(k=>[k,p[k]])),...Object.fromEntries(['muted','powerups','reduced'].filter(k=>typeof p?.[k]==='boolean').map(k=>[k,p[k]])),timer:[0,15,30,60].includes(p?.timer)?p.timer:0};}catch{return defaults;}}
function readSaved(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw||raw.length>250000)return null;return recoverMatch(JSON.parse(raw));}catch{return null;}}
const B=({en,zh})=><span className="bb-bilingual">{en}<small>{zh}</small></span>;
export function AnimalSprite({id,pose=0,className='',label=true}){const a=ANIMALS.find(x=>x.id===id)||ANIMALS[0];return <span role={label?'img':undefined} aria-label={label?`${a.name} ${['ready to play','shooting','celebrating','after a missed shot'][pose]}`:undefined} aria-hidden={!label||undefined} className={`bb-sprite ${pose===0?'bb-idle':''} ${className}`} style={{'--idle-delay':`${-ANIMALS.indexOf(a)*.37}s`,'--idle-duration':`${2.2+ANIMALS.indexOf(a)*.17}s`,backgroundImage:`url("${asset(a.sheet+'.png')}")`,backgroundPosition:`${pose*100/3}% ${a.row*100}%`}}/>;}
function Dialog({label,children,onClose}){const ref=useRef();useEffect(()=>{const before=document.activeElement;ref.current?.focus();return()=>before?.focus?.();},[]);return <div className="bb-overlay" onKeyDown={e=>{if(e.key==='Escape'&&onClose){e.stopPropagation();onClose();}if(e.key==='Tab'){const items=[...ref.current.querySelectorAll('button:not(:disabled),input,select,[tabindex="0"]')];if(!items.length){e.preventDefault();return;}const i=items.indexOf(document.activeElement);if(e.shiftKey&&i<=0){e.preventDefault();items.at(-1).focus();}if(!e.shiftKey&&(i===items.length-1||i===-1)){e.preventDefault();items[0].focus();}}}}><section ref={ref} tabIndex={-1} className="bb-dialog" role="dialog" aria-modal="true" aria-label={label}>{onClose&&<button className="bb-close" aria-label="Close dialog" onClick={onClose}><X/></button>}{children}</section></div>;}
function Hoop({hit}){return <g className={hit?'bb-net-hit':''}><path d="M115 606 L133 261 Q132 238 151 238 L155 610Z" fill="#954bdd" stroke="white" strokeWidth="12"/><path d="M140 274 L229 274 L229 333 L140 333Z" fill="#1c143d" stroke="white" strokeWidth="9"/><path d="M169 292 H212 V320 H169Z" fill="none" stroke="#fdac65" strokeWidth="4"/><path className="bb-net" d="M156 335 L170 385 Q188 398 207 385 L220 335 M159 344 L212 369 M162 358 L204 387 M216 344 L166 369 M212 358 L174 387 M178 337 L179 390 M200 337 L196 390" fill="none" stroke="white" strokeWidth="5" strokeLinejoin="round"/><rect x="147" y="324" width="84" height="15" rx="7" fill="#ff694a" stroke="white" strokeWidth="6"/><path d="M152 328 H225" stroke="#ffc758" strokeWidth="4"/></g>;}
function Basketball({x,y,angle=0,opacity=1}){return <g transform={`translate(${x} ${y}) rotate(${angle})`} opacity={opacity}><circle r="20" fill="#ff923e" stroke="#fff9df" strokeWidth="5"/><circle r="18" fill="none" stroke="#341640" strokeWidth="2.5"/><path d="M-18 0H18 M0-18V18 M-12-14Q10 0-12 14 M12-14Q-10 0 12 14" fill="none" stroke="#341640" strokeWidth="2.3"/><path d="M-10-10Q-3-17 4-13" fill="none" stroke="#ffe4ac" strokeWidth="3"/></g>;}
const positions={1:420,2:615,3:810,4:925};
function ballPoint(pending,progress){const x=(positions[pending?.shot]||615)-35;if(progress<.2)return {x,y:485-140*(progress/.2)};const t=Math.min(1,(progress-.2)/.48),endX=pending.hit?190:230;const bx=(1-t)**2*x+2*(1-t)*t*((x+endX)/2)+t*t*endX,by=(1-t)**2*345+2*(1-t)*t*(-100)+t*t*334;if(progress<=.68)return {x:bx,y:by};const v=(progress-.68)/.32;return pending.hit?{x:190+v*45,y:334+230*v-60*Math.sin(v*Math.PI*2)}:{x:230+250*v,y:334+230*v-135*Math.sin(v*Math.PI)};}

export default function BasketballGame({onExit,preferences}){
 const [teams,setTeams]=useState(defaultTeams),[count,setCount]=useState(2),[rounds,setRounds]=useState(6),[s,setS]=useState(null),[saved,setSaved]=useState(readSaved),[options,setOptions]=useState(readSettings),[dialog,setDialog]=useState(null),[picker,setPicker]=useState(null),[error,setError]=useState(''),[storageError,setStorageError]=useState(''),[full,setFull]=useState(false),[hidden,setHidden]=useState(document.hidden),[progress,setProgress]=useState(0),[remaining,setRemaining]=useState(0),[extra,setExtra]=useState(1),[loaded,setLoaded]=useState(false),[assetError,setAssetError]=useState(false);
 const root=useRef(),state=useRef(null),audio=useRef(new BasketballAudio()),elapsed=useRef(0),cues=useRef({}),clock=useRef(0),optionsRef=useRef(options);optionsRef.current=options;
 const managed=!s;
 const storeMatch=next=>{state.current=next;setS(next);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setStorageError('');}catch{setStorageError('This browser cannot save your match. Keep this tab open.');}};
 const act=a=>{const old=state.current,next=transition(old,a);if(next!==old){storeMatch(next);return true;}return false;};
 useEffect(()=>{window.scrollTo(0,0);let live=true;Promise.all(['cat-dog.png','rabbit-panda.png','fox-penguin.png','court.png'].map(f=>new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(true);img.onerror=()=>resolve(false);img.src=asset(f);}))).then(ok=>{if(live){setLoaded(ok.every(Boolean));setAssetError(ok.some(x=>!x));}});return()=>{live=false;};},[]);
 useEffect(()=>{audio.current.configure(options);try{localStorage.setItem(STORAGE_KEY+'-settings',JSON.stringify(options));}catch{}},[options]);
 useEffect(()=>{const visibility=()=>setHidden(document.hidden),fullscreen=()=>setFull(document.fullscreenElement===root.current);document.addEventListener('visibilitychange',visibility);document.addEventListener('fullscreenchange',fullscreen);return()=>{document.removeEventListener('visibilitychange',visibility);document.removeEventListener('fullscreenchange',fullscreen);audio.current.dispose();};},[]);
 useEffect(()=>{if(hidden||!s){audio.current.pause();return;}audio.current.start();return()=>audio.current.pause();},[hidden,!!s]);
 useEffect(()=>{if(s?.phase==='shooting'){elapsed.current=0;cues.current={};setProgress(0);}},[s?.phase]);
 useEffect(()=>{if(s?.phase!=='shooting'||hidden)return;let id,last=performance.now();const duration=options.reduced?1000:SHOT_MS;const frame=now=>{const dt=Math.min(now-last,100);last=now;elapsed.current+=dt;const p=Math.min(elapsed.current/duration,1);setProgress(p);if(p>=.2&&!cues.current.release){cues.current.release=true;audio.current.shoot();}if(p>=.68&&!cues.current.rim){cues.current.rim=true;s.pending.hit?audio.current.hit():audio.current.miss();}if(p>=1){act({type:'RESOLVE'});return;}id=requestAnimationFrame(frame);};id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id);},[s?.phase,hidden]);
 useEffect(()=>{if(s?.phase==='aim'){clock.current=options.timer*1000;setRemaining(options.timer);}},[s?.phase]);
 useEffect(()=>{if(s?.phase!=='aim'||!options.timer||hidden||dialog)return;let last=performance.now();const id=setInterval(()=>{const now=performance.now();clock.current-=Math.min(now-last,500);last=now;setRemaining(Math.max(0,Math.ceil(clock.current/1000)));if(clock.current<=0)act({type:'SKIP'});},100);return()=>clearInterval(id);},[s?.phase,hidden,dialog,options.timer]);
 useEffect(()=>{if(s?.phase==='finished')audio.current.win();return()=>audio.current.stopCelebration();},[s?.phase]);
 async function unlock(){await audio.current.unlock();audio.current.configure(optionsRef.current);}
 function start(){try{window.scrollTo(0,0);setError('');const next=createMatch(teams.slice(0,count),rounds,options.powerups);unlock().then(()=>audio.current.start());storeMatch(next);setSaved(null);}catch(e){setError(e.message);}}
 function restart(){setTeams(state.current.teams.concat(defaultTeams().filter(t=>!state.current.teams.some(a=>a.animal===t.animal))));setCount(state.current.teams.length);setRounds(Math.min(10,state.current.totalRounds));state.current=null;setS(null);setSaved(null);setDialog(null);try{localStorage.removeItem(STORAGE_KEY);}catch{}}
 function restore(){window.scrollTo(0,0);unlock().then(()=>audio.current.start());storeMatch(saved);setSaved(null);}
 function chooseAnimal(id){setTeams(old=>old.map((t,i)=>i===picker?{...t,animal:id}:t));setPicker(null);}
 function resizeCount(n){setCount(n);setTeams(old=>{const next=old.slice(0,n),used=new Set();return Array.from({length:6},(_,i)=>{const t=next[i]||{name:`Team ${i+1}`,animal:null};let a=t.animal;if(!a||used.has(a))a=ANIMALS.find(x=>!used.has(x.id)).id;used.add(a);return {...t,animal:a};});});}
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await root.current.requestFullscreen();}catch{setStorageError('Full screen is unavailable. Use your browser full-screen control.');}}
 const setting=(k,v)=>setOptions(o=>({...o,[k]:v}));
 const pts=s?scores(s):[],last=s?.history.at(-1),active=s?(s.phase==='result'?last.team:currentTeam(s)):0,animal=s?ANIMALS.find(a=>a.id===s.teams[active].animal):ANIMALS[0],round=s?(s.phase==='result'?last.round:currentRound(s)):1;
 const choosing=s?.phase==='ready',remainingTeams=s?availableTeams(s):[];
 const shooting=s?.phase==='shooting',result=s?.phase==='result',final=s?.phase==='finished',pending=s?.pending,shotX=positions[shooting?pending.shot:result?last.shot:2]||615;
 const pose=shooting?(progress<.2?0:1):result?(last.skipped?0:last.hit?2:3):0,point=shooting?ballPoint(pending,progress):{x:shotX-48,y:485};
 const shownOdds=s?shotOptions(result?{...s,history:s.history.slice(0,-1),activeTeam:last.team,boost:last.boost}:s):[];
 const winnerIds=s?winners(s):[],ranked=s?s.teams.map((t,i)=>({...t,index:i,score:pts[i]})).sort((a,b)=>b.score-a.score):[];
 const podiumGroups=s?[...new Set(ranked.map(t=>t.score))].slice(0,3).map(score=>({score,rank:1+ranked.filter(t=>t.score>score).length,members:ranked.filter(t=>t.score===score)})):[];
 return <main ref={root} className={`bb-app ${managed?'bb-management':''} ${options.reduced?'bb-reduced':''}`}>
  <header className="bb-toolbar"><button className="bb-text-button" onClick={()=>s?setDialog('leave'):onExit()}><ArrowLeft size={20}/>{managed?<B en="Game collection" zh="遊戲大集合"/>:'Game collection'}</button><span className="bb-wordmark">CLASSROOM CLUB <i>COURTSIDE</i></span><div><button aria-label={options.muted?'Unmute all audio':'Mute all audio'} onClick={()=>{unlock();setting('muted',!options.muted);}}>{options.muted?<VolumeX/>:<Volume2/>}</button><button aria-label="Settings" disabled={shooting} onClick={()=>setDialog('settings')}><Settings2/></button><button aria-label={full?'Exit full screen':'Full screen'} onClick={fullscreen}>{full?<Minimize/>:<Maximize/>}</button></div></header>
  {storageError&&<p className="bb-warning" role="alert">{storageError}</p>}
  {managed?<section className="bb-setup">
   <div className="bb-setup-heading"><span className="bb-kicker">PICK YOUR SQUAD. OWN THE COURT.</span><h1>ANIMAL<br/><em>BASKETBALL</em></h1><p>動物投籃爭霸賽 · Choose your teams</p></div>
   <div className="bb-setup-body"><div className="bb-setup-controls"><div><label><B en="Teams" zh="組別數量"/></label><div className="bb-segments">{[2,3,4,5,6].map(n=><button key={n} aria-label={`${n} teams`} aria-pressed={count===n} onClick={()=>resizeCount(n)}>{n}</button>)}</div></div><div><label htmlFor="bb-rounds"><B en="Rounds" zh="回合數（每組各一次）"/></label><select id="bb-rounds" value={rounds} onChange={e=>setRounds(+e.target.value)}>{Array.from({length:10},(_,i)=><option key={i} value={i+1}>{i+1} {i?'rounds':'round'}</option>)}</select></div><button className="bb-option-button" onClick={()=>setDialog('settings')}><Settings2/><B en="Options" zh="音效與遊戲設定"/></button></div>
   <div className="bb-team-grid">{teams.slice(0,count).map((team,i)=>{const a=ANIMALS.find(x=>x.id===team.animal);return <article key={i} className="bb-team-card" style={{'--team-color':a.color}}><span className="bb-team-number">{String(i+1).padStart(2,'0')}</span><button className="bb-select-animal" onClick={()=>setPicker(i)} aria-label={`Choose animal for team ${i+1}`}><AnimalSprite id={a.id}/><span>{a.name} <small>{a.zh} · 更換角色</small></span></button><label className="bb-name-label" htmlFor={`bb-name-${i}`}>Team name <small>組別名稱</small></label><input id={`bb-name-${i}`} maxLength={24} value={team.name} onChange={e=>setTeams(old=>old.map((t,j)=>i===j?{...t,name:e.target.value}:t))}/></article>;})}</div>
   {saved&&<div className="bb-resume"><div><strong>Pick up where you left off</strong><small>找到上次比賽 · {saved.teams.length} 組 · {saved.history.length} 次已完成</small></div><button onClick={restore} disabled={!loaded}><B en="Resume match" zh="繼續上次比賽"/></button></div>}
   <div className="bb-setup-footer"><p><strong>{count} TEAMS · {rounds} ROUNDS · {count*rounds} TURNS</strong><span>One shot each. Choose any team. Everyone plays.<br/>老師點選答對組別；每回合各組投一次。</span></p><button className="bb-primary bb-start" disabled={!loaded} onClick={()=>saved?setDialog('new'):start()}><Play fill="currentColor"/><B en={loaded?'LET’S PLAY!':assetError?'Images unavailable':'Loading artwork…'} zh={loaded?'開始比賽':assetError?'圖片載入失敗，請重新整理':'角色圖片載入中'}/></button></div>{error&&<p role="alert">{error}</p>}
   </div>
  </section>:<>
   <section className="bb-court" aria-label="Basketball court" data-phase={s.phase} data-round={round}>
    <div className="bb-court-bg"/>
    <div className="bb-court-shade"/>
    <div className="bb-round"><span>{round===s.totalRounds?'FINAL ROUND':`ROUND ${round}`}</span><small>{round} / {s.totalRounds}</small></div>
    <div className="bb-turn-pill" style={{'--team-color':animal.color}}>{final?'FULL TIME':choosing?'CHOOSE A TEAM':<><span/>{s.teams[active].name}<small>{shooting?'IN THE AIR':result?'SHOT COMPLETE':'YOUR TURN'}</small></>}</div>
    <div className="bb-scoreboard" aria-label="Team scores">{s.teams.map((t,i)=><div key={i} className={!final&&!choosing&&i===active?'active':''} style={{'--team-color':ANIMALS.find(a=>a.id===t.animal).color}}><i/>{t.name}<strong data-team-score={i}>{pts[i]}</strong></div>)}</div>
    <svg className="bb-court-svg" viewBox="0 0 1280 720" aria-hidden="true"><ellipse cx="185" cy="610" rx="86" ry="15" fill="#2b1549" opacity=".25"/><Hoop hit={(shooting&&pending.hit&&progress>.68)||result&&last.hit}/><ellipse cx={shotX} cy="607" rx="72" ry="12" fill="#30204e" opacity=".25"/>{!final&&!choosing&&(!result||!last.skipped)&&<>{shooting&&progress>.2&&progress<.68&&[.045,.03,.015].map((d,i)=>{const trail=ballPoint(pending,Math.max(.2,progress-d));return <circle key={d} cx={trail.x} cy={trail.y} r={10+i*3} fill="#ffd45a" opacity={.12+i*.12}/>;})}<Basketball x={point.x} y={point.y} angle={shooting?progress*900:0} opacity={result?0:1}/></>}</svg>
    {!final&&!choosing&&<div className={`bb-player ${shooting?'is-shooting':''} ${result&&last.hit?'is-celebrating':''}`} style={{left:`${shotX/12.8}%`,'--team-color':animal.color}}><AnimalSprite id={animal.id} pose={pose}/>{winnerIds.length===1&&winnerIds[0]===active&&pts[active]>0&&<span className="bb-crown" aria-label="Current leader">♛</span>}</div>}
    {!final&&!choosing&&<div className="bb-bench" aria-label="Waiting teams">{s.teams.map((t,i)=>i!==active&&<div key={t.animal} style={{'--team-color':ANIMALS.find(a=>a.id===t.animal).color}}><AnimalSprite id={t.animal} pose={result&&last.hit?2:0}/><span>{t.name}</span></div>)}</div>}
    {shooting&&progress>.68&&<div className={`bb-basket-points ${pending.hit?"":"bb-miss-mark"}`}>{pending.hit?`+${pending.points}`:"×"}</div>}
    {result&&<div className={`bb-result-call ${last.hit?'made':'missed'}`} role="status"><strong>{last.skipped?'TURN SKIPPED':last.hit?`+${last.points} · NICE SHOT!`:'SO CLOSE!'}</strong><span>{last.skipped?'Next team, get ready!':last.hit?'Brilliant teamwork!':'You’ll get the next one!'}</span></div>}
    {choosing&&round===s.totalRounds&&s.history.length%s.teams.length===0&&<div className="bb-final-round-banner" aria-hidden="true">Final Round!</div>}{choosing&&<div className="bb-round-picker"><span className="bb-kicker">TEACHER’S CHOICE · ROUND {round}</span><h2>WHO’S READY TO SHOOT?</h2><p>Tap a team. Every team gets one turn this round.</p><div>{s.teams.map((t,i)=>{const done=!remainingTeams.includes(i),a=ANIMALS.find(x=>x.id===t.animal);return <button key={i} disabled={done} aria-label={`Select ${t.name}${done?', completed this round':''}`} style={{'--team-color':a.color}} onClick={()=>{unlock();audio.current.bounce();act({type:'START',team:i});}}><AnimalSprite id={t.animal}/><strong>{t.name}</strong><span>{done?'✓ DONE':'LET’S GO!'}</span></button>;})}</div><small>{s.teams.length-remainingTeams.length} / {s.teams.length} teams finished this round</small></div>}
    {!final&&!choosing&&<div className="bb-shot-strip">{shownOdds.map(o=><button key={o.points} disabled={s.phase!=='aim'} className={shooting&&pending.shot===o.points?'selected':''} aria-label={`Shoot ${o.points} ${o.points===1?'point':'points'}, ${o.odds}% chance`} onClick={()=>{unlock();act({type:'SHOOT',points:o.points,random:randomUnit()});}}><strong>{o.points}</strong><span>{o.odds}%</span><small>{o.points===1?'POINT':'POINTS'}</small></button>)}</div>}
    {s.phase==='aim'&&options.timer>0&&<div className={`bb-shot-clock ${remaining<=5?'urgent':''}`} role="timer" aria-label="Seconds left"><Timer/>{remaining}</div>}
    {final&&<div className="bb-finale"><div className="bb-confetti" aria-hidden="true">{Array.from({length:38},(_,i)=><i key={i} style={{left:`${(i*37)%100}%`,background:['#fbe053','#73f0de','#ff78ba','#b498ff'][i%4],animationDelay:`${-(i%11)*.37}s`,animationDuration:`${2.4+i%4*.5}s`}}/>)}</div><span className="bb-kicker">WHAT A GAME!</span><h2>{winnerIds.length>1?'IT’S A TIE!':`${s.teams[winnerIds[0]].name} WINS!`}</h2><div className={`bb-podium ${podiumGroups.length===1?'bb-shared-podium':''}`}>{[1,0,2].filter(n=>podiumGroups[n]).map(n=>{const g=podiumGroups[n];return <div className={`bb-podium-place place-${n+1}`} key={g.score} style={{flex:g.members.length>1?1.4:1}}><div className="bb-podium-animals">{g.members.map(t=><div key={t.index}><AnimalSprite id={t.animal} pose={2}/><strong>{t.name}</strong></div>)}</div><div className="bb-podium-block"><b>{g.rank}</b><span>{g.score} PTS</span></div></div>;})}</div><div className="bb-final-ranking">{ranked.map(t=><span key={t.index}>{t.name} <b>{t.score}</b></span>)}</div><div className="bb-final-actions"><button onClick={()=>setDialog('restart')}><RotateCcw/>Restart</button><button className="bb-primary" onClick={()=>setDialog('add')}>+ Add rounds</button><button onClick={()=>setDialog('review')}>Score recap</button><button onClick={onExit}>Menu</button></div></div>}
   </section>
   {!final&&<section className="bb-play-dock"><div className="bb-turn-instruction"><span className="bb-kicker">{s.phase==='ready'?'TEACHER’S CONTROL':s.phase==='aim'?'CHOOSE YOUR SHOT':shooting?'HERE WE GO!':'GREAT EFFORT'}</span><strong>{s.phase==='ready'?'Tap the team that is ready to play.':s.phase==='aim'?'More points. A bigger challenge.':shooting?'Watch the ball…':'Every shot is a new chance.'}</strong><small>{s.phase==='aim'?`Live shot chances · ${adjustment(s)>0?'Comeback boost':adjustment(s)<0?'Leader challenge':'Even game'}${s.boost==='focus'?' · Focus +12%':s.boost==='range'?' · 4-pointer unlocked':''}`:'Any order · Each team plays once per round'}</small></div><div className="bb-turn-actions">{choosing&&<span className="bb-in-flight">{remainingTeams.length} TEAMS TO GO</span>}{s.phase==='aim'&&<><button onClick={()=>act({type:'SKIP'})}><SkipForward/>Skip team</button>{s.powerups&&<button className="bb-boost-button" disabled={!!s.boost} onClick={()=>setDialog('boost')}><Zap fill="currentColor"/>{s.boost?'Power-up active':'Power-up'}</button>}</>}{shooting&&<span className="bb-in-flight">BALL IN FLIGHT <span>•••</span></span>}{result&&<button className="bb-primary" onClick={()=>act({type:'NEXT'})}>{s.history.length===s.totalRounds*s.teams.length?'See results':s.history.length%s.teams.length===0?'Next round':'Next team'}<ChevronRight/></button>}</div></section>}
   <div className="bb-audio-bar"><span><Volume2 size={16}/> COURTSIDE SOUND</span>{['music','sounds','ambience'].map(k=><label key={k}>{k==='sounds'?'Effects':k[0].toUpperCase()+k.slice(1)}<input aria-label={`${k} volume`} type="range" min="0" max="1" step=".01" value={options[k]} onChange={e=>{unlock();setting(k,+e.target.value);}}/><output>{options.muted?'OFF':`${Math.round(options[k]*100)}%`}</output></label>)}<button onClick={()=>setDialog('rules')}><HelpCircle size={18}/>How to play</button></div>
  </>}
  {picker!==null&&<Dialog label="Choose an animal" onClose={()=>setPicker(null)}><h2><B en="Choose your animal" zh="選擇動物角色"/></h2><p>Each team has its own animal. 每組角色不重複。</p><div className="bb-animal-picker">{ANIMALS.map(a=>{const taken=teams.slice(0,count).some((t,i)=>i!==picker&&t.animal===a.id);return <button disabled={taken} key={a.id} onClick={()=>chooseAnimal(a.id)} style={{'--team-color':a.color}}><AnimalSprite id={a.id}/><B en={a.name} zh={taken?'其他組已選用':a.zh}/></button>;})}</div></Dialog>}
  {dialog==='settings'&&<Dialog label="Game options" onClose={()=>setDialog(null)}><h2>{managed?<B en="OPTIONS" zh="遊戲設定"/>:'OPTIONS'}</h2><div className="bb-settings">{['music','sounds','ambience'].map((k,i)=><div className="bb-volume-setting" key={k}><label>{managed?<B en={['Music','Sound effects','Ambience'][i]} zh={['背景音樂','投籃與得分音效','環境聲'][i]}/>:['Music','Sound effects','Ambience'][i]}<input aria-label={`${k} level`} type="range" min="0" max="1" step=".01" value={options[k]} onChange={e=>{unlock();setting(k,+e.target.value);}}/><output>{Math.round(options[k]*100)}%</output></label><button onClick={async()=>{await unlock();audio.current.preview(k);}}>▶ {managed?'試聽':'Test'}</button><button aria-label={`Mute ${k}`} onClick={()=>setting(k,options[k]>0?0:defaults[k])}>{options[k]===0?'ON':'OFF'}</button></div>)}<label className="bb-setting-row">{managed?<B en="Power-ups" zh="每次投籃可選一種加強"/>:'Power-ups'}<input type="checkbox" checked={s?s.powerups:options.powerups} disabled={!!s} onChange={e=>setting('powerups',e.target.checked)}/></label><label className="bb-setting-row">{managed?<B en="Shot clock" zh="選分倒數（開始投籃後）"/>:'Shot clock'}<select aria-label="Shot clock" value={options.timer} disabled={!!s} onChange={e=>setting('timer',+e.target.value)}>{[0,15,30,60].map(t=><option key={t} value={t}>{t?`${t} sec`:'OFF'}</option>)}</select></label><label className="bb-setting-row">{managed?<B en="Reduce motion" zh="減少動態"/>:'Reduce motion'}<input type="checkbox" checked={options.reduced} disabled={shooting} onChange={e=>setting('reduced',e.target.checked)}/></label><div className="bb-setting-row">{managed?<B en="Shots / Turn order / Shot odds" zh="每次一球／老師選組／機率常駐顯示"/>:'Shots / Turn order / Shot odds'}<strong>1 / TEACHER CHOICE / SHOW</strong></div></div><button className="bb-primary" onClick={()=>setDialog(null)}>OKAY</button></Dialog>}
  {dialog==='boost'&&<Dialog label="Choose a power-up" onClose={()=>setDialog(null)}><span className="bb-kicker">ONE BOOST · THIS TURN ONLY</span><h2>POWER UP!</h2><div className="bb-boost-picker"><button onClick={()=>{act({type:'BOOST',boost:'focus'});audio.current.boost();setDialog(null);}}><Target size={44}/><strong>FOCUS</strong><span>+12 percentage points<br/>to your shot chances</span></button><button onClick={()=>{act({type:'BOOST',boost:'range'});audio.current.boost();setDialog(null);}}><Zap size={44}/><strong>LONG SHOT</strong><span>Unlock the<br/>4-point shot</span></button></div><p>Your updated chances appear on the court. No guaranteed baskets!</p></Dialog>}
  {dialog==='rules'&&<Dialog label="How to play" onClose={()=>setDialog(null)}><h2>YOUR COURT. YOUR CHOICE.</h2><ol><li>Your teacher taps any available team. Choose 1, 2 or 3 points. Teams marked DONE have already played this round.</li><li>The percentage under each shot is its real chance of going in.</li><li>Teams behind get a small chance boost. Leading teams get a little extra challenge. Anyone can still miss!</li><li>Use one optional power-up: Focus adds 12 percentage points; Long Shot unlocks 4 points.</li><li>Every team plays once per round. Final results appear after the last turn. Ties share the win.</li></ol><p>Scores stay visible all game. Skipping gives 0 points. Music, effects and ambience have separate controls.</p><button className="bb-primary" onClick={()=>setDialog(null)}>LET’S PLAY</button></Dialog>}
  {dialog==='add'&&<Dialog label="Add rounds" onClose={()=>setDialog(null)}><h2>ONE MORE GAME?</h2><p>Keep every point. Add more rounds for all teams.</p><label>Extra rounds <select aria-label="Extra rounds" value={extra} onChange={e=>setExtra(+e.target.value)}>{Array.from({length:10},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label><button className="bb-primary" disabled={s.totalRounds+extra>100} onClick={()=>{act({type:'ADD_ROUNDS',count:extra});setDialog(null);}}>Add {extra} {extra===1?'round':'rounds'}</button>{s.totalRounds+extra>100&&<p>Maximum 100 rounds per match.</p>}</Dialog>}
  {dialog==='review'&&<Dialog label="Score recap" onClose={()=>setDialog(null)}><h2>SCORE RECAP</h2><div className="bb-recap"><table><thead><tr><th>Round</th><th>Team</th><th>Shot</th><th>Chance</th><th>Points</th></tr></thead><tbody>{s.history.map((h,i)=><tr key={i}><td>{h.round}</td><td>{s.teams[h.team].name}</td><td>{h.skipped?'Skipped':h.shot}</td><td>{h.odds===null?'—':`${h.odds}%`}</td><td>+{h.points}</td></tr>)}</tbody></table></div></Dialog>}
  {['restart','leave','new'].includes(dialog)&&<Dialog label={dialog==='leave'?'Leave match?':'Start a new match?'} onClose={()=>setDialog(null)}><h2>{dialog==='leave'?'LEAVE THE COURT?':'START FRESH?'}</h2><p>{dialog==='leave'?'Your saved match will be here when you return.':'This replaces the saved match. Current scores will be cleared.'}</p><div className="bb-confirm-actions"><button onClick={()=>setDialog(null)}>Keep playing</button><button className="bb-primary" onClick={()=>{if(dialog==='leave')onExit();else if(dialog==='new'){setDialog(null);start();}else restart();}}>{dialog==='leave'?'Save & leave':'Start new match'}</button></div></Dialog>}
  {hidden&&s&&<div className="bb-pause" role="status">MATCH PAUSED</div>}
 </main>;
}
