import React,{useEffect,useReducer,useRef,useState} from 'react';
import {ArrowLeft,Play,Pause,Maximize,Volume2,VolumeX,Settings2,Flag,Check,RotateCcw,Download} from 'lucide-react';
import {B} from './Preferences';
import {CHARACTERS,ITEMS,newGame,beachReducer,totalsFor,eventScore} from './beach-model.mjs';
import {BeachCharacter,BeachItem} from './BeachArt';
import BeachDrawing from './BeachDrawing';
import BeachExplore,{actionPhase} from './BeachExplore';
import {BeachAudio} from './BeachAudio';
import {sound} from './sound';
import './beach.css';
const signed=n=>`${n>=0?'+':''}${n}`;
export default function BeachGame({images=[],lesson,onSaveLesson,onExit,preferences,onPreferences}){
 const [mode,setMode]=useState('manual'),[characters,setCharacters]=useState(['taro','wave']),[names,setNames]=useState(['Team Coral','Team Ocean']),[config,setConfig]=useState(null),[name,setName]=useState(lesson?.name||'Our coastal adventure'),[ids,setIds]=useState(lesson?.imageIds||[]),[savedId,setSavedId]=useState(lesson?.id),[status,setStatus]=useState(''),[saving,setSaving]=useState(false);
 const chosen=ids.map(id=>images.find(i=>i.id===id)).filter(Boolean);
 async function save(){setSaving(true);try{if(!name.trim())throw Error('Please enter a lesson name. 請輸入課堂名稱。');const record={id:savedId||crypto.randomUUID(),name:name.trim().slice(0,120),gameId:'beach',imageIds:ids,updatedAt:Date.now()};await onSaveLesson(record);setSavedId(record.id);setStatus('Lesson saved. 課堂已儲存。');}catch(e){setStatus(e.message);}finally{setSaving(false);}}
 if(config)return <BeachMatch config={config} images={chosen} onExit={onExit} onRestart={()=>setConfig(null)} preferences={preferences} onPreferences={onPreferences}/>;
 return <main className="beach-setup"><header><button className="button secondary" onClick={onExit}><ArrowLeft/><B en="Game collection" zh="遊戲大集合"/></button><span className="beach-tag">CLASSROOM CLUB · 02</span></header><section className="beach-intro"><div><span className="beach-tag"><B en="TAIWAN'S EAST COAST" zh="一起守護臺灣東海岸"/></span><h1><B en="Beach Cleanup" zh="東岸淨灘挑戰"/></h1><p><B en="Small steps. A big difference." zh="兩組合作守護海岸，比比誰的收穫最多！"/></p><div className="beach-pills"><span><B en="2 teams" zh="兩大組"/></span><span><B en="6 rounds" zh="六回合"/></span><span><B en="5 trails" zh="五條路徑"/></span></div></div><div className="beach-intro-cast"><BeachCharacter id="taro"/><BeachCharacter id="wave"/></div></section>
 <section className="beach-panel"><h2><B en="01 · Choose how to play" zh="教師先選擇操作方式，整局共同使用"/></h2><div className="beach-mode-options">{[['manual','Tap & collect','手動：點選物品，角色前往撿拾'],['auto','Sit back & explore','自動：選好路徑，角色約 25 秒走完']].map(([id,en,zh])=><button key={id} aria-pressed={mode===id} onClick={()=>setMode(id)}><span>{id==='manual'?'☝':'▶'}</span><B en={en} zh={zh}/>{mode===id&&<Check/>}</button>)}</div></section>
 <section className="beach-panel"><h2><B en="02 · Meet your beach buddies" zh="每組選一位不同角色，六回合固定使用；所有角色能力相同"/></h2><div className="beach-team-setup">{[0,1].map(team=><div key={team}><label><B en={`Team ${team+1} name`} zh={`第 ${team+1} 組名稱`}/><input aria-label={`Team ${team+1} name`} value={names[team]} maxLength={24} onChange={e=>setNames(v=>v.map((n,i)=>i===team?e.target.value:n))}/></label><div className="beach-cast-options">{CHARACTERS.map(c=><button key={c.id} aria-label={`Team ${team+1}: ${c.name}`} disabled={characters[1-team]===c.id} aria-pressed={characters[team]===c.id} onClick={()=>setCharacters(v=>v.map((id,i)=>i===team?c.id:id))}><BeachCharacter id={c.id}/><strong>{c.name}</strong></button>)}</div></div>)}</div></section>
 <section className="beach-panel"><h2><B en="03 · Your lesson, your questions" zh="教師口頭出題；也可依序選用共用圖片庫的圖片"/></h2><label><B en="Lesson name" zh="淨灘課堂名稱"/><input value={name} maxLength={120} aria-label="Beach lesson name" onChange={e=>setName(e.target.value)}/></label><p><B en="Ask one question before each trail. Mark Correct to play, or Retry to try again." zh="每條路徑先答一題，教師按答對後選路；重試不扣分。圖片不足 12 張時會循環使用。"/></p><details><summary><B en={`Question pictures · ${ids.length} selected`} zh="點選圖片可新增或取消；編號就是播放順序"/></summary><div className="beach-image-picker">{images.map(img=><button key={img.id} disabled={!img.url} aria-label={`Question picture ${img.name}`} aria-pressed={ids.includes(img.id)} onClick={()=>setIds(v=>v.includes(img.id)?v.filter(id=>id!==img.id):[...v,img.id])}><img src={img.url} alt={img.name}/>{ids.includes(img.id)&&<b>{ids.indexOf(img.id)+1}</b>}</button>)}</div>{!images.length&&<p><B en="No pictures yet. Oral questions work perfectly!" zh="圖片庫還沒有圖片，也可以直接使用口頭問答。"/></p>}</details><button className="button secondary" disabled={saving} onClick={save}><B en={saving?'Saving…':'Save beach lesson'} zh="儲存淨灘課堂"/></button><p role="status">{status}</p></section>
 <section className="beach-panel"><h2><B en="Every find counts" zh="每條路徑都會遇到七種事件"/></h2><div className="beach-item-guide">{ITEMS.map(i=><div key={i.id}><BeachItem id={i.id}/><strong><B en={i.name} zh={{wood:'漂流木',bottle:'寶特瓶',can:'鐵罐',bag:'塑膠袋',large:'大型垃圾',stone:'踩到碎石摔倒',splinter:'被漂流木刺傷'}[i.id]}/></strong><b className={i.points<0?'negative':''}>{signed(i.points)}</b></div>)}</div><p><B en="Choose a trail. Explore the beach. Leave a cleaner coast." zh="兩組每回合各走一條路徑，六回合共十二條。意外會自動觸發，角色皆有相同機會。"/></p></section>
 <footer className="beach-start"><B en="Ready to make a difference?" zh="手動模式自由點選當區垃圾；自動模式欣賞角色完成淨灘。"/><button className="button primary" disabled={chosen.some(i=>!i.url)||ids.some(id=>!images.some(i=>i.id===id))} onClick={()=>{sound.unlock();setConfig({mode,characters,names});}}><Play/><B en="Let's clean up!" zh="開始淨灘挑戰"/></button></footer></main>;
}
function BeachMatch({config,images,onExit,onRestart,preferences,onPreferences}){
 const [s,dispatch]=useReducer(beachReducer,null,()=>newGame(config,crypto.getRandomValues(new Uint32Array(1))[0]));
 const [modal,setModal]=useState(null),[drawing,setDrawing]=useState(false),[retry,setRetry]=useState(false),[adjustTeam,setAdjustTeam]=useState(0),[points,setPoints]=useState('50'),[reason,setReason]=useState('Teacher correction'),[notice,setNotice]=useState('');
 const audio=useRef(null);if(!audio.current)audio.current=new BeachAudio();
 const [levels,setLevels]=useState(()=>{try{return {...{backgroundVolume:.4,eventVolume:.5},...JSON.parse(localStorage.getItem('beach-audio-v1')||'{}')};}catch{return {backgroundVolume:.4,eventVolume:.5};}});
 const root=useRef(),latest=useRef(),previous=useRef({turn:0,count:0,phase:'question'});latest.current={s,modal,drawing};
 useEffect(()=>{let frame,last;const tick=t=>{if(last!==undefined&&!document.hidden&&!latest.current.modal&&!latest.current.drawing)dispatch({type:'TICK',dt:t-last});last=t;frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);const pause=()=>{if(latest.current.s.phase!=='finished')dispatch({type:'PAUSE',value:true});sound.stopAll();audio.current.stop();};const hidden=()=>{if(document.hidden)pause();};const unload=e=>{if(latest.current.s.phase!=='finished'){e.preventDefault();e.returnValue='';}};document.addEventListener('visibilitychange',hidden);window.addEventListener('blur',pause);window.addEventListener('beforeunload',unload);return()=>{cancelAnimationFrame(frame);document.removeEventListener('visibilitychange',hidden);window.removeEventListener('blur',pause);window.removeEventListener('beforeunload',unload);sound.stopAll();audio.current.stop();};},[]);
 useEffect(()=>{audio.current.sync(sound.context,{active:!s.paused&&!modal&&!drawing,duck:s.phase==='question',muted:preferences.muted,...levels,walking:s.phase==='active'&&actionPhase(s)==='walking'});try{localStorage.setItem('beach-audio-v1',JSON.stringify(levels));}catch{}},[s.paused,s.phase,modal,drawing,preferences.muted,levels,actionPhase(s)]);
 useEffect(()=>{if(s.count>previous.current.count&&s.turn===previous.current.turn)audio.current.pick(s.route.events[s.done.at(-1)]);if(s.phase==='result'&&previous.current.phase!=='result'||s.phase==='finished'&&previous.current.phase!=='finished')audio.current.victory();previous.current={turn:s.turn,count:s.count,phase:s.phase};},[s.count,s.turn,s.phase]);
 const turn=s.plan[s.turn],team=turn.team,total=totalsFor(s.history,s.adjustments),live=s.phase==='active'?eventScore(s.done.map(i=>s.route.events[i])):0;
 const act=a=>{sound.unlock();dispatch(a);};
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await root.current.requestFullscreen();}catch{setNotice('Fullscreen is unavailable in this window.');}}
 function download(){const blob=new Blob([JSON.stringify({game:'Beach Cleanup',names:s.names,characters:s.characters,mode:s.mode,history:s.history,adjustments:s.adjustments,totals:total,plan:s.plan},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='beach-cleanup-results.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <main ref={root} className={`beach-match ${preferences.reduced?'beach-reduced':''}`} data-phase={s.phase} data-mode={s.mode}>
 <header className="beach-match-header"><div><span className="beach-tag">TAIWAN'S EAST COAST</span><h1>Beach Cleanup</h1></div><div className="beach-round"><b>{s.phase==='finished'?'GREAT WORK!':`ROUND ${turn.round} / 6`}</b><span>{Math.floor(s.seconds/60)}:{String(Math.floor(s.seconds%60)).padStart(2,'0')}{s.seconds>=600?' · 10 minutes reached':''}</span></div><div className="beach-actions"><button aria-label="Sound" aria-pressed={!preferences.muted} onClick={()=>{sound.unlock();onPreferences({...preferences,muted:!preferences.muted});}}>{preferences.muted?<VolumeX/>:<Volume2/>}</button><button aria-label="Fullscreen" onClick={fullscreen}><Maximize/></button><button aria-label="Teacher controls" onClick={()=>setModal('teacher')}><Settings2/></button><button aria-label="Leave game" onClick={()=>setModal('exit')}><ArrowLeft/></button></div></header>
 <div className="beach-scoreboard">{[0,1].map(t=><div key={t} className={`beach-score team-${t} ${team===t&&s.phase!=='finished'?'is-turn':''}`}><BeachCharacter id={s.characters[t]}/><div><strong>{s.names[t]}</strong><span>{s.history.filter(h=>h.team===t).length} / 6 trails</span></div><b data-testid={`score-${t}`}>{total[t]+(team===t?live:0)}</b></div>)}</div>
 <section className="beach-stage" aria-label="East coast beach"><div className="beach-coast-label">EAST COAST • TAIWAN</div>
 {s.phase==='active'&&<BeachExplore state={s} drawing={drawing} reduced={preferences.reduced} onPick={index=>act({type:'PICK',index})}/>}
 {s.phase==='question'&&<div className="beach-center-card question"><div><span className="beach-tag">{s.names[team].toUpperCase()} · YOUR TURN</span><h2>{retry?'Give it another try!':'Ready, beach buddies?'}</h2><p>Listen to your teacher.<br/>Answer together, then choose a trail.</p><div className="beach-question-actions"><button className="button secondary" onClick={()=>setRetry(true)} disabled={s.paused}><RotateCcw/>Retry</button><button className="button primary" onClick={()=>{setRetry(false);act({type:'CORRECT'});}} disabled={s.paused}><Check/>Correct</button></div></div>{images.length?<img className="beach-question-image" src={images[s.turn%images.length].url} alt="Question picture"/>:<BeachCharacter id={s.characters[team]}/>}</div>}
 {s.phase==='routes'&&<div className="beach-route-picker"><span className="beach-tag">{s.names[team].toUpperCase()} · LET'S EXPLORE</span><h2>Which trail will you choose?</h2><p>Five trails. A surprise around every bend.</p><div>{turn.routes.map(r=><button key={r.letter} disabled={s.paused} onClick={()=>act({type:'ROUTE',letter:r.letter})} aria-label={`Choose trail ${r.letter}`}><span>TRAIL</span><strong>{r.letter}</strong><span>Let's go →</span></button>)}</div></div>}
 {s.phase==='result'&&<div className="beach-center-card result"><BeachCharacter id={s.characters[team]}/><div><span className="beach-tag">TRAIL {s.route.letter} COMPLETE</span><h2>A cleaner coast!</h2><strong className="beach-big-score" data-testid="route-total">+{s.route.total}</strong><p>{s.names[team]} · {s.route.events.length} events</p><button className="button primary" disabled={s.paused} onClick={()=>act({type:'NEXT'})}>{s.turn===11?'See the results':'Next team'} →</button></div></div>}
 {s.phase==='finished'&&<div className="beach-final"><div className="beach-confetti" aria-hidden="true">{Array.from({length:16},(_,i)=><i key={i} style={{left:(i*6+2)+'%',animationDelay:(i%5*.1)+'s',color:['#f95a97','#e9ae00','#168b88','#9074d5'][i%4]}}>★</i>)}</div><span className="beach-tag">THANK YOU, BEACH BUDDIES!</span><h2>{total[0]===total[1]?'A shared victory!':`${s.names[total[0]>total[1]?0:1]} wins!`}</h2><div className="beach-final-cast"><BeachCharacter id={s.characters[0]}/><span>★</span><BeachCharacter id={s.characters[1]}/></div><p>{s.history.length} trails completed · A brighter coast for everyone.</p><div className="beach-final-rounds">{[0,1].map(t=><div key={t}><strong>{s.names[t]} · {total[t]} points</strong><p>{s.history.filter(h=>h.team===t).map(h=>`R${h.round}: ${h.score}`).join(' · ')||'No completed trails'}</p>{s.adjustments.filter(a=>a.team===t).map((a,i)=><p key={i}>Adjustment: {signed(a.points)} · {a.reason}</p>)}</div>)}</div><div className="beach-question-actions"><button className="button secondary" onClick={download}><Download/>Save results</button><button className="button primary" onClick={onRestart}>Play again</button><button className="button secondary" onClick={onExit}>Game collection</button></div></div>}
 </section><footer className="beach-match-footer"><div className="beach-legend">{ITEMS.map(i=><span key={i.id} title={i.name}><BeachItem id={i.id}/><b className={i.points<0?'negative':''}>{signed(i.points)}</b></span>)}</div>{s.phase!=='finished'&&<button className="button secondary" onClick={()=>act({type:'PAUSE',value:!s.paused})}>{s.paused?<Play/>:<Pause/>}{s.paused?'Resume':'Pause'}</button>}</footer>
 {s.paused&&<div className="beach-pause-banner" role="status">Game paused <button onClick={()=>act({type:'PAUSE',value:false})}>Resume</button></div>}{notice&&<button className="beach-pause-banner" onClick={()=>setNotice('')}>{notice} · Dismiss</button>}
 <BeachDrawing onDrawing={setDrawing} resetKey={s.turn}/>
 {modal&&<div className="beach-modal-backdrop"><section className="beach-modal" role="dialog" aria-modal="true" aria-label={modal==='teacher'?'Teacher controls':'Leave game'}><h2>{modal==='teacher'?'Teacher controls':'Leave this game?'}</h2>{modal==='teacher'?<>{[['backgroundVolume','Ocean & music volume'],['eventVolume','Action sound volume']].map(([key,label])=><label key={key}>{label} · {Math.round(levels[key]*100)}%<input aria-label={label} type='range' min='0' max='100' value={levels[key]*100} onChange={e=>setLevels(v=>({...v,[key]:+e.target.value/100}))}/></label>)}<label>Adjust team<select value={adjustTeam} onChange={e=>setAdjustTeam(+e.target.value)}>{s.names.map((n,i)=><option key={i} value={i}>{n}</option>)}</select></label><label>Points (+ or −)<input type="number" min="-1000" max="1000" step="1" value={points} onChange={e=>setPoints(e.target.value)}/></label><label>Reason<select value={reason} onChange={e=>setReason(e.target.value)}><option>Teacher correction</option><option>Classroom bonus</option><option>Classroom penalty</option></select></label><button className="button secondary" disabled={points.trim()===''||!Number.isInteger(+points)||Math.abs(+points)>1000} onClick={()=>{dispatch({type:'ADJUST',team:adjustTeam,points:+points,reason});setModal(null);}}>Apply adjustment</button><label className="beach-check"><input type="checkbox" checked={preferences.reduced} onChange={e=>onPreferences({...preferences,reduced:e.target.checked})}/>Reduce motion</label><button className="button danger" onClick={()=>setModal('end')}><Flag/>Finish early</button></>:<p>{modal==='end'?'Finish with completed trails only? The current unfinished trail will not count.':'Current game progress is kept only while this game is open. Leave without saving?'}</p>}<div className="beach-question-actions"><button className="button secondary" onClick={()=>setModal(null)}>Back to game</button>{modal!=='teacher'&&<button className="button primary" onClick={()=>{if(modal==='end'){dispatch({type:'END'});setModal(null);}else onExit();}}>{modal==='end'?'Finish game':'Leave game'}</button>}</div></section></div>}
 </main>;
}
