export const WIN_SECONDS=5;
export const CUE_IDS=['ui','peg','pink','reveal','transfer','team','round','music','win'];
export class PlinkOhAudio {
 constructor(){this.context=null;this.buffers=new Map();this.nodes=new Set();this.seen=new Set();this.settings={music:.28,sounds:.6,muted:false};this.musicNode=null;this.generation=0;this.disposed=false;this.loading=null;this.controller=null;this.lastErrors=[];}
 async unlock(){if(this.disposed)throw Error('Audio is closed.');if(!this.context){const Audio=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Audio)throw Error('Audio is unavailable.');this.context=new Audio();this.buses={};for(const name of ['sounds','music']){const gain=this.context.createGain();gain.connect(this.context.destination);this.buses[name]=gain;}this.configure(this.settings);}await this.context.resume();if(this.context.state!=='running')throw Error('Tap Retry sound to enable audio.');}
 async load(){if(this.loading)return this.loading;const generation=this.generation;const controller=new AbortController();this.controller=controller;const timeout=setTimeout(()=>controller.abort(),12000);this.loading=(async()=>{const errors=[];await Promise.all(CUE_IDS.map(async id=>{if(this.buffers.has(id))return;try{const r=await fetch(`/plinkoh/audio/${id}.wav`,{signal:controller.signal});if(!r.ok)throw Error('Unavailable');const b=await this.context.decodeAudioData(await r.arrayBuffer());if(!this.disposed&&generation===this.generation)this.buffers.set(id,b);}catch{errors.push(id);}}));this.lastErrors=errors;return errors;})().finally(()=>{clearTimeout(timeout);this.loading=null;});return this.loading;}
 configure(options){this.settings={...this.settings,...options};if(this.context&&this.buses)for(const [name,gain]of Object.entries(this.buses))gain.gain.setTargetAtTime(this.settings.muted?0:this.settings[name],this.context.currentTime,.025);}
 play(id,eventId){if(!this.context||this.context.state!=='running'||this.disposed||!this.buffers.has(id))return null;if(eventId){if(this.seen.has(eventId))return null;this.seen.add(eventId);if(this.seen.size>3000)this.seen.delete(this.seen.values().next().value);}if(this.settings.muted||!this.buffers.has(id))return null;const node=this.context.createBufferSource();node.buffer=this.buffers.get(id);node.connect(this.buses[id==='music'?'music':'sounds']);this.nodes.add(node);node.onended=()=>{this.nodes.delete(node);node.disconnect();};node.start();return node;}
 startMusic(){if(this.musicNode||!this.buffers.has('music')||this.disposed||this.context?.state!=='running')return;const node=this.context.createBufferSource();node.buffer=this.buffers.get('music');node.loop=true;node.connect(this.buses.music);this.musicNode=node;this.nodes.add(node);node.onended=()=>{this.nodes.delete(node);node.disconnect();};node.start();}
 win(eventId){this.pause();this.winNode=this.play('win',eventId);return this.winNode;}
 stopWin(){if(this.winNode){try{this.winNode.stop();}catch{}this.nodes.delete(this.winNode);try{this.winNode.disconnect();}catch{}this.winNode=null;}}
 pause(){this.winNode=null;for(const n of this.nodes){try{n.stop();}catch{}try{n.disconnect();}catch{}}this.nodes.clear();this.musicNode=null;}
 dispose(){this.disposed=true;this.generation++;this.controller?.abort();this.pause();this.buffers.clear();this.context?.close();}
}
