import React,{useState,useEffect,useRef,useMemo} from 'react';
import {DEFAULTS,STORAGE_KEY,settings,newGame,reduce,restore,save,leaders,turnSeed,dropId,cardsRemaining} from './plinkoh-model.mjs';
import {makeBoard,createDrop,advance,pegPosition,W,H} from './plinkoh-physics.mjs';
import {CARDS,cardById} from './plinkoh-cards.mjs';
import {PlinkOhAudio,WIN_SECONDS} from './PlinkOhAudio';
import './plinkoh.css';
const COLORS=['#ed427c','#932195','#06c7af','#ffae00','#427af1','#f46336','#74c626','#ab62ea','#1fbad7','#ff71c3','#997648','#5867cf','#ed4949','#358e77','#d27d1e'];
const SLOT_COLORS=['#1cf0cb','#fb333f','#bb29ef','#ffbe18','#46c9ee','#62e435','#ff78b6'];
const Label=({en,zh})=><span>{en}{zh&&<small lang="zh-Hant">{zh}</small>}</span>;
export function PlinkBall({skin=0,size=90,label='',rotation=0}){const color=COLORS[skin%COLORS.length];const uid=`ball-${React.useId().replace(/:/g,'')}`;return <svg width={size} height={size} viewBox="0 0 100 100" aria-hidden={!label} aria-label={label||undefined}><defs><clipPath id={uid}><circle cx="50" cy="50" r="44"/></clipPath><radialGradient id={uid+'g'} cx="30%" cy="22%" r="78%"><stop stopColor="#fff" stopOpacity=".5"/><stop offset=".45" stopColor={color}/><stop offset="1" stopColor="#210e52"/></radialGradient></defs><circle cx="50" cy="50" r="46" fill="#371252"/><g clipPath={`url(#${uid})`} transform={`rotate(${rotation} 50 50)`}><circle cx="50" cy="50" r="44" fill={color}/><circle cx="50" cy="50" r="44" fill={`url(#${uid}g)`}/>{[[27,20],[70,19],[48,44],[17,60],[80,59],[47,81]].map(([x,y],i)=>skin%3===0?<path key={i} transform={`translate(${x-10} ${y-9}) scale(.8)`} d="M12 22 C-12 7 3 -5 12 4 C21 -5 36 7 12 22Z" fill="#ffbbda"/>:skin%3===1?<ellipse key={i} cx={x} cy={y} rx="9" ry="12" fill="#fff0a5" transform={`rotate(25 ${x} ${y})`}/>:<path key={i} d={`M${x} ${y-10}l3 7 8 1-6 5 2 8-7-4-7 4 2-8-6-5 8-1Z`} fill="#eaffd3"/>)}</g><ellipse cx="29" cy="23" rx="9" ry="17" transform="rotate(38 29 23)" fill="white" opacity=".8"/>{label&&<text x="50" y="56" textAnchor="middle" fill="white" stroke="#241133" strokeWidth="3" paintOrder="stroke" fontSize={label.length>12?11:15} fontWeight="1000">{label}</text>}</svg>}
function CardArt({card}){return <img className="po-card-art" src={`/plinkoh/cards/${card.id}.svg`} alt="" draggable="false"/>}
function Logo(){return <h1 className="po-logo" aria-label="Plink-oh!">{'Plink-oh!'.split('').map((l,i)=><span key={i} style={{color:['#eb20d6','#63d934','#fae400','#10cbe8','#f89025'][i%5],transform:`rotate(${[4,-6,4,-3][i%4]}deg)`}}>{l}</span>)}</h1>}
function loadStored(){try{return restore(localStorage.getItem(STORAGE_KEY));}catch{return null;}}
export default function PlinkOhGame({preferences={},onExit}){
 const [saved,setSaved]=useState(loadStored);const [cfg,setCfg]=useState(()=>{try{return settings(JSON.parse(localStorage.getItem(STORAGE_KEY+'-settings')||'null')||saved?.config||DEFAULTS)}catch{return settings(saved?.config||DEFAULTS)}});
 const [screen,setScreen]=useState('title'),[state,setState]=useState(null),[frame,setFrame]=useState(null),[paused,setPaused]=useState(false),[dialog,setDialog]=useState(null),[confirm,setConfirm]=useState(null),[notice,setNotice]=useState(''),[audioStatus,setAudioStatus]=useState('idle'),[scale,setScale]=useState(1),[flight,setFlight]=useState({x:570,y:100});
 const stateRef=useRef(null),sim=useRef(null),audio=useRef(null),wrap=useRef(null),boardBox=useRef(null),shell=useRef(null),activeRow=useRef(null),alive=useRef(true),loading=useRef(false);
 if(!audio.current)audio.current=new PlinkOhAudio();
 const commit=a=>{const prev=stateRef.current;if(!prev)return;const next=reduce(prev,a);if(next!==prev){stateRef.current=next;setState(next);if(!save(localStorage,next))setNotice('Could not save progress. Keep this tab open.');}};
 const install=s=>{sim.current=null;setFrame(null);stateRef.current=s;setState(s);setSaved(s);setScreen('game');setPaused(false);setDialog(null);setConfirm(null);if(!save(localStorage,s))setNotice('Could not save progress. Keep this tab open.');};
 const audioSettings=state?.config||cfg;
 useEffect(()=>{audio.current.configure({...audioSettings,muted:!!preferences.muted||audioSettings.muted});},[audioSettings,preferences.muted]);
 useEffect(()=>{try{localStorage.setItem(STORAGE_KEY+'-settings',JSON.stringify(cfg));}catch{setNotice('Settings could not be saved.');}},[cfg]);
 useEffect(()=>{alive.current=true;const quiet=()=>{if(document.hidden){audio.current.pause();setPaused(true);}};document.addEventListener('visibilitychange',quiet);return()=>{alive.current=false;document.removeEventListener('visibilitychange',quiet);audio.current.dispose();};},[]);
 useEffect(()=>{if(!wrap.current)return;const element=wrap.current;const measure=()=>setScale(Math.min(element.clientWidth/1470,element.clientHeight/908));const ro=new ResizeObserver(measure);ro.observe(element);measure();return()=>ro.disconnect();},[screen]);
 const blocked=paused||!!dialog||!!confirm;
 useEffect(()=>{if(screen==='game'&&state?.phase!=='FINISHED'&&!blocked&&audioStatus==='ready')audio.current.startMusic();else audio.current.pause();},[screen,state?.phase,blocked,audioStatus]);
 useEffect(()=>{if(screen!=='game'||blocked||!state||audioStatus==='loading'||audioStatus==='idle')return;const map={ROUND_INTRO:['INTRO_DONE',preferences.reduced?200:1500,'round'],TEAM_INTRO:['INTRO_DONE',preferences.reduced?200:1300,'team'],REVEAL:['TRANSFER',preferences.reduced?200:1350,'reveal'],TRANSFER:['TRANSFER_DONE',preferences.reduced?200:1100,'transfer']};const item=map[state.phase];if(!item)return;audio.current.play(item[2],`${dropId(state)}-${state.phase}`);const id=setTimeout(()=>commit({type:item[0]}),item[1]);return()=>clearTimeout(id);},[screen,state?.phase,state?.round,state?.selected,blocked,preferences.reduced,audioStatus]);
 useEffect(()=>{if(screen!=='game'||state?.phase!=='FINISHED'||state.celebrationDone)return;if(blocked){audio.current.stopWin();commit({type:'CELEBRATION_DONE'});return;}audio.current.win(`win-${state.seed}-${state.turn}`);const timer=setTimeout(()=>{audio.current.stopWin();commit({type:'CELEBRATION_DONE'});},WIN_SECONDS*1000);return()=>{clearTimeout(timer);audio.current.stopWin();};},[screen,state?.phase,state?.celebrationDone,blocked]);
 const board=useMemo(()=>state?makeBoard(state.round,turnSeed(state)):null,[state?.round,state?.seed,state?.selected,state?.turn]);
 useEffect(()=>{if(state?.phase!=='DROPPING'){sim.current=null;return;}if(!sim.current)sim.current=createDrop(board,state.zone,state.config.zones,turnSeed(state)+(state.cardTurn?.attempt||0)*1009,state.cardTurn?.card==='big-ball'?25.2:18);},[state?.phase,board]);
 useEffect(()=>{if(state?.phase!=='DROPPING'||blocked)return;let handle,last=null;const id=dropId(state);const loop=t=>{if(!sim.current)return;if(last===null)last=t;const d=sim.current;const events=advance(d,Math.min((t-last)/1000,.08));last=t;for(const event of events)if(event.type==='peg'||event.type==='pink')audio.current.play(event.type,`${id}-${event.id}`);setFrame({ball:{...d.ball},time:d.time,hit:new Set(d.hit),events:d.events.slice(-18),collision:d.hits.reduce((n,h)=>n+h.points,0)});if(d.done){commit({type:'SETTLE',id,hits:d.hits,slot:d.board.slots[d.slotIndex],slotIndex:d.slotIndex,events:d.events});return;}if(d.failed){commit({type:'RETRY'});setNotice('The ball got stuck. No points were added. Try another drop zone.');return;}handle=requestAnimationFrame(loop);};handle=requestAnimationFrame(loop);return()=>cancelAnimationFrame(handle);},[state?.phase,blocked]);
 useEffect(()=>{activeRow.current?.scrollIntoView({block:'nearest',inline:'nearest'});},[state?.selected,state?.phase]);
 async function enableAudio(){if(loading.current)return;loading.current=true;setAudioStatus('loading');try{await audio.current.unlock();const failures=await audio.current.load();if(alive.current)setAudioStatus(failures.length?'failed':'ready');}catch{if(alive.current)setAudioStatus('failed');}finally{loading.current=false;}}
 function start(){audio.current.pause();setNotice('');install(newGame(cfg,Date.now()));enableAudio();}
 function resume(){if(saved){setNotice(saved.phase==='READY'?'Your unfinished turn is ready to drop again.':'Progress restored.');install(saved);enableAudio();}}
 function exit(){audio.current.pause();onExit();}
 function pause(){audio.current.pause();setPaused(true);setDialog('menu');}
 function closeDialog(){setDialog(null);setPaused(false);audio.current.unlock().catch(()=>setAudioStatus('failed'));}
 function select(id){setFrame(null);commit({type:'SELECT',id});}
 function drop(){if(blocked||audioStatus==='loading'||audioStatus==='failed'||stateRef.current?.phase!=='READY')return;setFrame(null);commit({type:'DROP'});}
 function configure(patch){if(state)commit({type:'CONFIG',patch});else setCfg(c=>settings({...c,...patch}));}
 function request(action,label){setConfirm({action,label});}
 function accept(){const action=confirm.action;setConfirm(null);if(action==='restart'){setCfg(state.config);install(newGame(state.config,Date.now()));enableAudio();}else if(action==='end'){commit({type:'END'});setDialog(null);setPaused(false);}else if(action==='home'){setSaved(loadStored());setScreen('title');setDialog(null);setPaused(false);audio.current.pause();}else if(action==='skip')commit({type:'SKIP'});else commit(action);}
 function exportLog(){if(!state)return;const u=URL.createObjectURL(new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`plinkoh-round-${state.round}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await shell.current.requestFullscreen();}catch{setNotice('Fullscreen is unavailable. Use landscape view or your browser zoom.');}}
 useEffect(()=>{if(state?.phase!=='REVEAL'||!activeRow.current||!boardBox.current)return;const a=activeRow.current.getBoundingClientRect(),b=boardBox.current.getBoundingClientRect();setFlight({x:(a.right-35*scale-b.left-b.width/2)/scale,y:(a.top+25*scale-b.top-45*scale)/scale});},[state?.phase,scale]);
 const shownScore=t=>t.score-(['REVEAL','TRANSFER'].includes(state?.phase)&&state.result?.team===t.id?state.result.total:0);
 const topTeam=state?Math.max(...state.teams.map(shownScore)):0;const current=state?.teams[state.selected];const after=['REVEAL','TRANSFER','TURN_DONE'].includes(state?.phase);const ball=frame?.ball;const displayTime=frame?.time||0;
 const activeCard=cardById(state?.cardTurn?.card);const secondBall=state?.cardTurn?.attempt===1;const ballSize=activeCard?.id==='big-ball'?53.2:38;
 const soundPanel=<><h2>Sound & options</h2><label>Drop zones<select aria-label="Drop zones" value={audioSettings.zones} onChange={e=>configure({zones:+e.target.value})} disabled={state?.phase==='DROPPING'}><option value="5">5</option><option value="10">10</option></select></label>{['music','sounds'].map(k=><label key={k}>{k==='music'?'Music':'Sounds'}<input aria-label={k==='music'?'Music volume':'Sounds volume'} type="range" min="0" max="1" step=".05" value={audioSettings[k]} onChange={e=>configure({[k]:+e.target.value})}/><output>{Math.round(audioSettings[k]*100)}%</output></label>)}<label className="po-check"><input type="checkbox" checked={audioSettings.muted} onChange={e=>configure({muted:e.target.checked})}/>Mute all sounds</label>{preferences.muted&&<p>Classroom Club master mute is on.</p>}<button onClick={async()=>{await enableAudio();audio.current.play('peg');}}>Try / retry sound</button><button onClick={fullscreen}>Full screen</button><button onClick={closeDialog}>Back to game</button></>;
 return <div ref={shell} onClickCapture={e=>{if(e.target.closest('button'))audio.current.play('ui',`ui-${e.timeStamp}`)}} className={`po-shell ${preferences.reduced?'po-reduced':''}`} data-phase={state?.phase||screen} data-audio={audioStatus}>
 {screen!=='game'?<main className="po-setup"><button className="po-exit" onClick={exit}><Label en="← Classroom Club" zh="回遊戲大集合"/></button><Logo/>{screen==='title'?<><p className="po-tagline">BIG BOUNCES. BRILLIANT POINTS.</p><div className="po-title-balls"><PlinkBall skin={0} size={150}/><PlinkBall skin={1} size={120}/><PlinkBall skin={2} size={90}/></div><button className="po-big" onClick={()=>{setScreen('setup');enableAudio();}}><Label en="New game →" zh="開始新遊戲"/></button>{saved&&<button onClick={resume}><Label en={`Resume · Round ${saved.round}/${saved.config.rounds}`} zh={saved.version===1?"接續本機進度（舊局維持原規則，無卡牌）":"接續本機進度"}/></button>}<p className="po-help"><Label en="Ask aloud. Choose a team. Let it drop!" zh="老師口頭問答，選組後放球。"/></p>{import.meta.env.DEV&&<a href="/qa/plinkoh-20260919/sound-check.html" target="_blank" rel="noreferrer">Sound A/B review／音效對照試聽</a>}</>:<><div className="po-config"><label><Label en="Teams" zh="組數"/><input aria-label="Teams" type="range" min="2" max="15" value={cfg.count} onChange={e=>setCfg(settings({...cfg,count:+e.target.value}))}/><output>{cfg.count}</output></label><label><Label en="Rounds" zh="回合數"/><input aria-label="Rounds" type="range" min="1" max="12" value={cfg.rounds} onChange={e=>setCfg(settings({...cfg,rounds:+e.target.value}))}/><output>{cfg.rounds}</output></label><label><Label en="Drop zones" zh="上方放球區"/><select aria-label="Setup drop zones" value={cfg.zones} onChange={e=>setCfg(settings({...cfg,zones:+e.target.value}))}><option value="5">5</option><option value="10">10</option></select></label><div className="po-names">{Array.from({length:cfg.count},(_,i)=><label key={i}><PlinkBall skin={cfg.skins[i]} size={55}/><input aria-label={`Team ${i+1} name`} maxLength="24" value={cfg.names[i]} onChange={e=>{const names=[...cfg.names];names[i]=e.target.value;setCfg({...cfg,names})}}/></label>)}</div></div><div className="po-actions"><button onClick={()=>setScreen('title')}><Label en="Back" zh="返回"/></button><button onClick={()=>{const names=Array.from({length:15},(_,i)=>`Team ${i+1}`);setCfg(c=>({...c,names}))}}><Label en="Reset names" zh="重設隊名"/></button><button onClick={()=>{const skins=[...cfg.skins];for(let i=skins.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[skins[i],skins[j]]=[skins[j],skins[i]];}setCfg(c=>({...c,skins}));}}><Label en="Shuffle balls" zh="隨機球款"/></button><button className="po-big" onClick={()=>saved?request('new','Start a new game and replace saved progress?'):start()}><Label en="Start!" zh="開始遊戲"/></button></div><p className="po-help"><Label en="Each team plays once per round. Choose from 6 power-ups, with 3 uses per team." zh="每組每回合一次，由老師決定順序。6 種卡牌，每組整局可用 3 次。"/></p></>}{notice&&<p role="alert">{notice}</p>}</main>:<div ref={wrap} className="po-viewport"><div className="po-stage" style={{transform:`translate(-50%,-50%) scale(${scale})`}}>
 <svg className="po-background" viewBox="0 0 1470 908" aria-hidden="true"><path d="M-100 110Q150-40 320 100T750 120T1450 30V-50H-100Z" fill="#f8b60b"/><path d="M-80 650Q80 400 290 520T680 440T1150 500T1600 350" fill="none" stroke="#f7b30a" strokeWidth="110"/><path d="M-80 860Q250 780 390 675T800 770" fill="none" stroke="#ffd548" strokeWidth="50"/>{[[85,260],[230,745],[180,360],[69,815]].map(([x,y],i)=><text key={i} x={x} y={y} fill="#ffe865" fontSize="70" transform={`rotate(12 ${x} ${y})`}>✦</text>)}</svg>
 <div className="po-left"><div className="po-small-logo">Plink-oh!</div><button onClick={pause}>Ⅱ Menu</button><button onClick={fullscreen} aria-label="Full screen">⛶</button><div className={`po-left-message ${state.version===2?'po-with-cards':''}`}>{state.phase==='SELECT_TEAM'?<>Who's next?<small>Choose a team →</small></>:current?<><PlinkBall skin={current.skin} size={130}/><strong>{current.name}</strong></>:null}</div>{state.version===2&&current&&<div className="po-card-status"><strong>{activeCard?.name||'No power-up'}</strong><small>{cardsRemaining(state)} uses left</small>{secondBall&&<small>Ball 1: {state.cardTurn.first.total} points<br/>Now drop ball 2!</small>}</div>}{state.phase==='READY'&&<div className="po-drop-controls"><p>Choose a drop zone</p><button className="po-big" disabled={(audioStatus==='loading'||audioStatus==='failed')||blocked} onClick={drop}>{secondBall?'Drop ball 2!':'Drop!'}</button><button onClick={()=>request('skip','Skip this team for this round?')}>Skip team</button></div>}{state.phase==='TURN_DONE'&&<button className="po-big" onClick={()=>{setFrame(null);commit({type:'NEXT'})}}>{state.completed.length===state.teams.length?(state.round===state.config.rounds?'Results!':'Next round →'):'Next team →'}</button>}<button className="po-sound-toggle" onClick={()=>configure({muted:!state.config.muted})}>{state.config.muted||preferences.muted?'Sound off':'Sound on'}</button></div>
 <div ref={boardBox} className="po-board"><svg viewBox={`0 0 ${W} ${H}`} aria-label="Plink-oh board" role="img"><defs><pattern id="po-dots" width="7" height="7" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="#523fe0" opacity=".28"/></pattern><linearGradient id="po-blue" x2=".8" y2="1"><stop stopColor="#67aafb"/><stop offset="1" stopColor="#428cfa"/></linearGradient><linearGradient id="po-beam" x2="0" y2="1"><stop stopColor="#e991ff" stopOpacity=".5"/><stop offset="1" stopColor="#fff" stopOpacity="0"/></linearGradient></defs><rect width={W} height={H} fill="url(#po-blue)"/><rect width={W} height={H} fill="url(#po-dots)"/>{state.phase==='READY'&&<rect x={(state.zone-1)*W/state.config.zones} y="90" width={W/state.config.zones} height="714" fill="url(#po-beam)"/>}<path d="M0 260L49 330 0 400M0 440L49 510 0 580M780 260L731 330 780 400M780 440L731 510 780 580" fill="#8656f5" stroke="#6135d2" strokeWidth="8"/>{board.pegs.filter(p=>!frame?.hit.has(p.id)).map(p=>{const q=pegPosition(p,displayTime);return <g key={p.id}><circle cx={q.x} cy={q.y+2} r={p.r} fill="#402696"/><circle cx={q.x} cy={q.y} r={p.r-1} fill={p.pink?'#fa8dc9':'#8255d5'} stroke="#62329e" strokeWidth="3"/><circle cx={q.x-3} cy={q.y-3} r="3" fill="#e2b2ff" opacity=".7"/></g>})}{board.slots.map((value,i)=>{const sw=W/board.slots.length;return <g key={i}><rect x={i*sw+2} y="824" width={sw-4} height="44" fill={SLOT_COLORS[value/10%7]} stroke="#281044" strokeWidth="5"/><path d={`M${i*sw+2} 824l13 -14h${sw-30}l13 14Z`} fill="#e6feff" opacity=".55" stroke="#45226b" strokeWidth="3"/><text x={(i+.5)*sw} y="858" textAnchor="middle" fontSize="44" fontWeight="1000" fill="white" stroke="#181234" strokeWidth="5" paintOrder="stroke">{value}</text>{after&&state.result?.slotIndex===i&&<ellipse cx={(i+.5)*sw} cy="810" rx={sw*.46} ry="42" fill={SLOT_COLORS[value/10%7]} opacity=".6" className="po-glow"/>}</g>})}{frame?.events.filter(e=>e.points&&e.type!=='landing'&&displayTime-e.time<.8).map(e=><text key={e.id} x={e.x} y={e.y-20-(displayTime-e.time)*60} fill="white" stroke="#49197b" strokeWidth="3" paintOrder="stroke" textAnchor="middle" fontSize="29" opacity={1-(displayTime-e.time)/.8}>+{e.points}</text>)}</svg>
 {state.phase==='READY'&&<><div className="po-zones" role="group" aria-label="Drop zones" onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();commit({type:'ZONE',zone:state.zone+(e.key==='ArrowRight'?1:-1)})}}}>{Array.from({length:state.config.zones},(_,i)=><button key={i} aria-label={`Drop zone ${i+1}`} aria-pressed={state.zone===i+1} onClick={()=>commit({type:'ZONE',zone:i+1})}>{i+1}</button>)}</div><div className="po-ready-ball" style={{left:`${(state.zone-.5)*100/state.config.zones}%`}}><PlinkBall skin={current.skin} size={ballSize}/></div></>}
 {ball&&['DROPPING','REVEAL','TRANSFER','TURN_DONE'].includes(state.phase)&&<div className="po-falling-ball" style={{left:`${ball.x/W*100}%`,top:`${ball.y/H*100}%`,width:ballSize,height:ballSize}}><PlinkBall skin={current?.skin||0} size={ballSize} rotation={ball.angle*180/Math.PI}/></div>}
 {state.phase==='DROPPING'&&<div className="po-live-score">{frame?.collision||0}</div>}{after&&state.result&&<div style={{'--po-flight-x':`${flight.x}px`,'--po-flight-y':`${flight.y}px`}} className={`po-final-score ${state.phase==='TRANSFER'?'po-transfer':''}`}>{state.result.total}<small>{state.result.formula||`${state.result.collision} + ${state.result.slot}`}{state.result.card&&<span> · {cardById(state.result.card)?.name}</span>}{state.result.attempts?.length===2&&<span><br/>Ball 1: {state.result.attempts[0].total} · Ball 2: {state.result.attempts[1].total} · Best: {state.result.total}</span>}</small></div>}
 {state.phase==='ROUND_INTRO'&&<div className="po-intro" onClick={()=>commit({type:'INTRO_DONE'})}><span>Round</span><strong>{state.round}</strong></div>}{state.phase==='TEAM_INTRO'&&<div className="po-intro"><PlinkBall skin={current.skin} size={300} label={current.name}/></div>}{state.phase==='SELECT_TEAM'&&<div className="po-pick-hint">Pick a team <span>→</span></div>}
 </div><aside className="po-scoreboard"><div className="po-score-menu"><button onClick={pause}>☰ Menu</button><button aria-label="Options" onClick={()=>{setPaused(true);setDialog('options')}}>⚙</button></div><div className="po-team-list" aria-label="Team scoreboard">{state.teams.map(t=><div key={t.id} ref={t.id===state.selected?activeRow:null} className={`po-team ${t.id===state.selected?'po-current':''} ${state.completed.includes(t.id)?'po-complete':''}`}><button aria-label={`Choose ${t.name}`} disabled={state.phase!=='SELECT_TEAM'||state.completed.includes(t.id)} onClick={()=>select(t.id)}><span className="po-team-name">{state.history.length>0&&shownScore(t)===topTeam&&<span className="po-crown" aria-label="Leading">♛</span>}{t.name}{state.completed.includes(t.id)&&<i>✓</i>}</span><strong data-testid={`po-score-${t.id}`}>{shownScore(t)}</strong></button><div className="po-adjust"><button aria-label={`Subtract one from ${t.name}`} disabled={!['SELECT_TEAM','READY','TURN_DONE'].includes(state.phase)} onClick={()=>request({type:'ADJUST',id:t.id,delta:-1},`Subtract 1 point from ${t.name}?`)}>−</button><button aria-label={`Add one to ${t.name}`} disabled={!['SELECT_TEAM','READY','TURN_DONE'].includes(state.phase)} onClick={()=>request({type:'ADJUST',id:t.id,delta:1},`Add 1 point to ${t.name}?`)}>+</button></div></div>)}</div><div className="po-round">Round {state.round}/{state.config.rounds}<small>{state.completed.length}/{state.teams.length} played</small></div></aside>
 {state.phase==='CARD_PICK'&&<section className="po-card-picker" role="dialog" aria-modal="true" aria-label="Choose a power-up"><header><span>MAKE YOUR MOVE</span><h1>Choose a power-up!</h1><p>{current.name} · {cardsRemaining(state)} uses left this game</p></header><div className="po-card-grid">{state.cardTurn.offer.map(id=>{const c=cardById(id);return <button key={id} className="po-power-card" style={{'--card-color':c.color}} onClick={()=>commit({type:'CARD_CHOOSE',card:id})} aria-label={`Choose ${c.name}`}><span className="po-card-number">POWER-UP</span><CardArt card={c}/><strong>{c.name}</strong><p>{c.text}</p><small>{c.detail}</small><span className="po-card-use">Choose card →</span></button>})}</div><button onClick={()=>commit({type:'CARD_CHOOSE',card:null})}>No card · Save my uses</button><small>One card per turn. A use is spent only after your score is added.</small></section>}
 {state.phase==='FINISHED'&&<section className={`po-results ${!state.celebrationDone?'po-celebrating':''}`} data-celebrating={!state.celebrationDone}><div className="po-victory-crown" aria-hidden="true">♛</div>{!state.celebrationDone&&<div className="po-confetti" aria-hidden="true">{Array.from({length:40},(_,i)=><i key={i} style={{left:`${(i*37)%100}%`,background:COLORS[i%15],animationDelay:`${i%8*.12}s`}}/>)}</div>}<h1>{leaders(state).length>1?'It’s a tie!':'Winner!'}</h1><div className="po-winners">{leaders(state).map(t=><div key={t.id}><PlinkBall skin={t.skin} size={130} label={t.name}/><strong>{t.score} points</strong></div>)}</div>{!state.celebrationDone&&<button className="po-skip-celebration" onClick={()=>{audio.current.stopWin();commit({type:'CELEBRATION_DONE'})}}>Skip celebration</button>}<ol>{[...state.teams].sort((a,b)=>b.score-a.score).map(t=><li key={t.id}>{t.name}<b>{t.score}</b></li>)}</ol><div className="po-actions"><button onClick={()=>request('restart','Play again? Scores will reset.')}>Play again</button><button onClick={exportLog}>Save score log</button><button onClick={exit}>Classroom Club</button></div></section>}
 </div></div>}
 {screen==='game'&&audioStatus==='loading'&&<div className="po-audio-note" role="status">Preparing sounds…</div>}{screen==='game'&&audioStatus==='failed'&&<div className="po-audio-note" role="alert">Some sounds could not load. <button onClick={enableAudio}>Retry sound</button><button onClick={()=>{configure({muted:true});setAudioStatus('silent')}}>Continue silently</button></div>}{screen==='game'&&notice&&<div className="po-notice" role="alert">{notice}<button aria-label="Dismiss message" onClick={()=>setNotice('')}>×</button></div>}
 {screen==='game'&&(paused||dialog)&&!confirm&&<div className="po-overlay"><section className="po-modal" role="dialog" aria-modal="true" aria-label={dialog==='options'?'Sound and options':'Paused'}>{dialog==='options'?soundPanel:<><h2>Paused</h2><button autoFocus onClick={closeDialog}>Resume</button><button onClick={()=>setDialog('options')}>Options</button><button disabled={state.phase==='DROPPING'} onClick={()=>request('end','End this game and show the results?')}>End game</button><button onClick={()=>request('restart','Restart this game? Scores will reset.')}>Restart game</button><button onClick={exportLog}>Save score log</button><button onClick={()=>request('home','Return to the game menu? Progress stays saved.')}>Game menu</button><button onClick={exit}>Classroom Club</button></>}</section></div>}
 {confirm&&<div className="po-overlay"><section className="po-modal" role="dialog" aria-modal="true" aria-label="Confirm action"><h2>{confirm.label}</h2><button autoFocus onClick={()=>setConfirm(null)}>Cancel</button><button onClick={()=>{if(confirm.action==='new'){setConfirm(null);start()}else accept()}}>Confirm</button></section></div>}
 </div>;
}
