import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,Maximize,Volume2,VolumeX} from 'lucide-react';
import {B} from './Preferences';
import {ABBR,DAYS,SECTORS,TASKS,SPIN_MS,ROLL_MS,CELEBRATE_MS,createGame,advance,randomInt,shuffleTasks,scores,rounds,winners} from './spin-model.mjs';
import {SpinAudio} from './SpinAudio';
import './spin.css';
import './spin-dopamine.css';

const asset=name=>`/spin/${name}.png`;
const taskUrl=id=>`/spin/tasks/${id+1}.gif`;
const faceTransforms=['rotateY(0deg)','rotateY(90deg)','rotateX(90deg)','rotateX(-90deg)','rotateY(-90deg)','rotateY(180deg)'];
const dieAngles={1:[0,0],2:[0,-90],3:[-90,0],4:[90,0],5:[0,90],6:[0,180]};
const calendarCenters=[[61.6,26.7],[76.4,41.5],[76.8,59.6],[61.9,77.1],[38.8,77.1],[25.5,60.1],[23.7,41.7],[38.9,26.7]];
function WheelBoard(){return <><img className="sr-board" src={asset('wheel')} alt="Eight weekday sectors"/>{calendarCenters.map(([left,top],i)=><span key={i} className="sr-wheel-day" style={{left:`${left}%`,top:`${top}%`}}>{ABBR[SECTORS[i]]}</span>)}</>;}

function Dialog({label,children}){const ref=useRef();useEffect(()=>{const previous=document.activeElement;ref.current?.focus();return()=>previous?.isConnected&&previous.focus();},[]);return <div className="sr-overlay"><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={label} className="sr-dialog" onKeyDown={e=>{if(e.key!=='Tab')return;const els=[...e.currentTarget.querySelectorAll('button:not(:disabled),[href],input,select')];if(!els.length){e.preventDefault();return;}const first=els[0],last=els.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first.focus();}}}>{children}</section></div>;}

export default function SpinGame({preferences,onPreferences,onExit}){
 const [count,setCount]=useState(2),[s,setS]=useState(null),[confirm,setConfirm]=useState(null),[retry,setRetry]=useState(0),[celebrating,setCelebrating]=useState(false),[media,setMedia]=useState({}),[mediaAttempt,setMediaAttempt]=useState(0),[artReady,setArtReady]=useState(false),[artError,setArtError]=useState(false),[left,setLeft]=useState(6),[hidden,setHidden]=useState(document.hidden);
 const state=useRef(null),root=useRef(),audio=useRef(null),cache=useRef(new Map()),pending=useRef(new Map()),mounted=useRef(true),bag=useRef(shuffleTasks()),phaseClock=useRef({phase:null,elapsed:0});
 if(!audio.current)audio.current=new SpinAudio();
 const [reading,setReading]=useState(null),[readError,setReadError]=useState(''),readRequest=useRef(0);
 const read=async file=>{const request=++readRequest.current;setReadError('');setReading(file);const ok=await audio.current.read(file,()=>{if(mounted.current&&request===readRequest.current)setReading(null);});if(mounted.current&&request===readRequest.current&&!ok)setReadError('Audio could not play. Please tap the speaker again.');};
 const readButton=(file,name)=><button className={`sr-read ${reading===file?'is-reading':''}`} aria-label={name} title="American English · 0.8×" disabled={preferences.muted||!preferences.scratchVolume} onClick={()=>read(file)}><Volume2 aria-hidden="true"/><span>0.8×</span></button>;
 const act=a=>{const next=advance(state.current,a);state.current=next;setS(next);};
 const start=()=>{audio.current.unlock();bag.current=shuffleTasks();const next=createGame(count);state.current=next;setS(next);};
 useEffect(()=>{audio.current.configure(preferences);},[preferences]);
 useEffect(()=>{mounted.current=true;const onHidden=()=>{setHidden(document.hidden);if(document.hidden)audio.current.stop();};document.addEventListener('visibilitychange',onHidden);return()=>{mounted.current=false;audio.current.dispose();document.removeEventListener('visibilitychange',onHidden);for(const url of cache.current.values())URL.revokeObjectURL(url);for(const controller of pending.current.values())controller.abort();};},[]);
 useEffect(()=>{let alive=true;setArtReady(false);setArtError(false);Promise.all(['wheel','pointer','dice-faces','mascot'].map(name=>new Promise((resolve,reject)=>{const img=new Image();img.onload=resolve;img.onerror=reject;img.src=asset(name);}))).then(()=>alive&&setArtReady(true)).catch(()=>alive&&setArtError(true));return()=>{alive=false;};},[mediaAttempt]);
 async function preload(id){if(cache.current.has(id)||pending.current.has(id))return;const controller=new AbortController();pending.current.set(id,controller);setMedia(m=>({...m,[id]:{status:'loading',progress:0}}));try{const r=await fetch(taskUrl(id),{signal:controller.signal});if(!r.ok)throw new Error('Task unavailable');const total=Number(r.headers.get('content-length')),chunks=[];let received=0;const reader=r.body.getReader();while(true){const {value,done}=await reader.read();if(done)break;chunks.push(value);received+=value.length;if(mounted.current)setMedia(m=>({...m,[id]:{status:'loading',progress:total?Math.min(99,Math.round(received/total*100)):null}}));}const url=URL.createObjectURL(new Blob(chunks,{type:'image/gif'}));if(!mounted.current){URL.revokeObjectURL(url);return;}cache.current.set(id,url);setMedia(m=>({...m,[id]:{status:'ready',url}}));}catch(e){if(mounted.current&&e.name!=='AbortError')setMedia(m=>({...m,[id]:{status:'error'}}));}finally{pending.current.delete(id);}}
 // Prefetch only the next task; never download all eight at game launch.
 useEffect(()=>{const next=s?.bag.length?s.bag[0]:bag.current[0];preload(next);if(s?.phase==='task')preload(s.task);},[s?.phase,s?.task,s?.bag,mediaAttempt]);
 useEffect(()=>{if(!s)return;if(phaseClock.current.phase!==s.phase)phaseClock.current={phase:s.phase,elapsed:0};if(hidden||confirm)return;let timer,tick;const clock=phaseClock.current,started=Date.now(),remaining=duration=>Math.max(0,duration-clock.elapsed);
  if(s.phase==='spinning'){setLeft(Math.ceil(remaining(SPIN_MS)/1000));tick=setInterval(()=>{setLeft(Math.max(1,Math.ceil((remaining(SPIN_MS)-(Date.now()-started))/1000)));audio.current.tick();},450);timer=setTimeout(()=>act({type:'STOP_SPIN'}),remaining(SPIN_MS));}
  if(s.phase==='rolling'){audio.current.good();timer=setTimeout(()=>{act({type:'STOP_ROLL'});audio.current.good();},remaining(ROLL_MS));}
  if(s.phase==='awarded')timer=setTimeout(()=>act({type:'NEXT'}),remaining(1800));
  if(s.phase==='finished'&&remaining(CELEBRATE_MS)>0){setCelebrating(true);if(clock.elapsed===0)audio.current.celebrate();timer=setTimeout(()=>{setCelebrating(false);audio.current.stop();},remaining(CELEBRATE_MS));}
  return()=>{clock.elapsed+=Date.now()-started;clearTimeout(timer);clearInterval(tick);};
 },[s?.phase,hidden,confirm]);
 useEffect(()=>{for(const el of root.current?.querySelectorAll('.sr-pointer,.sr-cube')||[])for(const animation of el.getAnimations()){if(hidden||confirm)animation.pause();else animation.play();}},[hidden,confirm,s?.phase]);
 useEffect(()=>{if(!retry)return;const t=setTimeout(()=>setRetry(0),1700);return()=>clearTimeout(t);},[retry]);
 const tryAgain=()=>{audio.current.unlock();audio.current.retry();setRetry(n=>n+1);};
 const end=()=>{audio.current.stop();setRetry(0);setConfirm(null);act({type:'END'});};
 const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await root.current.requestFullscreen();}catch{}};
 const label=(en,zh)=><B en={en} zh={zh}/>;
 const actionsDisabled=!!confirm||hidden;
 const question=s?`Is it ${DAYS[s.question]} today?`:'';
 const total=s?scores(s):[];
 return <main ref={root} className={`sr-game ${preferences.reduced?'sr-reduced':''}`} data-phase={s?.phase||'setup'}>
 <div className="sr-game-content" inert={confirm||hidden?true:undefined}>
 <header className="sr-topbar"><button className="sr-icon" aria-label="Leave game" onClick={()=>s&&s.phase!=='finished'?setConfirm('exit'):onExit()}><ArrowLeft/></button><div><span className="sr-kicker">HWG5 UNIT ONE · CLASS GAME</span><h1>Spin, ask, answer, do and roll</h1></div><button className="sr-icon" aria-label={preferences.muted?'Unmute':'Mute'} onClick={()=>onPreferences({...preferences,muted:!preferences.muted})}>{preferences.muted?<VolumeX/>:<Volume2/>}</button><button className="sr-icon" aria-label="Fullscreen" onClick={fullscreen}><Maximize/></button></header>
 {!s?<section className="sr-setup"><div className="sr-intro-art"><WheelBoard/><img className="sr-intro-pointer" src={asset('pointer')} alt=""/></div><div className="sr-setup-copy"><span className="sr-kicker">SPIN · SPEAK · MOVE · SCORE</span><h2>{label('A little spin. A big team moment.','轉一轉、說一說、做動作，為小組得分！')}</h2><p>{label('Choose your teams. Everyone gets six turns.','選擇組數，每組最多六回合。')}</p><div className="sr-team-choices" role="group" aria-label="Number of teams">{[2,3,4,5,6].map(n=><button key={n} aria-pressed={count===n} onClick={()=>setCount(n)}>{n}</button>)}</div><p>{label(`${count} teams · Roll 1–6 points each turn`,`${count} 組・每回合擲骰得 1–6 分`)}</p><button className="sr-btn sr-primary" disabled={!artReady} onClick={start}>{label('Let’s play!','開始遊戲')}</button>{!artReady&&<p role="status">{artError?'Artwork could not load.':'Loading artwork…'} {artError&&<button onClick={()=>setMediaAttempt(n=>n+1)}>Retry loading</button>}</p>}</div></section>:<>
 <section className="sr-scoreboard" aria-label="Team scores" style={{'--teams':s.count}}>{total.map((v,t)=><div key={t} data-testid={`spin-team-${t}`} className={`sr-score sr-team-${t} ${t===s.team&&s.phase!=='finished'?'active':''}`}><span>Team {t+1}</span><strong data-testid={`spin-score-${t}`}>{v}</strong><small>{rounds(s,t)} / 6 turns</small></div>)}</section>
 {s.phase!=='finished'&&<div className="sr-progress"><span>TEAM {s.team+1} · TURN {Math.min(6,rounds(s,s.team)+(s.phase==='awarded'?0:1))} OF 6</span><div className="sr-steps">{['Spin','Ask & answer','Do','Roll'].map((step,i)=><span key={step} className={([['ready','spinning'],['question'],['task'],['dice','rolling','awarded']][i].includes(s.phase))?'active':''}>{i+1}. {step}</span>)}</div><button className="sr-end" onClick={()=>setConfirm('end')}>End early</button></div>}
 {['ready','spinning'].includes(s.phase)&&<section className="sr-wheel-stage"><div className="sr-wheel" aria-label="Weekday spinner"><WheelBoard/><img className="sr-pointer" src={asset('pointer')} alt="Rotating arrow" style={{transform:`rotate(${s.angle}deg)`,transition:s.phase==='spinning'&&!preferences.reduced?'transform 6s cubic-bezier(.12,.65,.16,1)':'none'}}/></div><aside className="sr-spin-callout"><span className="sr-kicker">YOUR TURN, TEAM {s.team+1}</span><h2>{s.phase==='spinning'?'Where will it stop?':'Ready to spin?'}</h2><p>{s.phase==='spinning'?`${left}…`:'Spin a day. Ask and answer together.'}</p><button className="sr-btn sr-primary" disabled={s.phase!=='ready'||actionsDisabled} onClick={()=>{audio.current.unlock();act({type:'SPIN',sector:randomInt(8),question:randomInt(7)});}}> {s.phase==='spinning'?'Spinning…':'Spin!'}</button></aside></section>}
 {s.phase==='question'&&<section className="sr-question-stage" role="dialog" aria-modal="false" aria-label="Ask and answer"><span className="sr-kicker">ASK & ANSWER · TEAM {s.team+1}</span><div className="sr-question-grid"><div><div className="sr-speech-row sr-question-row"><h2 data-testid="spin-question">{question}</h2>{readButton(`question-${s.question}`,'Read question')}</div><div className="sr-answer"><div className="sr-speech-row"><p>Yes, it is.</p>{readButton('answer-yes','Read yes answer')}</div><span>or</span><div className="sr-speech-row"><p>No, it isn't.<br/>It's ___.</p>{readButton('answer-no-stem','Read no answer')}</div></div>{readError&&<p className="sr-read-error" role="alert">{readError}</p>}</div><div className="sr-day-card" data-testid="spin-day"><small>TODAY</small><strong>{ABBR[SECTORS[s.sector]]}</strong></div></div><footer className="sr-actions"><button className="sr-btn sr-secondary" onClick={tryAgain}>Try again</button><button className="sr-btn sr-primary" onClick={()=>{setRetry(0);audio.current.stop();audio.current.good();act({type:'RIGHT',bag:bag.current});if(!state.current.bag.length)bag.current=shuffleTasks();}}>Right</button></footer></section>}
 {s.phase==='task'&&<section className="sr-task-stage" aria-label="Action task"><div className="sr-task-copy"><span className="sr-kicker">DO · TEAM {s.team+1}</span><h2>Time to move!</h2><p>Watch. Move. Have fun!</p><span className="sr-task-badge">{TASKS[s.task]}</span></div><div className="sr-task-media">{media[s.task]?.status==='ready'?<div className="sr-task-frame"><img key={s.task} src={media[s.task].url} alt={TASKS[s.task]} data-testid="spin-task" onError={()=>{const url=cache.current.get(s.task);if(url)URL.revokeObjectURL(url);cache.current.delete(s.task);setMedia(m=>({...m,[s.task]:{status:'error'}}));}}/><span className="sr-task-heading">{TASKS[s.task]}</span></div>:<div role="status"><h3>{media[s.task]?.status==='error'?'Could not load this task.':'Loading your task…'}</h3>{media[s.task]?.status==='error'?<button className="sr-btn sr-secondary" onClick={()=>preload(s.task)}>Retry loading</button>:<p>{media[s.task]?.progress==null?'Please wait.':`${media[s.task]?.progress||0}%`}</p>}</div>}</div><footer className="sr-actions"><button className="sr-btn sr-secondary" onClick={tryAgain}>Try again</button><button className="sr-btn sr-primary" disabled={media[s.task]?.status!=='ready'} onClick={()=>{setRetry(0);audio.current.stop();audio.current.good();act({type:'GOOD'});}}>Good job</button></footer></section>}
 {['dice','rolling','awarded'].includes(s.phase)&&<section className="sr-dice-stage"><span className="sr-kicker">ROLL · TEAM {s.team+1}</span><h2>{s.phase==='awarded'?`+${s.die} points!`:s.phase==='rolling'?'Rolling…':'Tap the dice!'}</h2><div className="sr-dice-space"><button className="sr-dice-button" aria-label="Roll dice" disabled={s.phase!=='dice'} onClick={()=>{audio.current.unlock();act({type:'ROLL',value:randomInt(6)+1});}}><span className={`sr-cube ${s.phase==='rolling'?'rolling':''}`} style={s.phase==='awarded'?{transform:`rotateX(${dieAngles[s.die][0]}deg) rotateY(${dieAngles[s.die][1]}deg)`}:undefined}>{faceTransforms.map((transform,i)=><span key={i} className="sr-die-face" style={{transform:`${transform} translateZ(80px)`,backgroundPosition:`${(i%3)*50}% ${i<3?0:100}%`}}/>)}</span></button></div><p role="status">{s.phase==='awarded'?`Team ${s.team+1} · ${total[s.team]} points total`:'One roll. One score. Your team’s moment.'}</p></section>}
 {s.phase==='finished'&&<section className={`sr-results ${celebrating?'celebrating':''}`} data-celebrating={celebrating}><img className="sr-mascot" src={asset('mascot')} alt="Smiling star celebrating with a trophy"/><div><span className="sr-kicker">{s.early?'EARLY FINISH':'SIX TURNS COMPLETE'}</span><h2>{winners(s).length===s.count?'Everyone wins!':`${winners(s).map(t=>`Team ${t+1}`).join(' & ')} ${winners(s).length===1?'wins':'win'}!`}</h2><p>Great speaking. Great moves. Great teamwork!</p><div className="sr-ranking">{total.map((v,t)=><div key={t}><strong>Team {t+1}</strong><span>{v} points</span><small>{rounds(s,t)} / 6 turns</small></div>)}</div><p role="status">{celebrating?'Let’s celebrate!':'Well done, everyone!'}</p><button className="sr-btn sr-primary" disabled={celebrating} onClick={()=>{state.current=null;setS(null);}}>Play again</button><button className="sr-btn sr-secondary" onClick={onExit}>Game collection</button></div></section>}
 </>}
 {!!retry&&<div className="sr-retry" role="status" key={retry}><img src={asset('mascot')} alt=""/><strong>Try again!<small>You can do it!</small></strong></div>}
 </div>
 {confirm&&<Dialog label={confirm==='end'?'End early?':'Leave game?'}><h2>{confirm==='end'?'Finish this game?':'Leave this game?'}</h2><p>{confirm==='end'?'Keep completed rolls. The unfinished turn will not score.':'Your current game scores will be lost.'}</p><div className="sr-actions"><button className="sr-btn sr-secondary" onClick={()=>setConfirm(null)}>Keep playing</button><button className="sr-btn sr-primary" onClick={confirm==='end'?end:onExit}>{confirm==='end'?'Finish now':'Leave game'}</button></div></Dialog>}
 {hidden&&!confirm&&s&&s.phase!=='finished'&&<Dialog label="Game paused"><h2>Game paused</h2><p>Return to this tab to continue.</p></Dialog>}
 </main>;
}
