import React,{useState,useEffect,useRef} from 'react';
import QRCode from 'qrcode';
import {activity,LOCAL_LIVE,readSaved,saveLocal,downloadRecords} from './unscramble-api';
import './unscramble.css';
export const LIVE_GAME={id:'unscramble',name:'Unscramble Live',description:'Build sentences together. Every group, in sync.',url:'#unscramble',order:4,hidden:false,builtin:true};
const uid=()=>crypto.randomUUID();
const date=s=>new Date(s).toLocaleString('zh-TW',{hour12:false});
function Heading({en,zh}){return <><span>{en}</span><small>{zh}</small></>;}
function usePoll(action,payload,student=false){
 const [value,setValue]=useState(null),[error,setError]=useState(''),[online,setOnline]=useState(false);const ref=useRef(payload);ref.current=payload;
 useEffect(()=>{let live=true,timer,active=false,terminal=false;const tick=async()=>{if(active)return;active=true;try{const data=await activity(action,ref.current,student);if(live){setValue(data.room);setError('');setOnline(true);terminal=data.room.phase==='ended';}}catch(e){if(live){setError(e.message);setOnline(false);}}finally{active=false;if(live&&!terminal)timer=setTimeout(tick,1000);}};tick();return()=>{live=false;clearTimeout(timer);};},[action,payload.roomId,payload.groupId,student]);
 return {value,setValue,error,online};
}
function Picture({imageId,credentials,alt='Question picture'}){
 const [url,setUrl]=useState(''),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let alive=true,objectUrl;setUrl('');setError('');if(imageId)activity(credentials?'studentImage':'image',{...credentials,imageId},!!credentials).then(d=>{
  const raw=atob(d.base64),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));objectUrl=URL.createObjectURL(new Blob([bytes],{type:d.type}));if(alive)setUrl(objectUrl);else URL.revokeObjectURL(objectUrl);
 }).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[imageId,credentials?.roomId,retry]);
 return <div className="ul-picture">{url?<img src={url} alt={alt}/>:error?<button onClick={()=>setRetry(x=>x+1)}>Retry picture / 重載圖片</button>:<span>{imageId?'Loading picture…':'Add a picture / 加入圖片'}</span>}</div>;
}
function QR({roomId}){const [src,setSrc]=useState(''),[zoom,setZoom]=useState(false);const link=`${location.origin}/join?room=${roomId}`;useEffect(()=>{QRCode.toDataURL(link,{width:220,margin:2,errorCorrectionLevel:'M'}).then(setSrc);},[link]);return <><div className="ul-qr">{src&&<button className="ul-qr-expand" aria-label="放大加入 QR Code" onClick={()=>setZoom(true)}><img src={src} alt="Scan to join this activity"/></button>}<strong>Scan & join</strong><a href={link} target="_blank" rel="noreferrer">學生加入連結 ↗</a><small>{roomId}</small></div>{zoom&&<div className="ul-modal" role="dialog" aria-label="加入活動 QR Code"><div className="ul-qr-large"><h2>Scan & join</h2><img src={src} alt="Large activity QR Code"/><a href={link} target="_blank" rel="noreferrer">學生加入連結 ↗</a><p>輸入同組所有學號，以空格分隔。</p><button onClick={()=>setZoom(false)}>關閉 QR Code</button></div></div>}</>;}
export default function UnscrambleTeacher({onExit}){
 const [decks,setDecks]=useState([]),[rooms,setRooms]=useState([]),[editor,setEditor]=useState(null),[roomId,setRoomId]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[create,setCreate]=useState(null),[className,setClassName]=useState(''),[maxGroups,setMaxGroups]=useState(8),[filter,setFilter]=useState('');
 async function work(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function refresh(){const [d,r]=await Promise.all([activity('listDecks'),activity('listRooms')]);setDecks(d.decks);setRooms(r.rooms);}
 useEffect(()=>{work(refresh);},[]);
 if(roomId)return <TeacherRoom roomId={roomId} onBack={()=>{setRoomId(null);work(refresh);}}/>;
 if(editor)return <DeckEditor initial={editor} onBack={()=>setEditor(null)} onSaved={()=>{setEditor(null);work(refresh);}}/>;
 return <main className="ul-app"><header className="ul-header"><button onClick={onExit}>← Classroom Club</button><div className="ul-wordmark">UNSCRAMBLE <b>LIVE</b></div><span className="ul-pill">TEACHER</span></header>{LOCAL_LIVE&&<div className="ul-local">本地驗證環境 · Firebase 模擬器 · 尚未發布正式站</div>}
 <section className="ul-hero"><div><span className="ul-eyebrow">ONE CLASS. EVERY VOICE.</span><h1>Words come<br/><em>together.</em></h1><p>句子重組・即時互動<br/>保存題組，換張圖，再開一堂新課。</p></div><div className="ul-hero-tiles" aria-hidden="true"><i>Who's</i><i>she?</i><i>She's</i><i>my</i><i>sister.</i><b>10 GROUPS · LIVE</b></div></section>
 <section className="ul-section"><div className="ul-section-title"><h2><Heading en="Question sets" zh="我的題組"/></h2><div className="ul-actions"><button disabled={busy} onClick={()=>work(async()=>{await activity('seed');await refresh();})}>載入七題家人題組</button><button className="ul-primary" onClick={()=>setEditor({name:'新題組',questions:[{prompt:'',answer:'',imageId:''}]})}>＋ 新增題組</button></div></div>
 {error&&<p role="alert" className="ul-error">{error}</p>}{busy&&<p role="status">儲存／讀取中…</p>}
 <div className="ul-deck-grid">{decks.map(d=><article className="ul-deck" key={d.id}><Picture imageId={d.questions[0].imageId}/><div><span className="ul-eyebrow">{d.questions.length} QUESTIONS</span><h3>{d.name}</h3><p>{date(d.updatedAt)}</p><div className="ul-actions"><button onClick={()=>setEditor(structuredClone(d))}>編輯</button><button onClick={()=>setEditor({...structuredClone(d),id:undefined,version:undefined,name:`${d.name}（副本）`})}>複製題組</button><button className="ul-primary" onClick={()=>{setCreate(d);setClassName('');}}>建立新場次 →</button></div></div></article>)}</div>{!busy&&!decks.length&&<p className="ul-empty">先載入已提供的七題，或建立自己的圖片題組。</p>}</section>
 <section className="ul-section"><div className="ul-section-title"><h2><Heading en="Class records" zh="上課紀錄"/></h2><input aria-label="搜尋活動紀錄" placeholder="搜尋日期、班級或題組" value={filter} onChange={e=>setFilter(e.target.value)}/></div><div className="ul-record-list">{rooms.filter(r=>`${date(r.createdAt)} ${r.className} ${r.title}`.includes(filter)).map(r=><article key={r.id}><div><strong>{r.className} · {r.title}</strong><small>{date(r.createdAt)} · {r.groups} 組 · {r.phase==='ended'?'已結束':'進行中'}</small></div><button onClick={()=>setRoomId(r.id)}>開啟紀錄／場次 →</button></article>)}</div></section>
 {create&&<div className="ul-modal"><form onSubmit={e=>{e.preventDefault();work(async()=>{const d=await activity('createRoom',{deckId:create.id,className,maxGroups});setRoomId(d.room.id);setCreate(null);});}}><h2>建立新場次</h2><p>{create.name} · {create.questions.length} 題</p><label>班級／活動名稱<input autoFocus required aria-label="班級名稱" value={className} onChange={e=>setClassName(e.target.value)}/></label><label>組數<select aria-label="組數" value={maxGroups} onChange={e=>setMaxGroups(Number(e.target.value))}>{[2,3,4,5,6,7,8,9,10].map(n=><option key={n}>{n}</option>)}</select></label>{error&&<p role="alert">{error}</p>}<div className="ul-actions"><button type="button" onClick={()=>setCreate(null)}>取消</button><button className="ul-primary" disabled={busy}>建立場次</button></div></form></div>}
 </main>;
}
function DeckEditor({initial,onBack,onSaved}){
 const [deck,setDeck]=useState(initial),[index,setIndex]=useState(0),[step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');const q=deck.questions[index];
 function update(patch){setDeck(d=>({...d,questions:d.questions.map((x,i)=>i===index?{...x,...patch}:x)}));}
 async function upload(file){if(!file)return;setBusy(true);setError('');try{
  if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('請選 PNG、JPG 或 WebP 圖片。');
  if(file.size>6*1024*1024)throw new Error('請使用小於 6 MB 的圖片。');
  const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});
  const data=await activity('uploadImage',{base64,type:file.type});update({imageId:data.imageId});
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="ul-app"><header className="ul-header"><button onClick={()=>{if(confirm('離開編輯？尚未儲存的修改不會保留。'))onBack();}}>← 返回題組</button><h1>Prepare a set <small>編輯題組</small></h1><button className="ul-primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await activity('saveDeck',{deck});onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}}>儲存題組</button></header>
 <section className="ul-section"><label>題組名稱<input aria-label="題組名稱" value={deck.name} onChange={e=>setDeck({...deck,name:e.target.value})}/></label>{error&&<p role="alert" className="ul-error">{error}</p>}<div className="ul-editor-layout"><nav className="ul-question-nav">{deck.questions.map((x,i)=><button className={index===i?'active':''} key={i} onClick={()=>{setIndex(i);setStep(1);}}>Q{i+1} {x.imageId&&x.prompt&&x.answer?'✓':'○'}</button>)}<button onClick={()=>{setDeck(d=>({...d,questions:[...d.questions,{prompt:'',answer:'',imageId:''}]}));setIndex(deck.questions.length);setStep(1);}}>＋ 加題</button></nav>
 <div className="ul-editor-card"><div className="ul-tabs"><button className={step===1?'active':''} onClick={()=>setStep(1)}>1 · 題目圖片</button><button className={step===2?'active':''} onClick={()=>setStep(2)}>2 · 模式與句子</button></div><h2>Question {index+1}</h2>{step===1?<><Picture imageId={q.imageId}/><label className="ul-upload">上傳／更換圖片<input aria-label="題目圖片" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{upload(e.target.files[0]);e.target.value='';}}/></label><button className="ul-primary" disabled={!q.imageId||busy} onClick={()=>setStep(2)}>Next → 設定句子</button></>:<><div className="ul-mode">✦ 句子重組 · Unscramble</div><p>兩句字卡會混合；縮寫與標點保持完整。</p><label>問句<input aria-label="問句" value={q.prompt} onChange={e=>update({prompt:e.target.value})} placeholder="Who's she?"/></label><label>答句<input aria-label="答句" value={q.answer} onChange={e=>update({answer:e.target.value})} placeholder="She's my sister."/></label><div className="ul-word-preview">{`${q.prompt} ${q.answer}`.split(/\s+/).filter(Boolean).map((w,i)=><span key={i}>{w}</span>)}</div><p className="ul-muted">書寫白板條、口說評分、塗鴉：後續階段</p></>}
 <button className="ul-danger" disabled={deck.questions.length===1||busy} onClick={()=>{if(confirm(`刪除第 ${index+1} 題？`)){setDeck(d=>({...d,questions:d.questions.filter((_,i)=>i!==index)}));setIndex(Math.max(0,index-1));}}}>刪除此題</button></div></div></section></main>;
}
function GroupRecords({room,index}){
 return <div className="ul-groups">{Array.from({length:room.maxGroups},(_,i)=>{const g=Object.values(room.groups).find(g=>g.number===i+1);const attempts=g?.attempts.filter(a=>a.questionIndex===index)||[],last=attempts.at(-1);return <article key={i} className={`ul-group ${last?.correct?'correct':attempts.length>=5?'exhausted':last?'wrong':''}`}><header><strong>GROUP {i+1}</strong><span>{last?.correct?'✓ Correct':attempts.length>=5?'✕ 5 tries':last?'↻ Try again':g?(room.phase==='ended'?'No answer':'Waiting'):'Not joined'}</span></header><small>{g?.members.join(' · ')||'等待加入'}</small><div className="ul-answer">{room.showAnswers?(last?last.lines.map((line,j)=><div key={j}>{line}</div>):'—'):'••• 答案已遮蔽'}</div><footer>{attempts.length} / 5 attempts</footer>{attempts.length>0&&<details><summary>歷次紀錄（{attempts.length}）</summary>{attempts.map(a=><p key={a.id}>#{a.number} {a.correct?'✓':'✕'} {room.showAnswers?a.lines.join(' '):'•••'} <small>{new Date(a.at).toLocaleTimeString('zh-TW',{hour12:false})}</small></p>)}</details>}</article>;})}</div>;
}
function TeacherRoom({roomId,onBack}){
 const {value:room,setValue,error,online}=usePoll('teacherState',{roomId}),[busy,setBusy]=useState(false),[actionError,setActionError]=useState(''),[qr,setQr]=useState(true),[recordIndex,setRecordIndex]=useState(null);
 async function command(action,extra={}){setBusy(true);setActionError('');try{const d=await activity(action,{roomId,revision:room.revision,...extra});setValue(d.room);}catch(e){setActionError(e.message);}finally{setBusy(false);}}
 if(!room)return <main className="ul-app"><button onClick={onBack}>← 返回</button><h1>Opening activity…</h1>{error&&<p role="alert">{error}</p>}</main>;
 const review=recordIndex??(room.phase==='open'?room.questionIndex:room.reviewIndex??room.questionIndex);
 return <main className="ul-app ul-teacher" data-large-class={room.maxGroups>8}><header className="ul-header"><button onClick={onBack}>← 題組與紀錄</button><div><h1>{room.className} · {room.title}</h1><small>{date(room.createdAt)} · {Object.keys(room.groups).length}/{room.maxGroups} groups · <span className={online?'ul-online':'ul-offline'}>{online?'● Connected':'● Reconnecting'}</span></small></div><div className="ul-actions"><button onClick={()=>setQr(!qr)}>{qr?'收起 QR':'顯示 QR'}</button><button onClick={()=>document.documentElement.requestFullscreen?.().catch(()=>{})}>全螢幕</button></div></header>
 {(error||actionError)&&<p className="ul-error" role="alert">{actionError||error}</p>}
 <section className="ul-stage"><div><div className="ul-stage-label"><span className="ul-pill">QUESTION {room.questionIndex+1} / {room.questions.length}</span><strong>{room.phase==='preview'?'LOOK & THINK · 學生已鎖定':room.phase==='open'?'YOUR TURN · 作答開放中':'CLASS COMPLETE · 活動結束'}</strong></div><Picture imageId={room.questions[room.questionIndex].imageId}/></div>{qr&&<QR roomId={room.id}/>}</section>
 <div className="ul-controlbar"><p>{room.phase==='preview'?'先看圖片，準備好了再開放作答。':room.phase==='open'?'切換下一題圖片，將立即鎖定学生並保留本題紀錄。':'本場所有紀錄已保存。'}</p><div className="ul-actions"><button disabled={busy||!online} onClick={()=>command('visibility',{showAnswers:!room.showAnswers})}>{room.showAnswers?'遮蔽答案':'顯示答案'}</button>{room.phase!=='ended'&&<><button disabled={busy||!online} onClick={()=>{if(confirm('結束活動並鎖定所有學生？'))command('end');}}>結束活動</button><button className="ul-primary ul-next" disabled={busy||!online} onClick={()=>{setRecordIndex(null);command('next');}}>{room.phase==='preview'?'Next · 開放作答':room.questionIndex===room.questions.length-1?'Finish · 結束並看紀錄':'Next · 下一題圖片'} →</button></>}</div></div>
 <section className="ul-section"><div className="ul-section-title"><h2>Live answers <small>第 {review+1} 題各組作答紀錄</small></h2><div className="ul-actions"><select aria-label="查看題目紀錄" value={review} onChange={e=>setRecordIndex(Number(e.target.value))}>{room.questions.map((_,i)=><option key={i} value={i}>第 {i+1} 題</option>)}</select><button onClick={()=>downloadRecords(room)}>匯出 CSV</button>{room.phase==='ended'&&<button className="ul-danger" onClick={async()=>{if(confirm('永久刪除此場學號與作答紀錄？題組仍保留。')){try{await activity('deleteRoom',{roomId});onBack();}catch(e){setActionError(e.message);}}}}>刪除此場紀錄</button>}</div></div><GroupRecords room={room} index={review}/></section>
 </main>;
}
let audioContext;
function unlockAudio(){try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();}catch{}}
function successSound(){try{unlockAudio();[523.25,659.25,783.99,1046.5].forEach((f,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime+i*.13;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.12,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+.32);o.connect(g).connect(audioContext.destination);o.start(t);o.stop(t+.34);});}catch{}}
export function UnscrambleStudent(){
 const initialRoom=new URLSearchParams(location.search).get('room')||'';
 const [roomId,setRoomId]=useState(initialRoom),[entry,setEntry]=useState(()=>readSaved(`ul-entry:${initialRoom}`)),[numbers,setNumbers]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 if(entry)return <StudentPlay credentials={entry} onLeave={()=>{if(confirm('離開本組畫面？仍可用這台裝置重新加入。')){setEntry(null);}}}/>;
 async function join(e){e.preventDefault();unlockAudio();setBusy(true);setError('');try{const key=`ul-nonce:${roomId}`;let joinNonce=readSaved(key);if(!joinNonce){joinNonce=uid();if(!saveLocal(key,joinNonce))throw new Error('請允許瀏覽器儲存，才能安全接回原組。');}const data=await activity('join',{roomId,members:numbers,joinNonce},true);const value={roomId,groupId:data.groupId,token:data.token};if(!saveLocal(`ul-entry:${roomId}`,value))throw new Error('無法保存加入資料，請保持此頁並聯絡老師。');setEntry(value);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="ul-app ul-join"><div className="ul-wordmark">UNSCRAMBLE <b>LIVE</b></div><form onSubmit={join}><span className="ul-eyebrow">LET'S BUILD IT TOGETHER</span><h1>Hello,<br/><em>team!</em></h1><p>輸入同組所有學號，以空格分隔。</p>{!initialRoom&&<label>Activity code<input aria-label="活動代碼" required value={roomId} onChange={e=>setRoomId(e.target.value.trim().toUpperCase())}/></label>}<label>Student numbers<textarea aria-label="同組學號" required placeholder="40200 40230 40215" value={numbers} onChange={e=>setNumbers(e.target.value.replace(/[^0-9\s]/g,''))}/></label><p className="ul-muted">每組使用一台平板 · 學號與作答會保存在本場紀錄</p>{error&&<p role="alert" className="ul-error">{error}</p>}<button className="ul-primary" disabled={busy||!numbers.trim()}>{busy?'Joining…':'Join activity →'}</button></form></main>;
}
function StudentPlay({credentials,onLeave}){
 const {value:room,setValue,error,online}=usePoll('studentState',credentials,true),[draft,setDraft]=useState([[],[]]),[selectedRow,setSelectedRow]=useState(0),[pending,setPending]=useState(()=>readSaved(`ul-pending:${credentials.roomId}`)),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[feedback,setFeedback]=useState(null),[muted,setMuted]=useState(false);
 const currentQuestion=useRef(null),submitLock=useRef(false),feedbackTimer=useRef(null);
 useEffect(()=>()=>clearTimeout(feedbackTimer.current),[]);
 useEffect(()=>{if(room&&room.questionIndex!==currentQuestion.current){currentQuestion.current=room.questionIndex;setDraft(readSaved(`ul-draft:${credentials.roomId}:${room.questionIndex}`,[[],[]]));setSelectedRow(0);setFeedback(null);setMessage('');}},[room?.questionIndex]);
 function celebrate(correct){setFeedback(correct?'correct':'wrong');clearTimeout(feedbackTimer.current);feedbackTimer.current=setTimeout(()=>setFeedback(null),correct?2600:1600);if(correct&&!muted)successSound();}
 useEffect(()=>{if(pending&&room){const accepted=room.group.attempts.find(a=>a.id===pending.attemptId);if(accepted){setPending(null);saveLocal(`ul-pending:${credentials.roomId}`,null);setMessage('Saved ✓');celebrate(accepted.correct);}else if(room.questionIndex!==pending.questionIndex||room.phase!=='open'){setPending(null);saveLocal(`ul-pending:${credentials.roomId}`,null);setMessage('This question is locked. An unsent answer was not counted.');}}},[room]);
 if(!room)return <main className="ul-app ul-join"><h1>Joining your team…</h1>{error&&<p role="alert">{error}</p>}<button onClick={onLeave}>Back</button></main>;
 const tokens=room.tokens.map((word,i)=>({id:i,word})),used=draft.flat(),available=tokens.filter(t=>!used.includes(t.id));
 const attempts=room.group.attempts.filter(a=>a.questionIndex===room.questionIndex),correct=attempts.some(a=>a.correct),exhausted=attempts.length>=5;
 const locked=room.phase!=='open'||correct||exhausted||!online||busy||!!pending;
 function arrange(next){if(locked)return;unlockAudio();setDraft(next);saveLocal(`ul-draft:${credentials.roomId}:${room.questionIndex}`,next);setMessage('');}
 function add(i,row=selectedRow){if(locked)return;arrange(draft.map((line,j)=>j===row?[...line.filter(x=>x!==i),i]:line.filter(x=>x!==i)));}
 function remove(i){arrange(draft.map(line=>line.filter(x=>x!==i)));}
 async function submit(retry=false){
  if(submitLock.current||(!retry&&locked))return;unlockAudio();submitLock.current=true;setBusy(true);setMessage('');
  const body=retry?pending:{...credentials,attemptId:uid(),questionIndex:room.questionIndex,revision:room.revision,lines:draft.map(line=>line.map(i=>tokens[i].word))};
  setPending(body);saveLocal(`ul-pending:${credentials.roomId}`,body);
  try{const data=await activity('submit',body,true);setPending(null);saveLocal(`ul-pending:${credentials.roomId}`,null);setValue(data.room);setMessage('Saved ✓');celebrate(data.attempt.correct);}
  catch(e){setMessage(e.message);if(e.status&&e.status<500){setPending(null);saveLocal(`ul-pending:${credentials.roomId}`,null);}}
  finally{setBusy(false);submitLock.current=false;}
 }
 const status=room.phase==='ended'?'Great teamwork!':correct?'You got it!':exhausted?'Wait for your teacher.':room.phase!=='open'?'Look & think.':'Build two sentences.';
 return <main className="ul-app ul-student"><header className="ul-header"><div className="ul-wordmark">GROUP <b>{room.group.number}</b><small>{room.group.members.join(' · ')}</small></div><span className="ul-pill">Q{room.questionIndex+1} / {room.questionCount}</span><button aria-label="Toggle sound" onClick={()=>{unlockAudio();setMuted(!muted);}}>{muted?'Sound off':'Sound on'}</button></header>
 <div className="ul-student-title"><h1>{status}</h1><span className="ul-attempts">{attempts.length} / 5 attempts</span></div>{!online&&<p className="ul-error" role="alert">Reconnecting… Your words are kept.</p>}
 <div className="ul-play-layout"><Picture imageId={room.imageId} credentials={credentials}/><section className="ul-puzzle"><div className="ul-row-selector"><button className={selectedRow===0?'active':''} onClick={()=>setSelectedRow(0)}>1 · Question</button><button className={selectedRow===1?'active':''} onClick={()=>setSelectedRow(1)}>2 · Answer</button></div>
 {[0,1].map(row=><div key={row} className={`ul-sentence ${selectedRow===row?'selected':''}`} data-testid={`sentence-${row}`} onClick={()=>setSelectedRow(row)} onDragOver={e=>{if(!locked)e.preventDefault();}} onDrop={e=>{e.preventDefault();const n=Number(e.dataTransfer.getData('text/plain'));if(Number.isInteger(n)&&tokens[n])add(n,row);}}><span className="ul-line-label">{row===0?'Question':'Answer'}</span>{draft[row].map(i=>tokens[i]&&<button className="ul-word" disabled={locked} key={i} draggable={!locked} onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} onClick={e=>{e.stopPropagation();remove(i);}}>{tokens[i].word}</button>)}{!draft[row].length&&<span className="ul-placeholder">Tap words or drag them here</span>}</div>)}
 <div className="ul-wordbank" data-testid="wordbank" onDragOver={e=>{if(!locked)e.preventDefault();}} onDrop={e=>{e.preventDefault();remove(Number(e.dataTransfer.getData('text/plain')));}}>{available.map(t=><button className="ul-word" disabled={locked} key={t.id} draggable={!locked} onDragStart={e=>e.dataTransfer.setData('text/plain',String(t.id))} onClick={()=>add(t.id)}>{t.word}</button>)}</div>
 <div className="ul-submit-row"><button disabled={locked} onClick={()=>arrange([[],[]])}>Reset</button><button className="ul-primary" disabled={locked||available.length>0||draft.some(x=>!x.length)} onClick={()=>submit()}>Check answer →</button></div>
 {pending&&<button className="ul-primary" disabled={busy||!online} onClick={()=>submit(true)}>Retry saving · no extra attempt</button>}{message&&<p role="status">{message}</p>}{locked&&!pending&&!busy&&<div className="ul-lock-note">{correct?'✓ Correct! Wait for the next question.':exhausted?'Five tries completed. Listen to your teacher.':room.phase==='ended'?'All done. Thank you!':'🔒 Wait for your teacher to press Next.'}</div>}
 </section></div>{feedback&&<div role="status" className={`ul-feedback ${feedback}`} onClick={()=>setFeedback(null)}><span>{feedback==='correct'?'✦':'↻'}</span><strong>{feedback==='correct'?'Correct!':'Try again'}</strong>{feedback==='correct'&&<div className="ul-confetti" aria-hidden="true">✦ ● ✦ ● ✦</div>}</div>}
 </main>;
}
