import React,{useState,useEffect,useRef} from 'react';
import {activity,readSaved,saveLocal} from './vocabulary-api';
import {imageBlob} from './unscramble-images.mjs';
import {paint,capture,WIDTH,HEIGHT} from './vocabulary-drawing.mjs';
import {COLORS} from '../functions/vocabulary-model.mjs';
import {unlockAudio,tone} from './unscramble-audio.mjs';

export function usePicture(imageId,credentials){
 const [url,setUrl]=useState(''),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let alive=true,u;setUrl('');setError('');if(!imageId)return;
  activity(credentials?'studentImage':'image',{...credentials,imageId},!!credentials).then(imageBlob).then(b=>{if(alive){u=URL.createObjectURL(b);setUrl(u);}}).catch(e=>alive&&setError(e.message));return()=>{alive=false;if(u)URL.revokeObjectURL(u);};
 },[imageId,credentials?.roomId,credentials?.groupId,credentials?.token,retry]);
 return {url,error,retry:()=>setRetry(n=>n+1)};
}
export function WordPicture({imageId,options,credentials}){const p=usePicture(imageId,credentials);return <section className="vl-question"><div className="vl-options">{options?.map((word,i)=><span key={i}>{word}</span>)}</div><div className="vl-photo">{p.url?<img src={p.url} alt="Question picture"/>:<button onClick={p.retry}>{p.error?'Retry picture':'Loading picture…'}</button>}</div></section>;}
export function Snapshot({drawing,roomId}){const [url,setUrl]=useState(''),[retry,setRetry]=useState(0),[error,setError]=useState('');useEffect(()=>{let alive=true,u;setError('');setUrl('');if(drawing?.archivePath)activity('answerImage',{roomId,groupId:drawing.groupId,questionIndex:drawing.questionIndex}).then(imageBlob).then(b=>{if(alive){u=URL.createObjectURL(b);setUrl(u);}}).catch(e=>alive&&setError(e.message));return()=>{alive=false;if(u)URL.revokeObjectURL(u);};},[drawing?.archivePath,retry,roomId]);return drawing?.snapshot||url?<img className="vl-snapshot" src={drawing?.snapshot||url} alt="Group final handwriting"/>:error?<button onClick={()=>setRetry(x=>x+1)}>Retry answer image</button>:<div className="vl-empty-board">{drawing?.archivePath?'Loading…':'Waiting for writing'}</div>;}
export function DrawingBoard({value=[],onChange,templateId,credentials,disabled=false,replay=false,onReady}){
 const canvas=useRef(),template=useRef(),live=useRef(value),current=useRef(null),start=useRef(Date.now()),frame=useRef(),[color,setColor]=useState(COLORS[2]),[tool,setTool]=useState('pen'),[width,setWidth]=useState(6),[ready,setReady]=useState(false),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1);
 const p=usePicture(templateId,credentials);live.current=value;
 useEffect(()=>{setReady(false);if(!p.url)return;let alive=true;const img=new Image();img.onload=()=>{if(alive){template.current=img;setReady(true);onReady?.(true);}};img.src=p.url;return()=>{alive=false;onReady?.(false);};},[p.url]);
 useEffect(()=>{if(!playing&&canvas.current)paint(canvas.current.getContext('2d'),value);},[value,playing,ready]);
 useEffect(()=>()=>cancelAnimationFrame(frame.current),[]);
 function point(e){const r=canvas.current.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height)),(current.current?.offset||0)+Date.now()-start.current];}
 function finish(e){if(!current.current||e.pointerId!==current.current.pointer)return;const {stroke,base}=current.current;current.current=null;const next=[...base,{...stroke,points:[...stroke.points]}];live.current=next;onChange?.(next,capture(canvas.current,template.current));}
 function play(){cancelAnimationFrame(frame.current);setPlaying(true);const from=performance.now(),end=value.at(-1)?.points.at(-1)?.[2]||0;const tick=t=>{if(!canvas.current)return;const elapsed=(t-from)*speed;paint(canvas.current.getContext('2d'),value,elapsed);if(elapsed<end)frame.current=requestAnimationFrame(tick);else setPlaying(false);};frame.current=requestAnimationFrame(tick);}
 return <div className="vl-board-wrap">{!replay&&<div className="vl-tools" aria-label="Drawing tools">{COLORS.map((c,i)=><button key={c} className={tool==='pen'&&color===c?'selected':''} aria-label={['Red','Yellow','Blue','Green','Purple'][i]+' pen'} aria-pressed={tool==='pen'&&color===c} style={{'--swatch':c}} disabled={disabled} onClick={()=>{setColor(c);setTool('pen');}}><i/></button>)}<button disabled={disabled} className={tool==='eraser'?'selected':''} onClick={()=>setTool('eraser')}>Eraser</button><label>Size <input type="range" min="3" max="16" value={width} disabled={disabled} onChange={e=>setWidth(+e.target.value)}/></label></div>}
 <div className="vl-board"><img src={p.url||undefined} alt="Writing template" draggable="false"/><canvas ref={canvas} width={WIDTH} height={HEIGHT} aria-label="Writing board" style={{touchAction:'none'}} onPointerDown={e=>{if(disabled||replay||!ready||current.current)return;e.preventDefault();canvas.current.setPointerCapture(e.pointerId);start.current=Date.now();const offset=live.current.at(-1)?.points.at(-1)?.[2]||0;const stroke={tool,color,width:tool==='eraser'?width*3:width,points:[]};current.current={pointer:e.pointerId,stroke,base:live.current,offset,published:0};stroke.points.push(point(e));paint(canvas.current.getContext('2d'),[...current.current.base,stroke]);}} onPointerMove={e=>{if(!current.current||current.current.pointer!==e.pointerId)return;const s=current.current.stroke;for(const event of e.nativeEvent.getCoalescedEvents?.()||[e]){const next=point(event),last=s.points.at(-1);if(Math.hypot(next[0]-last[0],next[1]-last[1])>.001)s.points.push(next);}const next=[...current.current.base,{...s,points:[...s.points]}];paint(canvas.current.getContext('2d'),next);if(Date.now()-current.current.published>=250){current.current.published=Date.now();onChange?.(next,capture(canvas.current,template.current));}}} onPointerUp={finish} onPointerCancel={finish} onLostPointerCapture={finish}/>{!ready&&<div className="vl-loading"><button onClick={p.retry}>{p.error?'Retry template':'Loading template…'}</button></div>}</div>
 {replay&&<div className="ul-actions"><button onClick={play} disabled={playing||!ready||!value.length}>▶ Play handwriting</button><button onClick={()=>{cancelAnimationFrame(frame.current);setPlaying(false);}}>■ Stop</button><label>Speed <select value={speed} onChange={e=>setSpeed(+e.target.value)}><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></label></div>}
 </div>;
}
export function RewardArt({score}){return <svg viewBox="0 0 240 240" className={`vl-reward-art vl-art-${score}`} role="img" aria-label={`${score} points`}><defs><linearGradient id={`gold-${score}`} x2="0" y2="1"><stop stopColor="#fff3a0"/><stop offset=".5" stopColor="#ffca3b"/><stop offset="1" stopColor="#f58231"/></linearGradient></defs><circle cx="120" cy="120" r="98" fill={['','#fff0b9','#f9d7ef','#d8f4fc','#e7ddff','#fff0a1'][score]}/><g fill={`url(#gold-${score})`} stroke="#462954" strokeWidth="5" strokeLinejoin="round">{score<=2?<>{[...(score===1?[120]:[75,163])].map((x,i)=><path key={i} transform={`translate(${x} ${score===1?110:100+i*27}) scale(${score===1?1.1:.75})`} d="M0-65 19-21 66-16 31 16 40 64 0 40-40 64-31 16-66-16-19-21Z"/>)}</>:score===3?<><path d="M75 33H104L133 97 104 116Z" fill="#ea4472"/><path d="M137 33H169L132 116 103 97Z" fill="#62bceb"/><circle cx="121" cy="139" r="57"/><circle cx="121" cy="139" r="42" fill="none"/><path d="m121 107 10 20 22 3-16 17 4 22-20-10-20 10 4-22-16-17 22-3Z"/></>:score===4?<><path d="M80 62H46v42q0 40 54 42M160 62h34v42q0 40-54 42" fill="none" strokeWidth="12"/><path d="M76 47h88v59q0 42-44 51-44-9-44-51Z"/><path d="M110 156h20v31h31v19H79v-19h31Z"/><path d="m120 69 8 17 19 2-14 13 4 18-17-9-17 9 4-18-14-13 19-2Z" fill="#fff8c4"/></>:<><path d="m52 84 39 25 29-52 30 52 38-25-14 94H66Z"/><path d="M66 178h108v22H66Z"/><path d="m120 114 15 20-15 20-15-20Z" fill="#da4596"/><circle cx="52" cy="78" r="9"/><circle cx="120" cy="48" r="9"/><circle cx="188" cy="78" r="9"/></>}</g><g fill="#ef51a7"><path d="m30 37 4 8 9 1-7 6 2 9-8-5-8 5 2-9-7-6 9-1Z"/><path d="m206 173 4 8 9 1-7 6 2 9-8-5-8 5 2-9-7-6 9-1Z"/></g></svg>;}
function useRewardSound(score,active,settings,seconds){useEffect(()=>{if(!active||settings.quiet||!settings.effectsVolume)return;let stop=false,nodes=[];unlockAudio().then(ctx=>{if(!ctx||stop)return;const gain=ctx.createGain();gain.gain.value=settings.effectsVolume*.45;gain.connect(ctx.destination);nodes.push(gain);const count=seconds===10?40:score+2;for(let i=0;i<count;i++)nodes.push(tone(ctx,gain,[60,64,67,72,76,79][(i+score)%6]+(score===5?12:0),ctx.currentTime+i*(seconds===10?.25:.15),.24,.13,score%2?'triangle':'sine'));});return()=>{stop=true;nodes.forEach(n=>{try{n.stop?.();n.disconnect();}catch{}});};},[score,active,settings.quiet,settings.effectsVolume,seconds]);}
export function Rewards({score,eventId,sound}){const [active,setActive]=useState(false);useEffect(()=>{if(!score||!eventId)return;const key=`vl-seen:${eventId}`;if(readSaved(key))return;saveLocal(key,true);setActive(true);const t=setTimeout(()=>setActive(false),3200);return()=>clearTimeout(t);},[eventId,score]);useRewardSound(score,active,sound.settings,3.2);return active?<div className={`vl-reward vl-score-${score}`} role="status"><RewardArt score={score}/><strong>+{score} {score===1?'point':'points'}!</strong><span>{['','Nice effort!','Keep going!','Great writing!','Wonderful!','Superstar!'][score]}</span></div>:null;}
export function Finale({room,sound}){const [started]=useState(()=>{const key=`vl-finale:${room.id}:${room.endedAt}`,saved=readSaved(key);if(saved)return saved;const t=Date.now()-Date.parse(room.endedAt)<15000?Date.now():Date.parse(room.endedAt);saveLocal(key,t);return t;}),[remaining,setRemaining]=useState(()=>Math.max(0,10000-(Date.now()-started))),active=remaining>0;useEffect(()=>{const t=setInterval(()=>setRemaining(Math.max(0,10000-(Date.now()-started))),100);return()=>clearInterval(t);},[started]);useRewardSound(5,active,sound.settings,10);const scores=(room.standings||Object.values(room.groups||{}).map(g=>({number:g.number,total:Object.values(g.scores||{}).reduce((n,s)=>n+s.score,0)}))).sort((a,b)=>b.total-a.total||a.number-b.number),max=scores[0]?.total;return <section className={`vl-finale ${active?'celebrating':''}`} aria-label="Final scores"><h1>Wonderful teamwork!</h1>{active&&<div className="vl-confetti" aria-hidden="true">{Array.from({length:36},(_,i)=><i key={i} style={{left:`${i*2.8}%`,animationDelay:`-${i%7*.4}s`,background:['#f44895','#ffe151','#5edacc','#8a6be8'][i%4]}}/>)}</div>}<RewardArt score={5}/><div className="vl-final-grid">{scores.map(s=><article key={s.number} className={s.total===max?'winner':''}><span>{s.total===max?'♛ ':''}GROUP {s.number}</span><strong>{s.total}</strong><small>{s.total===max?'CHAMPION':'POINTS'}</small></article>)}</div><p>{active?`Celebrating · ${Math.ceil(remaining/1000)}s`:'Every word is progress.'}</p></section>;}
