import React,{useState,useEffect,useRef} from 'react';
import {activity,readSaved,saveLocal,removeLocal,downloadRecords} from './vocabulary-api';
import {preparePicture,pictureUploadPayload,imageSize} from './unscramble-images.mjs';
import {DrawingBoard,Snapshot,WordPicture,Rewards,Finale,usePicture} from './VocabularyBoard';
import {totalScore} from '../functions/vocabulary-model.mjs';
import {SoundControls,useClassSound} from './UnscrambleSound';
import {QR} from './VocabularyLive';
const fresh=()=>({imageId:'',options:['','',''],correctIndex:0,templateId:'default-whiteboard',templateOverride:false});
function Picture({id}){const p=usePicture(id);return p.url?<img className="vl-editor-image" src={p.url} alt="Template preview"/>:<button onClick={p.retry}>Load picture</button>;}
export function DeckEditor({initial,onBack,onSaved}){
 const [deck,setDeck]=useState({...initial,templateId:initial.templateId||'default-whiteboard'}),[index,setIndex]=useState(0),[templates,setTemplates]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[stats,setStats]=useState('');const q=deck.questions[index];
 useEffect(()=>{activity('listTemplates').then(x=>setTemplates(x.templates)).catch(e=>setError(e.message));},[]);
 function update(p){setDeck(d=>({...d,questions:d.questions.map((x,i)=>i===index?{...x,...p}:x)}));}
 async function upload(file,template=false){if(!file)return;setBusy(true);setError('');try{const prepared=await preparePicture(file);const data=await activity(template?'saveTemplate':'uploadImage',{...await pictureUploadPayload(prepared),...(template?{name:file.name}:{})});if(template){setTemplates((await activity('listTemplates')).templates);update({templateId:data.imageId,templateOverride:true});}else update({imageId:data.imageId});setStats(`${imageSize(prepared.stats.originalBytes)} → ${imageSize(prepared.full.size)}`);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="ul-app vl-app"><header className="ul-header"><button disabled={busy} onClick={()=>{if(confirm('離開編輯？未儲存的修改不會保留。'))onBack();}}>← 返回題組</button><h1>Prepare a set <small>編輯單字題組</small></h1><button className="ul-primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await activity('saveDeck',{deck});onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}}>儲存題組</button></header>
 <section className="ul-section"><label>題組名稱<input aria-label="題組名稱" value={deck.name} onChange={e=>setDeck({...deck,name:e.target.value})}/></label><label>題組預設模板<select value={deck.templateId} onChange={e=>{const id=e.target.value;setDeck(d=>({...d,templateId:id,questions:d.questions.map(q=>q.templateOverride?q:{...q,templateId:id})}));}}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{error&&<p role="alert" className="ul-error">{error}</p>}<div className="ul-editor-layout"><nav className="ul-question-nav">{deck.questions.map((q,i)=><button disabled={busy} key={i} className={i===index?'active':''} onClick={()=>setIndex(i)}>Q{i+1} {q.options[q.correctIndex]||'○'}</button>)}<button disabled={busy||deck.questions.length>=50} onClick={()=>{setDeck(d=>({...d,questions:[...d.questions,{...fresh(),templateId:d.templateId}]}));setIndex(deck.questions.length);}}>＋ 加題</button></nav><div className="ul-editor-card"><h2>Question {index+1}</h2><WordPicture imageId={q.imageId} options={q.options}/><label>上傳／更換題目圖片<input aria-label="題目圖片" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>upload(e.target.files[0])}/></label><p role="status">{stats}</p><div className="vl-option-editor">{q.options.map((w,i)=><label key={i}>選項 {i+1}<input aria-label={`選項 ${i+1}`} value={w} maxLength={40} onChange={e=>update({options:q.options.map((x,j)=>j===i?e.target.value:x)})}/><button type="button" aria-pressed={q.correctIndex===i} className={q.correctIndex===i?'active':''} onClick={()=>update({correctIndex:i})}>{q.correctIndex===i?'✓ 正確單字':'設為正確'}</button></label>)}</div><label>本題模板<select value={q.templateOverride?q.templateId:''} onChange={e=>update({templateOverride:!!e.target.value,templateId:e.target.value||deck.templateId})}><option value="">沿用題組預設</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><Picture id={q.templateId}/><label>新增私人模板<input aria-label="新增模板" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>upload(e.target.files[0],true)}/></label><button className="ul-danger" disabled={busy||deck.questions.length<2} onClick={()=>{if(confirm('移除此題？')){setDeck(d=>({...d,questions:d.questions.filter((_,i)=>i!==index)}));setIndex(Math.max(0,index-1));}}}>刪除此題</button></div></div></section></main>;
}
function useRoom(action,payload,student=false){const [room,setRoom]=useState(null),[error,setError]=useState(''),[online,setOnline]=useState(false),latest=useRef(payload);latest.current=payload;useEffect(()=>{let alive=true,timer,done=false;const tick=async()=>{try{const r=await activity(action,latest.current,student);if(alive){setRoom(r.room);setError('');setOnline(true);done=r.room.phase==='ended';}}catch(e){if(alive){setError(e);setOnline(false);done=['ROOM_REMOVED','LOGIN_REVOKED','LOGIN_INVALID'].includes(e.code);}}finally{if(alive&&!done)timer=setTimeout(tick,1000);}};tick();return()=>{alive=false;clearTimeout(timer);};},[action,payload.roomId,payload.reviewIndex,payload.token]);return {room,setRoom,error,online};}
export function TeacherRoom({roomId,onBack}){
 const [review,setReview]=useState(null),[focus,setFocus]=useState(null),[replay,setReplay]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[qr,setQr]=useState(false),[reduced,setReduced]=useState(()=>readSaved('vl-reduced',false));
 const {room,setRoom,error,online}=useRoom('teacherState',{roomId,...(review!==null?{reviewIndex:review}:{})});const sound=useClassSound('teacher',room?.phase!=='ended'&&room?.phase!=='closing');
 async function act(action,extra={}){setBusy(true);setMessage('');try{const x=await activity(action,{roomId,revision:room.revision,...extra});if(x.room)setRoom({...room,...x.room,drawings:x.room.drawings||room.drawings});return true;}catch(e){setMessage(e.message);return false;}finally{setBusy(false);}}
 if(!room)return <main className="ul-app"><button onClick={onBack}>← 返回</button><h1>Opening activity…</h1>{error&&<p role="alert">{error.message}</p>}</main>;
 const i=review??room.questionIndex,q=room.questions[i],drawings=room.drawings||[],gfocus=focus?room.groups[focus]:null,drawing=drawings.find(d=>d.groupId===focus),ended=room.phase==='ended';
 async function move(action){if(room.phase==='open'){const incomplete=Object.values(room.groups).filter(g=>!g.scores?.[room.questionIndex]);if(incomplete.length&&!confirm(`尚未完成：${incomplete.map(g=>'GROUP '+g.number).join('、')}。繼續將記 0 分並鎖定本題，確定？`))return;}if(action==='end'&&!confirm('提早結束並顯示總分與 10 秒慶祝？'))return;setFocus(null);setReplay(null);setReview(null);await act(action,{confirmIncomplete:true});}
 async function inspectReplay(g){setBusy(true);try{const x=await activity('drawing',{roomId,groupId:g.id,questionIndex:i});setReplay(x.drawing);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const card=(g,n)=>{const d=drawings.find(d=>d.groupId===g?.id),s=g?.scores?.[i];return <article className={`vl-group ${s?'scored':''}`} key={n}><button className="vl-group-open" onClick={()=>{if(g){setFocus(g.id);setReplay(null);}}}><header><strong>GROUP {n}</strong><span>{s?`${s.score} pts`:d?.status==='submitted'?'Submitted':d?'Writing…':'Waiting'}</span></header><small>{g?.members.join(' · ')||'尚未加入'}</small>{room.showAnswers?<Snapshot drawing={d} roomId={roomId}/>:<div className="vl-empty-board">Answer hidden</div>}<footer><span>Total {totalScore(g)}</span><span>{s?.status==='ungraded'?'未評分':s?.status==='unanswered'?'未作答':g?'放大／批改 ↗':''}</span></footer></button>{g&&!ended&&<button className="vl-release" disabled={busy||g.loginStatus==='released'} onClick={()=>{if(confirm(`解除 GROUP ${n} 登入？相同學號可接回原組。`))act('releaseGroupLogin',{groupId:g.id,loginVersion:g.loginVersion,releaseRequestId:crypto.randomUUID()});}}>{g.loginStatus==='released'?'等待重新加入':'解除登入'}</button>}</article>;};
 return <main className={`ul-app vl-app vl-teacher ${reduced?'vl-reduced':''}`}><header className="ul-header"><button onClick={onBack}>← 題組與紀錄</button><div><h1>{room.className} · {room.title}</h1><small>{Object.keys(room.groups).length}/{room.maxGroups} groups · {online?'● Connected':'● Reconnecting'}</small></div><div className="ul-actions"><SoundControls sound={sound} teacher/><button onClick={()=>setQr(!qr)}>QR</button><button onClick={()=>document.documentElement.requestFullscreen?.()}>全螢幕</button><button aria-pressed={reduced} onClick={()=>{setReduced(!reduced);saveLocal('vl-reduced',!reduced);}}>減少動態</button></div></header>{(message||error)&&<p role="alert" className="ul-error">{message||error.message}</p>}
 {ended&&<Finale room={room} sound={sound}/>}
 <div className="vl-live-layout"><section className="vl-stage"><div className="ul-stage-label"><span className="ul-pill">QUESTION {room.questionIndex+1} / {room.questions.length}</span><strong>{room.phase==='open'?'YOUR TURN':ended?'CLASS COMPLETE':room.phase==='closing'?'SAVING ANSWERS':'LOOK & THINK'}</strong></div><WordPicture imageId={room.questions[room.questionIndex].imageId} options={room.questions[room.questionIndex].options}/>{qr&&<QR roomId={roomId}/>}<div className="ul-controlbar"><button disabled={busy} onClick={()=>act('visibility',{showAnswers:!room.showAnswers})}>{room.showAnswers?'遮蔽答案':'顯示答案'}</button>{!ended&&<><button disabled={busy||!online} onClick={()=>move('end')}>{room.phase==='closing'?'重試保存並結束':'提早結束'}</button><button className="ul-primary ul-next" disabled={busy||!online||room.phase==='closing'} onClick={()=>move('next')}>{room.phase==='preview'?'Next · 開放作答':room.questionIndex===room.questions.length-1?'Finish · 結束':'Next · 下一題'} →</button></>}</div></section>
 <section className="vl-answers"><div className="ul-section-title"><h2>Live answers</h2><select aria-label="查看題目紀錄" value={i} onChange={e=>{setReview(+e.target.value);setFocus(null);setReplay(null);}}>{room.questions.map((_,n)=><option key={n} value={n}>第 {n+1} 題</option>)}</select><button onClick={()=>downloadRecords(room)}>CSV</button></div><div className="vl-group-grid" data-count={room.maxGroups}>{Array.from({length:room.maxGroups},(_,n)=>card(Object.values(room.groups).find(g=>g.number===n+1),n+1))}</div></section></div>
 {gfocus&&<div className="ul-modal" role="dialog" aria-label="組別作答"><section className="vl-review"><header><h2>GROUP {gfocus.number} · Q{i+1}</h2><button onClick={()=>{setFocus(null);setReplay(null);}}>Close ✕</button></header><p>{gfocus.members.join(' · ')} · 正確單字：{q.options[q.correctIndex]}</p>{room.showAnswers?(replay?<DrawingBoard templateId={q.templateId} value={replay.strokes||[]} disabled replay/>:<Snapshot drawing={drawing} roomId={roomId}/>):<p>答案已遮蔽</p>}
 {!ended&&drawing?.status!=='draft'&&drawing&&<button disabled={busy||!room.showAnswers} onClick={()=>inspectReplay(gfocus)}>▶ 載入筆跡重播</button>}
 {drawing?.status==='submitted'&&room.phase==='open'&&i===room.questionIndex&&!gfocus.scores?.[i]&&<div className="vl-grading">{[1,2,3,4,5].map(score=><button key={score} disabled={busy} onClick={()=>act('score',{groupId:focus,questionIndex:i,score,requestId:crypto.randomUUID()})}>{score} 分</button>)}<button disabled={busy} onClick={async()=>{if(await act('return',{groupId:focus,questionIndex:i,requestId:crypto.randomUUID()}))setReplay(null);}}>退回重寫</button></div>}{gfocus.scores?.[i]&&<p className="vl-grade-saved">Saved · {gfocus.scores[i].score} points</p>}</section></div>}
 </main>;
}
export function StudentPlay({credentials,onLeave,onInvalid}){
 const {room,setRoom,error,online}=useRoom('studentState',credentials,true),sound=useClassSound('student',room?.phase==='open');const invalid=useRef(false);
 useEffect(()=>{if(error&&['LOGIN_REVOKED','LOGIN_INVALID','ROOM_REMOVED'].includes(error.code)&&!invalid.current){invalid.current=true;onInvalid({code:error.code,credentials,members:credentials.members});}},[error]);
 if(!room)return <main className="ul-app"><h1>Joining your team…</h1>{error&&<p>{error.message}</p>}<button onClick={onLeave}>Back</button></main>;
 return <main className="ul-app vl-app vl-student"><header className="ul-header"><div className="ul-wordmark">GROUP <b>{room.group.number}</b><small>{room.group.members.join(' · ')}</small></div><span className="ul-pill">Q{room.questionIndex+1} / {room.questionCount} · Total {totalScore(room.group)}</span><SoundControls sound={sound}/></header>{!online&&<p role="alert" className="ul-error">Reconnecting… Your writing is kept.</p>}{room.phase==='ended'?<Finale room={room} sound={sound}/>:<StudentWriter key={`${room.questionIndex}:${room.drawing?.epoch||0}`} room={room} credentials={credentials} online={online} sound={sound} onRoom={setRoom}/>}</main>;
}
function StudentWriter({room,credentials,online,sound,onRoom}){
 const key=`vl-draft:${room.id}:${credentials.groupId}:${room.questionIndex}`,epoch=room.drawing?.epoch||0;
 const [value,setValue]=useState([]),[hydrated,setHydrated]=useState(false),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[status,setStatus]=useState('');
 const current=useRef(null),flight=useRef(null),alive=useRef(true),roomRef=useRef(room);roomRef.current=room;
 useEffect(()=>{alive.current=true;let live=true;activity('studentDrawing',{...credentials,questionIndex:room.questionIndex},true).then(x=>{if(!live)return;const saved=readSaved(key),remote=x.drawing;const best=saved?.epoch===epoch&&(saved.seq||0)>=(remote?.seq||0)?saved:remote;current.current={epoch,seq:best?.seq||0,strokes:best?.strokes||[],snapshot:best?.snapshot||'',dirty:!!(saved===best),submitId:best?.submitId||null};setValue(current.current.strokes);setStatus(remote?.status||'draft');setHydrated(true);}).catch(e=>setMessage(e.message));return()=>{live=false;alive.current=false;};},[]);
 useEffect(()=>{if(room.drawing?.status)setStatus(room.drawing.status);},[room.drawing?.status]);
 const score=room.group.scores?.[room.questionIndex],locked=room.phase!=='open'||!!score||status==='submitted'||status==='scored'||busy||!hydrated;
 async function sync(submit=false){if(!current.current)return;if(flight.current){await flight.current;if(!submit)return;}const draft=current.current,r=roomRef.current;if(r.phase!=='open'||r.group.scores?.[r.questionIndex])return;
  if(!submit&&!draft.dirty)return;if(submit){setBusy(true);draft.submitId??=crypto.randomUUID();saveLocal(key,draft);}
  const body={...credentials,questionIndex:r.questionIndex,epoch:draft.epoch,seq:draft.seq,strokes:draft.strokes,snapshot:draft.snapshot,...(submit?{submitId:draft.submitId}:{})};
  const task=activity(submit?'submit':'draw',body,true).then(x=>{if(!alive.current)return;if(current.current.seq===body.seq)current.current.dirty=false;setMessage(submit?'Submitted. Wait for your teacher.':'Saved ✓');if(submit){setStatus('submitted');onRoom({...x.room,drawing:x.drawing});}saveLocal(key,current.current);}).catch(e=>{if(alive.current)setMessage(e.message);}).finally(()=>{flight.current=null;if(alive.current)setBusy(false);});flight.current=task;await task;
 }
 const syncRef=useRef(sync);syncRef.current=sync;useEffect(()=>{const t=setInterval(()=>{if(online&&!locked)syncRef.current(false);},1000);return()=>clearInterval(t);},[online,locked]);
 function change(strokes,snapshot){const next={...current.current,seq:current.current.seq+1,strokes,snapshot,dirty:true,submitId:null};current.current=next;setValue(strokes);if(!saveLocal(key,next))setMessage('Storage is full. Keep this page open and submit.');else setMessage('Saving…');}
 return <><div className="vl-student-heading"><h1>{score?`${score.score} points!`:status==='submitted'?'Great! Wait for your teacher.':room.phase==='open'?'Look. Choose. Write.':'Look & think.'}</h1><span>{room.phase==='closing'?'Saving final answers…':status==='draft'&&epoch>0?'Try writing again.':''}</span></div><div className="vl-student-layout"><WordPicture imageId={room.imageId} options={room.options} credentials={credentials}/><section><DrawingBoard value={value} onChange={change} templateId={room.templateId} credentials={credentials} disabled={locked} onReady={setReady}/><div className="vl-submit"><span role="status">{message||(!hydrated?'Loading your writing…':locked?'Wait for your teacher.':'Choose a pen and write.')}</span><button className="ul-primary" disabled={locked||!online||!ready||!value.some(x=>x.tool==='pen')} onClick={()=>sync(true)}>{busy?'Saving…':'Submit →'}</button></div></section></div>{score?.score>0&&<Rewards score={score.score} eventId={score.requestId} sound={sound}/>}</>;
}
