"""Generate the four exact HWG5 analog-clock question images.

The clock hands are computed from the requested time instead of generated by an
image model, so the educational stimulus stays deterministic and testable.
"""

from __future__ import annotations

import math
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


WIDTH = 1536
HEIGHT = 864
OUTPUT_DIR = Path(__file__).resolve().parents[1] / "images" / "hwg5-sentence-review"

CLOCKS = {
    "HWG5-SR-001.png": (5, 55),
    "HWG5-SR-002.png": (3, 15),
    "HWG5-SR-009.png": (5, 45),
    "HWG5-SR-010.png": (11, 0),
}


def load_font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = (
        Path("C:/Windows/Fonts/arialbd.ttf"),
        Path("C:/Windows/Fonts/Arial.ttf"),
    )
    for path in candidates:
        if path.exists():
            return ImageFont.truetype(str(path), size=size)
    return ImageFont.load_default()


def endpoint(center: tuple[int, int], length: float, angle_degrees: float) -> tuple[int, int]:
    angle = math.radians(angle_degrees)
    return (
        round(center[0] + length * math.sin(angle)),
        round(center[1] - length * math.cos(angle)),
    )


def draw_clock(hour: int, minute: int, destination: Path) -> None:
    image = Image.new("RGB", (WIDTH, HEIGHT), "#fff7df")
    draw = ImageDraw.Draw(image)

    # A simple pastel background keeps the clock legible on a projected screen.
    for y in range(HEIGHT):
        ratio = y / max(1, HEIGHT - 1)
        start = (227, 249, 255)
        end = (255, 239, 214)
        color = tuple(round(a + (b - a) * ratio) for a, b in zip(start, end))
        draw.line((0, y, WIDTH, y), fill=color)

    center = (WIDTH // 2, HEIGHT // 2)
    radius = 335
    shadow_box = (
        center[0] - radius + 18,
        center[1] - radius + 24,
        center[0] + radius + 18,
        center[1] + radius + 24,
    )
    draw.ellipse(shadow_box, fill="#b8cdd1")
    face_box = (
        center[0] - radius,
        center[1] - radius,
        center[0] + radius,
        center[1] + radius,
    )
    draw.ellipse(face_box, fill="#fffdf7", outline="#16a6b6", width=24)

    for index in range(60):
        angle = index * 6
        outer = endpoint(center, radius - 20, angle)
        inner_length = radius - (55 if index % 5 == 0 else 38)
        inner = endpoint(center, inner_length, angle)
        draw.line((inner, outer), fill="#22304a", width=8 if index % 5 == 0 else 3)

    font = load_font(58)
    for number in range(1, 13):
        angle = number * 30
        position = endpoint(center, radius - 105, angle)
        label = str(number)
        bounds = draw.textbbox((0, 0), label, font=font)
        draw.text(
            (position[0] - (bounds[2] - bounds[0]) / 2, position[1] - (bounds[3] - bounds[1]) / 2 - 4),
            label,
            font=font,
            fill="#17233d",
        )

    minute_angle = minute * 6
    hour_angle = (hour % 12) * 30 + minute * 0.5
    hour_end = endpoint(center, radius * 0.53, hour_angle)
    minute_end = endpoint(center, radius * 0.76, minute_angle)

    # Draw the shorter hour hand first and the long minute hand second.
    draw.line((center, hour_end), fill="#17233d", width=30)
    draw.line((center, minute_end), fill="#8b35d1", width=20)
    draw.ellipse(
        (center[0] - 24, center[1] - 24, center[0] + 24, center[1] + 24),
        fill="#ff477e",
        outline="#17233d",
        width=7,
    )

    destination.parent.mkdir(parents=True, exist_ok=True)
    image.save(destination, format="PNG", optimize=True)


def main() -> None:
    for filename, (hour, minute) in CLOCKS.items():
        draw_clock(hour, minute, OUTPUT_DIR / filename)
        print(f"generated {filename}: {hour:02d}:{minute:02d}")


if __name__ == "__main__":
    main()
