import {mkdirSync} from 'node:fs';
mkdirSync('tests/artifacts',{recursive:true});
import {chromium} from 'playwright';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8').replace(/const configured=[^;]+;/,'const configured=false;');
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('https://www.youtube.com/**',r=>r.abort());
await page.addInitScript(()=>{window.YT={Player:class{constructor(id,opts){this.t=0;this.state=2;this.opts=opts;this.frame=document.createElement('iframe');setTimeout(()=>opts.events.onReady(),0);}getIframe(){return this.frame}getCurrentTime(){return this.t}getPlayerState(){return this.state}unMute(){}playVideo(){this.state=1;this.opts.events.onStateChange({data:1})}pauseVideo(){this.state=2;this.opts.events.onStateChange({data:2})}seekTo(t){this.t=t}loadVideoById(o){this.t=o.startSeconds;this.playVideo()}}};});
await page.route('http://localhost:8021/**',r=>r.fulfill({body:html,contentType:'text/html'}));
await page.goto('http://localhost:8021/?quizId=test-cloze#song/yesterday-once-more');
await page.evaluate(()=>{bank={...bank,quizId:'test-cloze',questions:[{start:0,end:1,sentence:'When I was young',prompt:'When I was _____',choices:['your','yard','young'],answer:2},{start:1.1,end:2,sentence:"I'd listen to the radio",prompt:"I'd listen to the _____",choices:['radio','rainbow','video'],answer:0},{start:2.1,end:3,sentence:'Waiting for my favorite songs',prompt:'Waiting for my favorite _____',choices:['sons','songs','socks'],answer:1}]};});
await page.locator('#enableVideo').click();await page.locator('#studentId').fill('TEST-001');await page.locator('#start').click();
const advance=async t=>page.evaluate(t=>{while(player.t<t&&player.state===1){player.t=Math.min(t,player.t+.1);controller.sample(player.t,1);controller.confirmStopped(player.state);}},t);
await advance(1.1);assert.equal(await page.locator('#choices button').count(),3);
await page.locator('#choices button').nth(0).click();assert.match(await page.locator('#playerStatus').innerText(),/Try again/);assert.equal(await page.locator('#choices button').nth(0).evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(185, 28, 28)');
await page.locator('#replay').click();assert.equal(await page.locator('#choices button').count(),0);await advance(1.1);
assert.equal(await page.evaluate(()=>answers[0].attempts.length),1);
await page.locator('#choices button').nth(2).click();assert.equal(await page.locator('#choices button').nth(2).evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(21, 128, 61)');assert.equal(await page.evaluate(()=>answerLocked),true);await page.waitForFunction(()=>index===1);await advance(2.1);
await page.locator('#choices button').nth(1).click();await page.locator('#choices button').nth(2).click();
await page.locator('#endPractice').click();assert.match(await page.locator('#prompt').innerText(),/33.33/);
await page.locator('#teacherOpen').click();let text=await page.locator('#scores').innerText();assert.match(text,/33.33/);assert.match(text,/I'd listen to the radio/);assert.match(text,/提前結束/);assert.equal(await page.locator('#scores tr').count(),1);
await page.screenshot({path:'tests/artifacts/teacher-progress-preview.png',fullPage:true});await page.locator('#teacherClose').click();
await page.reload();await page.locator('#teacherOpen').click();assert.equal(await page.locator('#scores tr').count(),1);await page.locator('#teacherClose').click();
await page.locator('#enableVideo').click();await page.locator('#studentId').fill('TEST-002');
await page.evaluate(()=>bank.questions=[{start:0,end:1,sentence:'One',prompt:'____',choices:['One','Two','Three'],answer:0}]);await page.locator('#start').click();await advance(1.1);await page.locator('#choices button').first().click();assert.equal(await page.evaluate(()=>active),true);await page.waitForFunction(()=>controller.phase==='outro');await page.evaluate(()=>{player.state=0;controller.sample(5,0);});assert.equal(await page.evaluate(()=>active),false);assert.match(await page.locator('#prompt').innerText(),/100.00/);
assert.deepEqual(errors,[]);console.log('PASS red/green colors, feedback lock, timer cancellation, browser: retry, replay hidden/locked, early exit, wrong sentence, local persistence after reload, final score after song end');await browser.close();
