import React,{useState,useRef,useEffect} from 'react';
import {sentenceParts,inlineTypes,publicParity} from './parity.mjs';
import {Picture,Region} from './ParityEditor.jsx';
import {useMediaResource} from './useMediaResource.jsx';
import {requiresMastery} from './mastery.mjs';
export function Drawing({block,value,onChange,disabled}) {
  const [color,setColor]=useState('#6d46db'),[tool,setTool]=useState('pen'),[redo,setRedo]=useState([]);
  const {url}=useMediaResource(block.canvasMode==='image'?block.background.assetId:undefined);
  const lines=useRef(value),active=useRef(false);lines.current=value;
  const point=e=>{const r=e.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(1000,(e.clientX-r.left)/r.width*1000)),Math.max(0,Math.min(600,(e.clientY-r.top)/r.height*600))];};
  const erase=e=>{const [x,y]=point(e);onChange(lines.current.filter(l=>!l.points.some(p=>Math.hypot(p[0]-x,p[1]-y)<25)));};
  return <div className="lh-drawing"><svg viewBox="0 0 1000 600" aria-label="繪圖畫布" onPointerDown={e=>{if(disabled)return;e.currentTarget.setPointerCapture(e.pointerId);active.current=true;setRedo([]);if(tool==='erase')return erase(e);onChange([...lines.current,{color,width:tool==='highlight'?18:6,points:[point(e)]}]);}} onPointerMove={e=>{if(!active.current||disabled)return;if(tool==='erase')return erase(e);const next=structuredClone(lines.current);if(!next.length||next.reduce((n,l)=>n+l.points.length,0)>=2500)return;next.at(-1).points.push(point(e));onChange(next);}} onPointerUp={()=>active.current=false} onPointerCancel={()=>active.current=false}>
    {url&&<image href={url} width="1000" height="600" preserveAspectRatio="xMidYMid meet"><title>{block.background.alt}</title></image>}
    {value.map((l,i)=><polyline key={i} points={l.points.map(p=>p.join(',')).join(' ')} stroke={l.color} strokeWidth={l.width} opacity={l.width===18?.4:1} fill="none" strokeLinecap="round" strokeLinejoin="round"/>)}
  </svg><div className="lh-row"><label>工具<select disabled={disabled} value={tool} onChange={e=>setTool(e.target.value)}><option value="pen">畫筆</option><option value="highlight">螢光筆</option><option value="erase">橡皮擦</option></select></label><label>顏色<input disabled={disabled} type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><button disabled={disabled||!value.length} onClick={()=>{setRedo([...redo,value.at(-1)]);onChange(value.slice(0,-1));}}>復原</button><button disabled={disabled||!redo.length} onClick={()=>{onChange([...value,redo.at(-1)]);setRedo(redo.slice(0,-1));}}>重做</button><button disabled={disabled||!value.length} onClick={()=>{setRedo([...value].reverse());onChange([]);}}>清除</button></div></div>;
}
export function ParityQuestion({block,disabled,onSubmit,savedAnswer,savedAttemptId,allowRetry=false}) {
  const b=block.blanks?.some(x=>x.answers)||block.anchors?.some(a=>a.labelId)||block.regions?.some(r=>r.correct!==undefined)?publicParity(block):block;
  const [answer,setAnswer]=useState(b.type==='hotspot'||b.type==='draw'?[]:{}),[selected,setSelected]=useState(''),[error,setError]=useState(''),[state,setState]=useState('idle');
  const attempt=useRef(crypto.randomUUID());const lock=disabled||state!=='idle';
  useEffect(()=>{if(savedAnswer!==undefined){setAnswer(savedAnswer);setState(allowRetry?'idle':'sent');if(allowRetry)attempt.current=crypto.randomUUID();}},[savedAttemptId,allowRetry]);
  const set=(id,value)=>setAnswer(a=>({...a,[id]:value}));
  const assign=(id,v)=>{if(lock||!v)return;if(b.type==='label')setAnswer(a=>Object.fromEntries([...Object.entries(a).filter(([k,x])=>k!==id&&x!==v),[id,v]]));else set(id,v);setSelected('');};
  const toggle=id=>{if(!lock)setAnswer(a=>a.includes(id)?a.filter(v=>v!==id):[...a,id]);};
  const pool=inlineTypes.includes(b.type)?[...new Set(b.blanks.flatMap(x=>x.choices||[]))]:[];
  return <section className="lh-answer lh-parity-question" data-question-type={b.type}>
    {inlineTypes.includes(b.type)&&<>
      <div className="lh-sentence">{sentenceParts(b.sentence).map((p,i)=>p.text?<span key={i}>{p.text}</span>:b.type==='blank'?<input key={p.blank} aria-label={`空格 ${b.blanks.findIndex(x=>x.id===p.blank)+1}`} disabled={lock} value={answer[p.blank]||''} onChange={e=>set(p.blank,Array.from(e.target.value).slice(0,200).join(''))}/>:b.type==='dropdown'?<select key={p.blank} aria-label={`空格 ${b.blanks.findIndex(x=>x.id===p.blank)+1}`} disabled={lock} value={answer[p.blank]||''} onChange={e=>set(p.blank,e.target.value)}><option value="">選擇答案</option>{b.blanks.find(x=>x.id===p.blank)?.choices.map(v=><option key={v}>{v}</option>)}</select>:<button key={p.blank} disabled={lock} className="lh-blank-target" aria-label={`空格 ${b.blanks.findIndex(x=>x.id===p.blank)+1} ${answer[p.blank]||'未填'}`} onClick={()=>selected?assign(p.blank,selected):set(p.blank,'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const v=e.dataTransfer.getData('text/plain');if(pool.includes(v))assign(p.blank,v);}}>{answer[p.blank]||'拖曳或點選答案'}</button>)}</div>
      {b.type==='drag'&&<><p>拖曳答案；觸控或鍵盤可先選答案，再選空格。點已填空格可清除。</p><div className="lh-token-pool">{pool.map(v=><button key={v} disabled={lock} draggable={!lock} aria-pressed={selected===v} onClick={()=>setSelected(v)} onDragStart={e=>e.dataTransfer.setData('text/plain',v)}>{v}</button>)}</div></>}
    </>}
    {b.type==='label'&&<><p>先選標籤，再點圖片上的位置；也可拖曳或用下方選單。</p><div className="lh-token-pool">{b.labels.map(l=><button key={l.id} disabled={lock} draggable={!lock} aria-pressed={selected===l.id} onClick={()=>setSelected(l.id)} onDragStart={e=>e.dataTransfer.setData('text/plain',l.id)}>{l.text}</button>)}</div><Picture block={b}>{b.anchors.map((a,i)=><button key={a.id} disabled={lock} className={`lh-anchor lh-anchor-${a.direction}`} style={{left:`${a.x*100}%`,top:`${a.y*100}%`}} onClick={()=>assign(a.id,selected)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(b.labels.some(l=>l.id===id))assign(a.id,id);}} aria-label={`錨點 ${i+1}`}>{b.labels.find(l=>l.id===answer[a.id])?.text||i+1}</button>)}</Picture>{b.anchors.map((a,i)=><label key={a.id}>錨點 {i+1}<select disabled={lock} value={answer[a.id]||''} onChange={e=>assign(a.id,e.target.value)}><option value="">選擇標籤</option>{b.labels.map(l=><option key={l.id} value={l.id}>{l.text}</option>)}</select></label>)}</>}
    {b.type==='hotspot'&&<><p>點選一個或多個區域，再點一次取消。</p><Picture block={b}><svg className="lh-regions" viewBox="0 0 1000 1000" preserveAspectRatio="none">{b.regions.map((r,i)=><Region key={r.id} region={r} role="button" tabIndex={lock?-1:0} aria-label={`區域 ${i+1}`} aria-pressed={answer.includes(r.id)} className={answer.includes(r.id)?'selected':''} onClick={()=>toggle(r.id)} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();toggle(r.id);}}}/>)}</svg></Picture><div className="lh-token-pool">{b.regions.map((r,i)=><button key={r.id} disabled={lock} aria-pressed={answer.includes(r.id)} onClick={()=>toggle(r.id)}>區域 {i+1}</button>)}</div></>}
    {b.type==='draw'&&<Drawing block={b} value={answer} onChange={setAnswer} disabled={lock}/>}
    <button className="lh-primary" disabled={lock} onClick={async()=>{setState('sending');setError('');try{const next=await onSubmit(answer,attempt.current);const retry=requiresMastery(block)&&next?.feedback?.outcome!=='full';setState(retry?'idle':'sent');if(retry)attempt.current=crypto.randomUUID();}catch(e){setError(e.message);setState('idle');}}}>{state==='sent'?'已提交，等待老師':state==='sending'?'提交中…':'提交答案'}</button>
    {error&&<p role="alert" className="lh-error">{error}</p>}
  </section>;
}
