import test from 'node:test';
import assert from 'node:assert/strict';
import {BasketballAudio,CELEBRATION_SECONDS} from '../src/BasketballAudio.js';
class Param{value=0;setValueAtTime(v){this.value=v;}linearRampToValueAtTime(v){this.value=v;}exponentialRampToValueAtTime(v){this.value=v;}setTargetAtTime(v){this.value=v;}}
class Node{gain=new Param();frequency=new Param();connect(other){this.destination=other;return other;}disconnect(){this.disconnected=true;}start(){this.started=true;}stop(){this.stopped=true;}}
class Context{currentTime=0;state='running';sampleRate=8000;destination={};createGain(){return new Node();}createOscillator(){return new Node();}createBiquadFilter(){return new Node();}createBufferSource(){return new Node();}createBuffer(c,n){return {getChannelData:()=>new Float32Array(n)};}resume(){this.state='running';return Promise.resolve();}close(){this.state='closed';return Promise.resolve();}}
test('Three audio buses use independent volumes; master mute suppresses all and restores values',async()=>{globalThis.window={AudioContext:Context};const a=new BasketballAudio();await a.unlock();const context=a.context;await a.unlock();assert.equal(a.context,context);a.configure({music:.3,sounds:.7,ambience:.15});assert.deepEqual(Object.values(a.bus).map(g=>g.gain.value),[.3,.7,.15]);a.configure({muted:true});assert.deepEqual(Object.values(a.bus).map(g=>g.gain.value),[0,0,0]);a.configure({muted:false,sounds:0});assert.deepEqual(Object.values(a.bus).map(g=>g.gain.value),[.3,0,.15]);a.dispose();});
test('Pausing and disposal cancel every scheduled basketball voice and music loop',async()=>{globalThis.window={AudioContext:Context};const a=new BasketballAudio();await a.unlock();a.start();a.shoot();a.hit();a.miss();a.boost();a.win();assert.ok(a.nodes.size>15);const nodes=[...a.nodes];a.pause();assert.equal(a.timer,null);assert.equal(a.nodes.size,0);assert.ok(nodes.every(n=>n.stopped));a.dispose();assert.equal(a.context.state,'closed');});

test('Celebration lasts five seconds longer and cancellation preserves unrelated audio',async()=>{globalThis.window={AudioContext:Context};const a=new BasketballAudio();await a.unlock();a.bounce();const prior=[...a.nodes];const calls=[];const original=a.noise.bind(a);a.noise=(duration,volume,bus,filter,delay=0)=>{calls.push({duration,delay});original(duration,volume,bus,filter,delay);};a.win();assert.equal(CELEBRATION_SECONDS,1.6+5);assert.equal(Math.max(...calls.map(c=>c.duration+c.delay)),6.6);const voices=[...a.celebrationNodes];assert.ok(voices.length>20);a.stopCelebration();assert.ok(voices.every(n=>n.stopped));assert.equal(a.celebrationNodes.size,0);assert.ok(prior.every(n=>a.nodes.has(n)));a.dispose();});
test('Starting celebration again stops previous cheers before scheduling new voices',async()=>{globalThis.window={AudioContext:Context};const a=new BasketballAudio();await a.unlock();a.win();const old=[...a.celebrationNodes];a.win();assert.ok(old.every(n=>n.stopped&&!a.nodes.has(n)));assert.ok(a.celebrationNodes.size>0);a.dispose();});
