import test from 'node:test';import assert from 'node:assert/strict';
import {newGame,reduce,restore,dropId,totalScore,turnSeed,save} from '../src/plinkoh-model.mjs';
import {makeBoard,createDrop,advance} from '../src/plinkoh-physics.mjs';
const ready=(count=2,rounds=6)=>{let s=reduce(newGame({count,rounds},42),{type:'INTRO_DONE'});s=reduce(s,{type:'SELECT',id:count-1});return reduce(reduce(s,{type:'INTRO_DONE'}),{type:'CARD_CHOOSE',card:null});};
const settle=(s,collision=4,slot=30)=>reduce(reduce(s,{type:'DROP'}),{type:'SETTLE',id:dropId(s),hits:Array.from({length:collision},(_,i)=>({id:String(i),points:1})),slot,slotIndex:0});
test('four reference scoring cases and cumulative totals',()=>{assert.equal(totalScore([{id:'p',points:4}],30).total,34);assert.equal(totalScore([{id:'p',points:6}],20).total,26);assert.equal(totalScore([{id:'p',points:7}],30).total+34,71);assert.equal(totalScore([{id:'p',points:9}],10).total+26,45);assert.throws(()=>totalScore([{id:'p',points:1},{id:'p',points:1}],10));});
test('teacher picks any team, exactly once; six rounds finish for 15 teams',()=>{let s=reduce(newGame({count:15},88),{type:'INTRO_DONE'});for(let r=1;r<=6;r++){assert.equal(s.round,r);for(let i=14;i>=0;i--){s=reduce(s,{type:'SELECT',id:i});s=reduce(s,{type:'INTRO_DONE'});s=reduce(s,{type:'CARD_CHOOSE',card:null});s=settle(s,4,10);s=reduce(s,{type:'TRANSFER'});s=reduce(s,{type:'TRANSFER_DONE'});s=reduce(s,{type:'NEXT'});if(i>0)assert.equal(reduce(s,{type:'SELECT',id:i}),s);}if(r<6)s=reduce(s,{type:'INTRO_DONE'});}assert.equal(s.phase,'FINISHED');assert.equal(s.history.length,90);assert.ok(s.teams.every(t=>t.score===84));});
test('double drop and stale settlement do not add points',()=>{let s=ready();s=reduce(s,{type:'DROP'});assert.equal(reduce(s,{type:'DROP'}),s);assert.equal(reduce(s,{type:'SETTLE',id:'old',hits:[],slot:30}),s);s=reduce(s,{type:'SETTLE',id:dropId(s),hits:[],slot:30,slotIndex:0});assert.equal(reduce(s,{type:'SETTLE',id:dropId(s),hits:[],slot:30}),s);assert.equal(s.teams[1].score,30);});
test('refresh before settlement rolls back turn; refresh after settlement keeps award',()=>{const s=ready();const falling=reduce(s,{type:'DROP'});assert.equal(restore(JSON.stringify(falling)).phase,'READY');assert.deepEqual(restore(falling).teams,s.teams);const done=settle(s);assert.equal(restore(done).phase,'TURN_DONE');assert.equal(restore(done).teams[1].score,34);});
test('skip, manual correction and early end are traceable',()=>{let s=ready();s=reduce(s,{type:'ADJUST',id:0,delta:-1,at:1});s=reduce(s,{type:'SKIP'});assert.equal(s.teams[0].score,-1);assert.equal(s.history[0].type,'adjust');assert.equal(s.history[1].type,'skip');s=reduce(s,{type:'END'});assert.equal(s.phase,'FINISHED');});
test('invalid storage is rejected and write failure is surfaced',()=>{assert.equal(restore('garbage'),null);assert.equal(restore({...ready(),completed:[0,0]}),null);assert.equal(restore({...ready(),teams:[{id:0,score:Infinity}]}),null);assert.equal(save({setItem(){throw Error('quota')}},ready()),false);});
function run(seed,round,zone,zones,fps){const s=createDrop(makeBoard(round,seed),zone,zones,seed);let guard=0;while(!s.done&&!s.failed&&guard++<10000)advance(s,1/fps);return s;}
test('fixed physics agrees at 30, 60 and 144 fps',()=>{for(let seed=1;seed<=30;seed++){const all=[30,60,144].map(fps=>run(seed,1+seed%6,1+seed%5,5,fps));assert.deepEqual(all[0].hits,all[1].hits);assert.deepEqual(all[1].hits,all[2].hits);assert.equal(all[0].slotIndex,all[2].slotIndex);assert.equal(all[0].time,all[2].time);}});
test('600 varied drops settle legally, without duplicate pegs or non-finite coordinates',()=>{let fails=0;let bounces=0;for(let seed=1;seed<=600;seed++){const s=run(seed,1+seed%6,1+seed%10,10,60);if(s.failed)fails++;assert.ok(Number.isFinite(s.ball.x+s.ball.y));assert.equal(new Set(s.hits.map(h=>h.id)).size,s.hits.length);if(s.done)assert.ok(s.slotIndex>=0&&s.slotIndex<s.board.slots.length);if(s.events.some(e=>e.type==='floor'))bounces++;}assert.equal(fails,0);assert.ok(bounces>500);});
test('changing top zones does not change bottom slots',()=>{let s=ready();const before=makeBoard(s.round,turnSeed(s));s=reduce(s,{type:'CONFIG',patch:{zones:5}});assert.deepEqual(makeBoard(s.round,turnSeed(s)),before);assert.equal(s.config.zones,5);const falling=reduce(s,{type:'DROP'});assert.equal(reduce(falling,{type:'CONFIG',patch:{zones:10}}),falling);});

// Reject impossible awards rather than saving a corrupt game.
test('out-of-board and impossible slot values cannot settle',()=>{const s=reduce(ready(),{type:'DROP'});for(const [slotIndex,slot]of [[-1,10],[3,10],[0,999],[0,-10]])assert.equal(reduce(s,{type:'SETTLE',id:dropId(s),hits:[],slotIndex,slot}),s);});
import {leaders} from '../src/plinkoh-model.mjs';
import {validateManifest} from '../src/model.mjs';
test('all-skipped final round produces shared winners and restart clears scores',()=>{let s=reduce(newGame({count:2,rounds:1},25),{type:'INTRO_DONE'});for(const id of [1,0]){s=reduce(s,{type:'SELECT',id});s=reduce(s,{type:'INTRO_DONE'});s=reduce(s,{type:'CARD_CHOOSE',card:null});s=reduce(s,{type:'SKIP'});s=reduce(s,{type:'NEXT'});}assert.equal(s.phase,'FINISHED');assert.equal(leaders(s).length,2);const fresh=newGame(s.config,26);assert.equal(fresh.history.length,0);assert.equal(fresh.round,1);assert.ok(fresh.teams.every(t=>t.score===0));});
test('Plink-oh is preserved as a built-in in backup validation',()=>{const m={format:'classroom-club',version:1,images:[],lessons:[],games:[{id:'plinkoh',name:'Plink-oh!',url:'#plinkoh'}]};assert.equal(validateManifest(m),m);});
