import {chromium,expect} from '@playwright/test';import fs from 'node:fs/promises';
const out='qa/plinkoh-powerups-20260919/regression';await fs.mkdir(out,{recursive:true});const b=await chromium.launch({channel:'msedge',headless:true});const p=await b.newPage({viewport:{width:1366,height:768}});const errors=[];p.on('pageerror',e=>errors.push(e.message));const checks=[];
const open=async()=>{await p.goto('http://127.0.0.1:5194');await p.getByRole('button',{name:/Plink-oh!/}).click();};const phase=async value=>{if(value==='READY'){await p.waitForFunction(()=>['READY','CARD_PICK'].includes(document.querySelector('.po-shell')?.dataset.phase));if(await p.locator('.po-card-picker').count())await p.getByRole('button',{name:/No card/}).click();}await expect(p.locator('.po-shell')).toHaveAttribute('data-phase',value,{timeout:25000});};const read=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('classroom-plinkoh-v1')));
await open();await p.getByRole('button',{name:/New game/}).click();await p.getByRole('button',{name:/Start!/}).click();await phase('SELECT_TEAM');await p.getByRole('button',{name:'Choose Team 2',exact:true}).click();await phase('READY');await p.getByRole('button',{name:'Drop zone 4',exact:true}).click();await p.getByRole('button',{name:'Drop zone 4',exact:true}).press('ArrowRight');await expect(p.getByRole('button',{name:'Drop zone 5',exact:true})).toHaveAttribute('aria-pressed','true');checks.push('keyboard zone selection');
await p.getByRole('button',{name:'Drop!',exact:true}).click();await phase('DROPPING');await p.waitForTimeout(500);await p.getByRole('button',{name:'Ⅱ Menu',exact:true}).click();const before=await p.locator('.po-falling-ball').getAttribute('style');await p.waitForTimeout(600);expect(await p.locator('.po-falling-ball').getAttribute('style')).toBe(before);await p.getByRole('button',{name:'Resume',exact:true}).click();await p.waitForTimeout(200);checks.push('pause freezes ball');await p.reload();await p.getByRole('button',{name:/Plink-oh!/}).click();await p.getByRole('button',{name:/Resume ·/}).click();await phase('READY');expect((await read()).teams.every(t=>t.score===0)).toBe(true);expect((await read()).selected).toBe(1);checks.push('refresh during drop rolls back without points');
await p.getByRole('button',{name:'Drop!',exact:true}).dblclick();await phase('TURN_DONE');let s=await read();expect(s.history.filter(h=>h.type==='drop').length).toBe(1);expect(s.history[0].total).toBe(s.history[0].collision+s.history[0].slot);checks.push('double-click one settlement');await p.reload();await p.getByRole('button',{name:/Plink-oh!/}).click();await p.getByRole('button',{name:/Resume ·/}).click();await phase('TURN_DONE');expect((await read()).history.length).toBe(1);await p.getByRole('button',{name:'Next team →',exact:true}).click();await expect(p.getByRole('button',{name:'Choose Team 2',exact:true})).toBeDisabled();await p.getByRole('button',{name:'Choose Team 1',exact:true}).click();await phase('READY');await p.getByRole('button',{name:'Skip team',exact:true}).click();await p.getByRole('button',{name:'Confirm',exact:true}).click();await p.getByRole('button',{name:'Next round →',exact:true}).click();await phase('SELECT_TEAM');expect((await read()).round).toBe(2);checks.push('used team disabled, skip completes round');
// Fresh deterministic six-round game through real UI; clock advances only animation time, physics remains fixed-step.
await p.evaluate(()=>{localStorage.removeItem('classroom-plinkoh-v1');localStorage.setItem('classroom-plinkoh-v1-settings',JSON.stringify({count:2,rounds:6,zones:5}));});await open();await p.getByRole('button',{name:/New game/}).click();await p.getByRole('button',{name:/Start!/}).click();await phase('SELECT_TEAM');await p.clock.install();
for(let round=1;round<=6;round++){for(const team of round%2?[2,1]:[1,2]){await p.getByRole('button',{name:`Choose Team ${team}`,exact:true}).click();await p.clock.runFor(1400);await phase('READY');await p.getByRole('button',{name:`Drop zone ${1+(round+team)%5}`,exact:true}).click();await p.getByRole('button',{name:'Drop!',exact:true}).click();await p.clock.runFor(24000);await phase('TURN_DONE');const next=p.getByRole('button',{name:/^(Next team →|Next round →|Results!)$/});await next.click();await p.clock.runFor(1600);}}
await phase('FINISHED');s=await read();expect(s.history.filter(h=>h.type==='drop').length).toBe(12);await p.screenshot({path:out+'/six-round-results.png'});checks.push('12 real drops complete six rounds');await p.clock.resume();
const layouts=[];for(const count of [2,5,10,15]){await p.evaluate(c=>{localStorage.removeItem('classroom-plinkoh-v1');localStorage.setItem('classroom-plinkoh-v1-settings',JSON.stringify({count:c,rounds:6,zones:10}));},count);await open();await p.getByRole('button',{name:/New game/}).click();await p.getByRole('button',{name:/Start!/}).click();await phase('SELECT_TEAM');await p.getByRole('button',{name:`Choose Team ${count}`,exact:true}).click();await phase('READY');for(const [width,height]of [[1366,768],[1920,1080],[1024,768],[820,600]]){await p.setViewportSize({width,height});await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const board=await p.locator('.po-board').boundingBox();const score=await p.locator('.po-scoreboard').boundingBox();expect(board.y).toBeGreaterThanOrEqual(0);expect(board.y+board.height).toBeLessThanOrEqual(height+1);expect(score.x+score.width).toBeLessThanOrEqual(width+1);expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);layouts.push({count,width,height,board});await p.screenshot({path:`${out}/layout-${count}-${width}.png`});}}
checks.push('16 team-count/viewport combinations');
await p.getByRole('button',{name:'Options',exact:true}).click();await p.getByRole('combobox',{name:'Drop zones',exact:true}).selectOption('5');await p.getByRole('button',{name:'Back to game',exact:true}).click();expect(await p.getByRole('group',{name:'Drop zones'}).getByRole('button').count()).toBe(5);expect((await read()).round).toBe(1);checks.push('mid-game 10 to 5 top zones');
await p.getByRole('button',{name:'Add one to Team 15',exact:true}).click();await p.getByRole('button',{name:'Confirm',exact:true}).click();expect((await read()).teams[14].score).toBe(1);checks.push('confirmed teacher adjustment saved');
await p.getByRole('button',{name:'Ⅱ Menu',exact:true}).click();await p.getByRole('button',{name:'Classroom Club',exact:true}).click();await expect(p.getByRole('button',{name:/Plink-oh!/})).toBeVisible();await p.reload();await expect(p.getByRole('button',{name:/Plink-oh!/})).toBeVisible();await p.getByRole('button',{name:/^Manage collection/}).first().click();await p.getByRole('button',{name:'Hide Plink-oh!',exact:true}).click();await p.getByRole('button',{name:'Game collection',exact:true}).click();await expect(p.getByRole('button',{name:/Plink-oh!/})).toHaveCount(0);await p.getByRole('button',{name:/^Manage collection/}).first().click();await p.getByRole('button',{name:'Show Plink-oh!',exact:true}).click();checks.push('hub reload and hide/show');
await p.goto('http://127.0.0.1:5194/qa/plinkoh-20260919/sound-check.html');await expect(p.locator('section.card')).toHaveCount(8);checks.push('8 A/B reference pairs');expect(errors).toEqual([]);await fs.writeFile(out+'/browser-report.json',JSON.stringify({passed:true,checks,layouts,errors,fullGame:s},null,2));console.log(JSON.stringify({passed:true,checks,layouts:layouts.length,errors}));await b.close();
