import test from 'node:test';
import assert from 'node:assert/strict';
import {sound} from '../src/sound.js';
const created=[];
const parameter=()=>({value:0,setValueAtTime(v){this.value=v;},linearRampToValueAtTime(v){this.value=v;},setTargetAtTime(v){this.value=v;},exponentialRampToValueAtTime(v){this.value=v;},cancelScheduledValues(){}});
function node(kind){const n={kind,frequency:parameter(),Q:parameter(),gain:parameter(),connect(next){return next;},disconnect(){this.disconnected=true;},start(){this.started=true;},stop(){this.stopped=true;}};created.push(n);return n;}
globalThis.window={AudioContext:class {state='running';sampleRate=44100;currentTime=0;destination={};resume(){return Promise.resolve();}createBuffer(channels,length){const samples=new Float32Array(length);return {getChannelData(){return samples;}};}createBufferSource(){return node('noise');}createBiquadFilter(){return node('filter');}createGain(){return node('gain');}createOscillator(){return node('note');}}};
test('stationary pointer becomes silent within 150 ms; repeated movement reuses one source',async()=>{await sound.unlock();sound.configure({muted:false,scratchVolume:.35,victoryVolume:.5});sound.pulse();sound.pulse();assert.equal(created.filter(n=>n.kind==='noise').length,1);assert.ok(sound.scratch);await new Promise(r=>setTimeout(r,150));assert.equal(sound.scratch,null);assert.equal(created.find(n=>n.kind==='noise').stopped,true);});
test('muting interrupts scratch and victory, and suppresses new playback',()=>{sound.startScratch();sound.victory();assert.equal(sound.voices.length,7);const playing=created.filter(n=>(n.kind==='noise'||n.kind==='note')&&!n.stopped);sound.configure({muted:true,scratchVolume:.35,victoryVolume:.5});assert.equal(sound.scratch,null);assert.equal(sound.voices.length,0);assert.ok(playing.every(n=>n.stopped));const count=created.length;sound.startScratch();sound.victory();assert.equal(created.length,count);});
test('revealing uses a continuous source until stopped; volume updates do not restart it',()=>{sound.configure({muted:false,scratchVolume:.2,victoryVolume:.8});sound.startScratch();const source=sound.scratch.source;sound.configure({muted:false,scratchVolume:.6,victoryVolume:.8});assert.equal(sound.scratch.source,source);assert.ok(Math.abs(sound.scratch.gain.gain.value-.42)<.00001);sound.stopAll();assert.equal(source.stopped,true);assert.equal(sound.scratch,null);});
