import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
const base='http://127.0.0.1:5184',out=new URL('../qa/unscramble-dopamine-20260915/',import.meta.url),results=[];
async function api(action,payload={},student=false){const r=await fetch(base+'/api/live-activity',{method:'POST',headers:{'content-type':'application/json',...(!student?{authorization:'Bearer local-teacher'}:{})},body:JSON.stringify({action,...payload})});const d=await r.json();if(!r.ok)throw Error(d.message);return d;}
const deck=(await api('listDecks')).decks.find(d=>d.id==='family-20260915');let room=(await api('createRoom',{deckId:deck.id,className:'新版預覽｜大圖與音效',maxGroups:10})).room;
const entries=[];for(let i=0;i<10;i++){const j=await api('join',{roomId:room.id,members:`98${i}01 98${i}02 98${i}03`,joinNonce:randomUUID()},true);entries.push({roomId:room.id,groupId:j.groupId,token:j.token});}
// Use the longest approved sentence to exercise wrapping, rather than only sister.
for(let i=0;i<9;i++)room=(await api('next',{roomId:room.id,revision:room.revision})).room;
assert.equal(room.questionIndex,4);assert.equal(room.phase,'open');
for(let i=0;i<9;i++)await api('submit',{...entries[i],attemptId:randomUUID(),questionIndex:4,revision:room.revision,lines:[deck.questions[4].prompt.split(' '),deck.questions[4].answer.split(' ')]},true);
const browser=await chromium.launch({headless:true,channel:'chrome'}),teacher=await browser.newPage({viewport:{width:1366,height:768}});
await teacher.goto(base+'/unscramble');await teacher.locator('.ul-record-list article').filter({hasText:'新版預覽｜大圖與音效'}).first().getByRole('button',{name:'開啟紀錄／場次 →',exact:true}).click();await expect(teacher.locator('.ul-group')).toHaveCount(10);await expect(teacher.locator('.ul-stage .ul-picture img')).toBeVisible();await teacher.evaluate(()=>document.fonts.ready);
for(const [width,height] of [[1366,768],[1440,1000],[1920,1080]]){await teacher.setViewportSize({width,height});const m=await teacher.evaluate(()=>{const rect=s=>document.querySelector(s).getBoundingClientRect();return {pictureWidth:rect('.ul-stage .ul-picture').width,recordWidth:rect('.ul-teacher>.ul-section').width,bottom:Math.max(...[...document.querySelectorAll('.ul-group')].map(e=>e.getBoundingClientRect().bottom)),nextBottom:rect('.ul-next').bottom,overflow:document.documentElement.scrollWidth>innerWidth};});assert.ok(m.bottom<=height,`Cards overflow ${width}: ${m.bottom}`);assert.ok(m.nextBottom<=height,`Next overflow ${width}: ${m.nextBottom}`);assert.equal(m.overflow,false);assert.ok(m.pictureWidth>m.recordWidth*1.4);results.push({width,height,...m});await teacher.screenshot({path:new URL(`teacher-dopamine-${width}x${height}.png`,out).pathname.replace(/^\/(\w:)/,'$1'),fullPage:true});}
await teacher.emulateMedia({reducedMotion:'reduce'});assert.equal(await teacher.locator('.ul-next').evaluate(e=>getComputedStyle(e).animationName),'none');await teacher.emulateMedia({reducedMotion:'no-preference'});assert.equal(await teacher.locator('.ul-next').evaluate(e=>{e.disabled=true;return getComputedStyle(e).animationName;}),'none');await teacher.locator('.ul-next').evaluate(e=>e.disabled=false);
const student=await browser.newPage({viewport:{width:1024,height:768}});await student.goto(base+`/join?room=${room.id}`);await student.evaluate(e=>localStorage.setItem(`ul-entry:${e.roomId}`,JSON.stringify(e)),entries[9]);await student.reload();await expect(student.getByTestId('wordbank').locator('.ul-word')).toHaveCount(5);await expect(student.locator('.ul-picture img')).toBeVisible({timeout:30000});await student.evaluate(()=>document.fonts.ready);
for(const [width,height] of [[1024,768],[768,1024],[390,844]]){await student.setViewportSize({width,height});const m=await student.evaluate(()=>{const word=document.querySelector('.ul-word'),p=document.querySelector('.ul-puzzle').getBoundingClientRect(),img=document.querySelector('.ul-play-layout>.ul-picture').getBoundingClientRect();return {font:parseFloat(getComputedStyle(word).fontSize),puzzleWidth:p.width,imageWidth:img.width,overflow:document.documentElement.scrollWidth>innerWidth,clipped:[...document.querySelectorAll('.ul-word')].some(e=>e.scrollWidth>e.clientWidth+1)};});assert.equal(m.font,width<=650?26.25:28.75);assert.equal(m.overflow,false);assert.equal(m.clipped,false);if(width===1024)assert.ok(m.puzzleWidth>m.imageWidth*1.7);results.push({width,height,...m});await student.screenshot({path:new URL(`student-dopamine-${width}x${height}.png`,out).pathname.replace(/^\/(\w:)/,'$1'),fullPage:true});}
await fs.writeFile(new URL('layout-results.json',out),JSON.stringify({passed:true,roomId:room.id,studentUrl:base+`/join?room=${room.id}`,results,reducedMotion:true,disabledNextAnimationStopped:true},null,2));console.log(JSON.stringify({passed:true,roomId:room.id,results},null,2));await browser.close();
