import {test} from 'node:test';
import assert from 'node:assert/strict';
import {members,validateDeck,evaluate,stageNext,publicRoom,teacherRoom} from '../functions/unscramble-model.mjs';
const q={prompt:"Who's she?",answer:"She's my sister.",imageId:'image1'};
test('student numbers preserve leading zeros and accept many space-separated members',()=>{assert.deepEqual(members(' 0040200   40230\n40215 '),['0040200','40230','40215']);assert.equal(members(Array.from({length:100},(_,i)=>String(40000+i)).join(' ')).length,100);assert.throws(()=>members('40200 name'));assert.throws(()=>members('40200 40200'));});
test('both lines must use the exact token multiset; reordered sentences are wrong',()=>{assert.equal(evaluate(q,[["Who's",'she?'],["She's",'my','sister.']]).correct,true);assert.equal(evaluate(q,[["Who's",'sister.'],["She's",'my','she?']]).correct,false);assert.throws(()=>evaluate(q,[["Who's",'she?'],["She's",'my','my']]));});
test('deck normalization preserves contractions and duplicate questions',()=>{const d=validateDeck({name:'Test',questions:[{...q,prompt:'Who’s   she?'},q]});assert.equal(d.questions[0].prompt,q.prompt);assert.equal(d.questions.length,2);assert.throws(()=>validateDeck({name:'',questions:[q]}));});
test('teacher moves preview to open, then locks next picture and reviews previous question',()=>{let r={phase:'preview',questionIndex:0,reviewIndex:null,revision:0,questions:[q,q]};r=stageNext(r);assert.equal(r.phase,'open');r=stageNext(r);assert.equal(r.phase,'preview');assert.equal(r.questionIndex,1);assert.equal(r.reviewIndex,0);r=stageNext(stageNext(r));assert.equal(r.phase,'ended');assert.equal(r.reviewIndex,1);});
test('student projection contains no correct sentence order, other groups or access hashes',()=>{const r={id:'room',questions:[q],questionIndex:0,groups:{a:{id:'a',number:1,members:['40200'],tokenHash:'secret',attempts:[]},b:{id:'b',members:['40300'],tokenHash:'other',attempts:[]}}};const s=publicRoom(r,'a');assert.ok(!JSON.stringify(s).includes('secret'));assert.ok(!JSON.stringify(s).includes('40300'));assert.ok(!s.questions);assert.ok(!s.answer);assert.equal(s.tokens.length,5);assert.ok(!JSON.stringify(teacherRoom(r)).includes('tokenHash'));});
