import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs';
const origin='http://127.0.0.1:5196',out='qa/vocabulary-20260920';fs.mkdirSync(out,{recursive:true});const errors=[],results=[];
const browser=await chromium.launch({channel:'chrome',headless:true});const contexts=[];let teacher;
async function api(action,body={},student=false){const r=await fetch(origin+'/api/vocabulary-activity',{method:'POST',headers:{'Content-Type':'application/json',...(student?{}:{Authorization:'Bearer local-teacher'})},body:JSON.stringify({action,...body})});const d=await r.json();if(!r.ok)throw Error(`${action}: ${d.message}`);return d;}
async function page(size){const c=await browser.newContext({viewport:size});contexts.push(c);const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));return p;}
async function until(fn,label,ms=15000){const start=Date.now();while(Date.now()-start<ms){if(await fn())return;await new Promise(r=>setTimeout(r,150));}throw Error('Timed out: '+label);}
async function write(p,erase=false){const c=p.getByLabel('Writing board');await p.getByRole('button',{name:'Blue pen',exact:true}).waitFor();await until(()=>p.getByRole('button',{name:'Blue pen',exact:true}).isEnabled(),'pen enabled');await until(async()=>await p.locator('.vl-loading').count()===0,'template ready');const box=await c.boundingBox();await p.mouse.move(box.x+box.width*.15,box.y+box.height*.55);await p.mouse.down();await p.mouse.move(box.x+box.width*.15,box.y+box.height*.2,{steps:7});await p.mouse.move(box.x+box.width*.28,box.y+box.height*.4,{steps:7});await p.mouse.move(box.x+box.width*.4,box.y+box.height*.2,{steps:7});await p.mouse.move(box.x+box.width*.4,box.y+box.height*.55,{steps:7});await p.mouse.up();if(erase){await p.getByRole('button',{name:'Eraser',exact:true}).click();await p.mouse.move(box.x+box.width*.2,box.y+box.height*.25);await p.mouse.down();await p.mouse.move(box.x+box.width*.32,box.y+box.height*.36,{steps:7});await p.mouse.up();}await p.getByRole('button',{name:'Submit →',exact:true}).click();}
try{
 teacher=await page({width:1440,height:1000});await teacher.goto(origin+'/vocabulary');await teacher.getByRole('button',{name:'載入 SF1 U01 五題圖卡'}).click();await teacher.getByRole('heading',{name:'SF1 U01｜五題單字圖卡'}).waitFor();
 await teacher.locator('.ul-deck').filter({has:teacher.getByRole('heading',{name:'SF1 U01｜五題單字圖卡',exact:true})}).getByRole('button',{name:'建立新場次 →'}).click();await teacher.getByLabel('班級名稱').fill('20260921三年甲班 · QA');await teacher.getByLabel('組數',{exact:true}).selectOption('15');await teacher.getByRole('button',{name:'建立場次',exact:true}).click();await teacher.getByRole('heading',{name:'Live answers',exact:true}).waitFor();await teacher.getByRole('button',{name:'QR',exact:true}).click();const href=await teacher.getByRole('link',{name:'學生加入連結 ↗',exact:true}).getAttribute('href'),roomId=new URL(href).searchParams.get('room');
 const students=await Promise.all(Array.from({length:15},async(_,i)=>{const p=await page({width:1024,height:768});await p.goto(href);await p.getByLabel('同組學號').fill(`08${100+i} 08${200+i}`);await p.getByRole('button',{name:'Join activity →'}).click();try{await p.getByLabel('Writing board').waitFor({timeout:60000});}catch(e){console.log('JOIN FAILED',i,await p.locator('body').innerText(),errors);await p.screenshot({path:out+`/join-failure-${i}.png`});throw e;}return p;}));
 await teacher.getByRole('button',{name:'QR',exact:true}).click();await teacher.getByRole('button',{name:'Next · 開放作答 →',exact:true}).click();await Promise.all(students.map((p,i)=>write(p,i===0)));await until(async()=>Object.keys((await api('teacherState',{roomId})).room.groups).length===15,'15 joins');
 await until(async()=>(await api('teacherState',{roomId})).room.drawings.filter(d=>d.status==='submitted').length===15,'15 submissions');results.push('15 independent browser students draw and submit');
 await teacher.locator('.vl-group-open').first().click();await teacher.getByRole('button',{name:'▶ 載入筆跡重播'}).click();await teacher.getByRole('button',{name:'▶ Play handwriting'}).click();await teacher.screenshot({path:out+'/teacher-replay.png'});results.push('teacher replay loads drawing and eraser');
 await teacher.getByRole('button',{name:'退回重寫',exact:true}).click();const state=(await api('teacherState',{roomId})).room;const g1=Object.values(state.groups).find(g=>g.number===1);const target=await (async()=>{for(const p of students){if((await p.locator('.ul-wordmark b').innerText()).trim()==='1')return p;}return students[0];})();
 await until(()=>target.getByRole('button',{name:'Blue pen',exact:true}).isEnabled(),'returned writing unlocks');await write(target);await teacher.getByRole('button',{name:'5 分',exact:true}).click();await teacher.getByRole('button',{name:'Close ✕',exact:true}).click();results.push('teacher returns and grades from UI');
 for(const [k,size] of Object.entries({projector1366:{width:1366,height:768},projector1920:{width:1920,height:1080}})){await teacher.setViewportSize(size);await teacher.screenshot({path:`${out}/${k}.png`});assert.equal(await teacher.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 let r=(await api('teacherState',{roomId})).room;for(const g of Object.values(r.groups)){if(g.scores?.[0])continue;await api('score',{roomId,groupId:g.id,questionIndex:0,score:1+(g.number-1)%5,requestId:crypto.randomUUID()});}
 await new Promise(r=>setTimeout(r,1200));await students[1].screenshot({path:out+'/student-reward.png'});await new Promise(r=>setTimeout(r,3500));
 for(const size of [{width:1024,height:768},{width:768,height:1024},{width:390,height:844}]){await target.setViewportSize(size);await target.screenshot({path:`${out}/student-${size.width}x${size.height}.png`});assert.equal(await target.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 await target.setViewportSize({width:1024,height:768});await target.reload();await target.getByText('5 points!',{exact:true}).waitFor();results.push('refresh preserves group and score; three student viewports fit');
 r=(await api('teacherState',{roomId})).room;r=(await api('next',{roomId,revision:r.revision,confirmIncomplete:true})).room;r=(await api('next',{roomId,revision:r.revision})).room;await until(()=>target.getByRole('button',{name:'Blue pen',exact:true}).isEnabled(),'second question open');
 // Preserve a draft through a browser refresh, then verify a disconnected submit cannot score.
 const c=target.getByLabel('Writing board'),b=await c.boundingBox();await target.mouse.move(b.x+80,b.y+90);await target.mouse.down();await target.mouse.move(b.x+160,b.y+170,{steps:12});await target.mouse.up();await target.reload();await until(()=>target.getByRole('button',{name:'Submit →',exact:true}).isEnabled(),'draft survives refresh');results.push('unsubmitted handwriting survives browser refresh');
 teacher.on('dialog',d=>d.accept());await teacher.getByRole('button',{name:'提早結束',exact:true}).click();await teacher.getByRole('heading',{name:'Wonderful teamwork!'}).waitFor();const celebration=Date.now();await teacher.screenshot({path:out+'/teacher-celebration.png'});await until(async()=>await teacher.locator('.vl-finale.celebrating').count()===0,'ten second celebration ends',13000);assert.ok(Date.now()-celebration>=9500);await teacher.screenshot({path:out+'/teacher-final.png'});results.push('early finish celebrates for ten seconds then holds standings');
 await teacher.getByLabel('查看題目紀錄').selectOption('0');await until(async()=>await teacher.locator('.vl-group .vl-snapshot').count()===15,'archived snapshots read back');await teacher.locator('.vl-group-open').first().click();assert.equal(await teacher.getByRole('button',{name:'▶ 載入筆跡重播'}).count(),0);await teacher.screenshot({path:out+'/history-answer.png'});results.push('history contains final snapshots without replay');assert.deepEqual(errors,[]);
 fs.writeFileSync(out+'/browser.json',JSON.stringify({passed:results.length,results,errors,roomId},null,2));console.log(JSON.stringify({results,errors,roomId}));
}catch(e){if(teacher)await teacher.screenshot({path:out+'/failure.png'}).catch(()=>{});throw e;}finally{await browser.close();}
